package isolation

import (
	"bytes"
	"context"
	"debug/elf"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	containerfiles "github.com/ctxloom/ctxloom/container"
	"github.com/ctxloom/ctxloom/internal/shared/clidiag"
)

// imageBuildTimeout caps one on-the-fly agent-image build. The production
// builds are network-bound (npm / the kiro installer / an official-image pull)
// so the first build takes minutes; a hung build must still degrade rather than
// block the LLM forever.
const imageBuildTimeout = 10 * time.Minute

// resolveSelfExe is the seam over the running-binary check (overridable in
// tests, like hostHomeDir): it yields the path buildImage bakes into the image.
var resolveSelfExe = selfLinuxExe

// baseImageTag is the local tag the shared base stage builds to; the agent
// stages FROM it via --build-arg BASE_IMAGE.
const baseImageTag = "ctxloom-agent-base:latest"

// buildSource is one way to produce the agent image locally: the agent-stage
// Containerfile (a rendered overlay onto a client-shipped base, or the embedded
// install recipe), optionally preceded by a BASE stage, plus a description for
// degrade diagnostics.
type buildSource struct {
	desc          string
	containerfile []byte
	// base, when non-nil, is stage 1: a base image built first and tagged
	// baseImageTag, which the agent stage above FROMs via --build-arg.
	base *baseStage
}

// baseStage describes the shared stage-1 base image build: a user-provided
// Containerfile on disk (its directory is the build context, so its COPYs
// work), or the embedded default base.
type baseStage struct {
	desc          string
	path          string // user Containerfile path ("" = embedded default)
	containerfile []byte // embedded default content (used when path == "")
}

// defaultBaseStage is the embedded shared base (container/base/Containerfile).
func defaultBaseStage() *baseStage {
	return &baseStage{desc: "default base Containerfile", containerfile: containerfiles.Base}
}

// userBaseStage is a user-provided base Containerfile on disk.
func userBaseStage(path string) *baseStage {
	return &baseStage{desc: "user base Containerfile " + path, path: path}
}

// buildSources orders a profile's local-build sources. An explicit base-IMAGE
// override wins outright (the caller asserts the client lives there). Else, for
// a profile with an agent-stage recipe, a user base CONTAINERFILE leads (their
// environment, our agent layers), the client's OFFICIAL image overlay follows
// (a fresh --pull build rides the vendor's most recent client), and the
// embedded install recipe over the default base (which fetches the MOST RECENT
// client CLI — never pinned) is the fallback. Empty means the image cannot be
// built locally.
func buildSources(p containerProfile, baseOverride, baseContainerfile string) []buildSource {
	if baseOverride != "" {
		return []buildSource{{
			desc:          "overlay on base image " + baseOverride,
			containerfile: overlayContainerfile(baseOverride, p.validate),
		}}
	}
	var out []buildSource
	if len(p.containerfile) > 0 && baseContainerfile != "" {
		out = append(out, buildSource{
			desc:          "agent stage on the user base Containerfile " + baseContainerfile,
			containerfile: p.containerfile,
			base:          userBaseStage(baseContainerfile),
		})
	}
	if p.officialImage != "" {
		out = append(out, buildSource{
			desc:          "overlay on the official client image " + p.officialImage,
			containerfile: overlayContainerfile(p.officialImage, p.validate),
		})
	}
	if len(p.containerfile) > 0 {
		out = append(out, buildSource{
			desc:          "embedded install Containerfile",
			containerfile: p.containerfile,
			base:          defaultBaseStage(),
		})
	}
	return out
}

// overlayContainerfile renders the generated OVERLAY Containerfile: the running
// ctxloom binary layered onto a base image that already ships the client CLI
// (the vendor's official image, or a user-provided base). ENTRYPOINT is reset
// because the isolation runtime supplies the full in-container argv; the
// validate command gates the build so a base without a runnable client never
// ships as an agent image.
func overlayContainerfile(baseImage, validate string) []byte {
	var b strings.Builder
	b.WriteString("# Generated by ctxloom: the running ctxloom binary overlaid onto a base\n")
	b.WriteString("# image that already ships the client CLI.\n")
	b.WriteString("FROM " + baseImage + "\n")
	b.WriteString("ENTRYPOINT []\n")
	if validate != "" {
		b.WriteString("RUN " + validate + "\n")
	}
	b.WriteString("COPY ctxloom /usr/local/bin/ctxloom\n")
	b.WriteString("RUN /usr/local/bin/ctxloom version\n")
	return []byte(b.String())
}

// ensureImage is the image half of the container degrade gate, used by run and
// the map/weave fan-out alike. Present → run. Absent and locally buildable →
// build (official-image overlay first, then the install Containerfile), with
// the RUNNING static ctxloom binary layered in — no go toolchain, no ctxloom
// release needed. Anything else errors so the caller degrades (CLAUDE.md fault
// tolerance): the build is a best-effort convenience, never a blocker.
func (c Container) ensureImage(ctx context.Context) error {
	if c.imagePresent(ctx) {
		return nil
	}
	sources := buildSources(c.profile, "", c.baseContainerfile)
	if len(sources) == 0 {
		return fmt.Errorf("container image %q is not present (no local build recipe for this engine; provide the image, or configure isolation_images)", c.image)
	}
	selfExe, err := resolveSelfExe()
	if err != nil {
		return fmt.Errorf("container image %q is not present and cannot be built from this binary: %w", c.image, err)
	}
	clidiag.Warn("ctxloom", "container image %q not found; building it locally (first run — this may take a few minutes)", c.image)
	var lastErr error
	for _, src := range sources {
		err := buildFromSource(ctx, c.runtime, c.image, src, selfExe, false, nil)
		if err == nil && !c.imagePresent(ctx) {
			err = fmt.Errorf("image %q is still absent after a build via the %s", c.image, src.desc)
		}
		if err == nil {
			return nil
		}
		clidiag.Warn("ctxloom", "agent image build (%s) failed: %v", src.desc, err)
		lastErr = err
	}
	return fmt.Errorf("local build of container image %q failed: %w", c.image, lastErr)
}

// buildFromSource executes one build source: the base stage first when the
// source has one (tagged baseImageTag, handed to the agent stage via
// --build-arg BASE_IMAGE), then the agent/overlay stage with the running
// ctxloom binary in its context. `fresh` pulls + skips cache on stages whose
// FROM is an external image; the agent stage over a just-built local base
// never --pulls (the tag exists only locally) but still skips cache so the
// client install re-runs.
func buildFromSource(ctx context.Context, rt ContainerRuntime, image string, src buildSource, selfExe string, fresh bool, output io.Writer) error {
	var buildArgs []string
	if src.base != nil {
		if err := buildBaseImage(ctx, rt, src.base, fresh, output); err != nil {
			return fmt.Errorf("base image (%s): %w", src.base.desc, err)
		}
		buildArgs = append(buildArgs, "BASE_IMAGE="+baseImageTag)
	}
	return buildImage(ctx, rt, image, src.containerfile, selfExe, buildFlags{
		pull:      fresh && src.base == nil,
		noCache:   fresh,
		buildArgs: buildArgs,
	}, output)
}

// buildBaseImage builds the stage-1 base image (baseImageTag). A user-provided
// Containerfile builds with ITS OWN directory as the context (so its COPYs
// resolve); the embedded default builds from a scratch context.
func buildBaseImage(ctx context.Context, rt ContainerRuntime, base *baseStage, fresh bool, output io.Writer) error {
	flags := buildFlags{pull: fresh, noCache: fresh}
	if base.path != "" {
		abs, err := filepath.Abs(base.path)
		if err != nil {
			return fmt.Errorf("base containerfile: %w", err)
		}
		if _, err := os.Stat(abs); err != nil {
			return fmt.Errorf("base containerfile: %w", err)
		}
		return runImageBuild(ctx, rt, baseImageTag, abs, filepath.Dir(abs), flags, output)
	}

	dir, err := os.MkdirTemp("", "ctxloom-imgbase-")
	if err != nil {
		return fmt.Errorf("base build context: %w", err)
	}
	defer func() { _ = os.RemoveAll(dir) }()
	file := filepath.Join(dir, "Containerfile")
	if err := os.WriteFile(file, base.containerfile, 0o644); err != nil {
		return fmt.Errorf("base build context: %w", err)
	}
	return runImageBuild(ctx, rt, baseImageTag, file, dir, flags, output)
}

// ImageBuildOptions parameterize an explicit agent-image build
// (`ctxloom container build`).
type ImageBuildOptions struct {
	// BaseImage overlays ctxloom onto this user-chosen base — which must
	// already ship the client CLI — instead of the profile's build sources.
	BaseImage string
	// BaseContainerfile builds the shared base stage from this user-provided
	// Containerfile instead of the embedded default; the engine's agent stage
	// layers on top. Mutually exclusive with BaseImage.
	BaseContainerfile string
	// Runtime prefers a container runtime by name ("docker" | "podman");
	// empty auto-detects.
	Runtime string
	// KeepCache reuses cached layers. Default false: the build runs with
	// --pull --no-cache so the base image is refreshed and the client install
	// re-runs — the MOST RECENT client, never pinned.
	KeepCache bool
	// Output streams build output when set (the CLI); nil captures output and
	// surfaces only a failure tail.
	Output io.Writer
}

// BuildAgentImage builds the agent image for the REGISTERED backend name from
// the best available source — the caller's base-image overlay, the agent stage
// on a user base Containerfile, the client's official image, or the embedded
// install recipe over the default base — layering the RUNNING ctxloom binary in
// (any dev build works; no ctxloom release needed). Each source validates the
// client inside the build (`<client> --version`), so a broken image never
// ships. Returns the image tag it built.
func BuildAgentImage(ctx context.Context, backend string, opts ImageBuildOptions) (string, error) {
	if opts.BaseImage != "" && opts.BaseContainerfile != "" {
		return "", fmt.Errorf("base-image and base-containerfile are mutually exclusive (an image asserts the client is preinstalled; a containerfile gets the client layered on)")
	}
	p := containerProfileFor(backend)
	sources := buildSources(p, opts.BaseImage, opts.BaseContainerfile)
	if len(sources) == 0 {
		return "", fmt.Errorf("backend %q has no local build recipe (no official client image and no embedded Containerfile); pass --base-image with the client preinstalled", backend)
	}
	rt := SelectRuntime(opts.Runtime)
	if _, isHost := rt.(Host); isHost {
		return "", fmt.Errorf("no container runtime (docker/podman) is available to build with")
	}
	selfExe, err := resolveSelfExe()
	if err != nil {
		return "", err
	}
	var lastErr error
	for _, src := range sources {
		if opts.Output != nil {
			fmt.Fprintf(opts.Output, "ctxloom: building %s via the %s (%s)\n", p.image, src.desc, rt.Name())
		}
		if err := buildFromSource(ctx, rt, p.image, src, selfExe, !opts.KeepCache, opts.Output); err != nil {
			clidiag.Warn("ctxloom", "agent image build (%s) failed: %v", src.desc, err)
			lastErr = err
			continue
		}
		return p.image, nil
	}
	return "", lastErr
}

// selfLinuxExe returns the running executable's path when it can serve as the
// in-container ctxloom binary: a linux host (the container shares the host
// kernel/arch) and an ELF. Dynamic linkage is deliberately ALLOWED — the daily
// `just build` ctxloom is CGO/glibc-linked and runs fine on the glibc image
// bases; whether THIS binary actually runs in THIS image is proven by the
// in-image `ctxloom version` build gate (every build source ends with one), so
// an ABI mismatch fails the build and degrades instead of shipping a broken
// image. Non-linux / non-ELF errors so the caller degrades up front.
func selfLinuxExe() (string, error) {
	if runtime.GOOS != "linux" {
		return "", fmt.Errorf("host is %s and the agent image needs a linux ctxloom (build it ahead of time via the container-build just recipes)", runtime.GOOS)
	}
	exe, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("resolve running executable: %w", err)
	}
	if exe, err = filepath.EvalSymlinks(exe); err != nil {
		return "", fmt.Errorf("resolve running executable: %w", err)
	}
	f, err := elf.Open(exe)
	if err != nil {
		return "", fmt.Errorf("running executable is not an ELF binary: %w", err)
	}
	_ = f.Close()
	return exe, nil
}

// buildFlags are the per-stage `<runtime> build` knobs: --pull (refresh an
// EXTERNAL base — never set when the FROM is the locally-built base tag, which
// no registry has), --no-cache (re-run installs → most recent client), and
// --build-arg values (BASE_IMAGE for agent stages).
type buildFlags struct {
	pull      bool
	noCache   bool
	buildArgs []string
}

// buildImage runs one agent/overlay stage over a temp context holding the
// Containerfile plus the running static ctxloom binary.
func buildImage(ctx context.Context, rt ContainerRuntime, image string, containerfile []byte, selfExe string, flags buildFlags, output io.Writer) error {
	dir, err := os.MkdirTemp("", "ctxloom-imgbuild-")
	if err != nil {
		return fmt.Errorf("image build context: %w", err)
	}
	defer func() { _ = os.RemoveAll(dir) }()
	file := filepath.Join(dir, "Containerfile")
	if err := os.WriteFile(file, containerfile, 0o644); err != nil {
		return fmt.Errorf("image build context: %w", err)
	}
	if err := copyExecutable(selfExe, filepath.Join(dir, "ctxloom")); err != nil {
		return fmt.Errorf("image build context: %w", err)
	}
	return runImageBuild(ctx, rt, image, file, dir, flags, output)
}

// runImageBuild executes `<runtime> build -t <image> -f <file> <contextDir>`.
// output streams the build live when set; otherwise output is captured and
// surfaced (tail only) on failure. Capped at imageBuildTimeout.
func runImageBuild(ctx context.Context, rt ContainerRuntime, image, file, contextDir string, flags buildFlags, output io.Writer) error {
	args := []string{"build", "-t", image}
	if flags.pull {
		args = append(args, "--pull")
	}
	if flags.noCache {
		args = append(args, "--no-cache")
	}
	for _, ba := range flags.buildArgs {
		args = append(args, "--build-arg", ba)
	}
	args = append(args, "-f", file, contextDir)

	bctx, cancel := context.WithTimeout(ctx, imageBuildTimeout)
	defer cancel()
	cmd := exec.CommandContext(bctx, rt.Binary(), args...)
	if output != nil {
		cmd.Stdout, cmd.Stderr = output, output
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("%s build: %w", rt.Name(), err)
		}
		return nil
	}
	var out bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &out
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%s build: %w\n%s", rt.Name(), err, tailLines(out.String(), 20))
	}
	return nil
}

// copyExecutable copies src to dst with the executable bit set (the build
// context is a fresh temp dir, so a plain copy suffices — no atomicity needed).
func copyExecutable(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o755)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		_ = out.Close()
		return err
	}
	return out.Close()
}

// tailLines returns the last n lines of s — enough build-failure context to
// diagnose without dumping a whole multi-minute build log into a warning.
func tailLines(s string, n int) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, "\n")
}
