package isolation

import (
	"bytes"
	"context"
	"debug/elf"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/ctxloom/ctxloom/internal/shared/clidiag"
)

// imageBuildTimeout caps one on-the-fly agent-image build. The production
// builds are network-bound (npm / the kiro installer / an official-image pull)
// so the first build takes minutes; a hung build must still degrade rather than
// block the LLM forever.
const imageBuildTimeout = 10 * time.Minute

// resolveSelfExe is the seam over the running-binary check (overridable in
// tests, like hostHomeDir): it yields the path buildImage bakes into the image.
var resolveSelfExe = selfLinuxExe

// buildSource is one way to produce the agent image locally: a Containerfile
// (a rendered overlay onto a client-shipped base, or the embedded install
// recipe) plus a description for degrade diagnostics.
type buildSource struct {
	desc          string
	containerfile []byte
}

// buildSources orders a profile's local-build sources. An explicit base
// override wins outright (the caller asserts the client lives there); else the
// client's OFFICIAL image is overlaid first (a fresh --pull build rides the
// vendor's most recent client), falling back to the embedded install
// Containerfile (which fetches the most recent client CLI — never pinned).
// Empty means the image cannot be built locally.
func buildSources(p containerProfile, baseOverride string) []buildSource {
	if baseOverride != "" {
		return []buildSource{{
			desc:          "overlay on base image " + baseOverride,
			containerfile: overlayContainerfile(baseOverride, p.validate),
		}}
	}
	var out []buildSource
	if p.officialImage != "" {
		out = append(out, buildSource{
			desc:          "overlay on the official client image " + p.officialImage,
			containerfile: overlayContainerfile(p.officialImage, p.validate),
		})
	}
	if len(p.containerfile) > 0 {
		out = append(out, buildSource{desc: "embedded install Containerfile", containerfile: p.containerfile})
	}
	return out
}

// overlayContainerfile renders the generated OVERLAY Containerfile: the running
// ctxloom binary layered onto a base image that already ships the client CLI
// (the vendor's official image, or a user-provided base). ENTRYPOINT is reset
// because the isolation runtime supplies the full in-container argv; the
// validate command gates the build so a base without a runnable client never
// ships as an agent image.
func overlayContainerfile(baseImage, validate string) []byte {
	var b strings.Builder
	b.WriteString("# Generated by ctxloom: the running ctxloom binary overlaid onto a base\n")
	b.WriteString("# image that already ships the client CLI.\n")
	b.WriteString("FROM " + baseImage + "\n")
	b.WriteString("ENTRYPOINT []\n")
	if validate != "" {
		b.WriteString("RUN " + validate + "\n")
	}
	b.WriteString("COPY ctxloom /usr/local/bin/ctxloom\n")
	b.WriteString("RUN /usr/local/bin/ctxloom version\n")
	return []byte(b.String())
}

// ensureImage is the image half of the container degrade gate, used by run and
// the map/weave fan-out alike. Present → run. Absent and locally buildable →
// build (official-image overlay first, then the install Containerfile), with
// the RUNNING static ctxloom binary layered in — no go toolchain, no ctxloom
// release needed. Anything else errors so the caller degrades (CLAUDE.md fault
// tolerance): the build is a best-effort convenience, never a blocker.
func (c Container) ensureImage(ctx context.Context) error {
	if c.imagePresent(ctx) {
		return nil
	}
	sources := buildSources(c.profile, "")
	if len(sources) == 0 {
		return fmt.Errorf("container image %q is not present (no local build recipe for this engine; provide the image, or configure isolation_images)", c.image)
	}
	selfExe, err := resolveSelfExe()
	if err != nil {
		return fmt.Errorf("container image %q is not present and cannot be built from this binary: %w", c.image, err)
	}
	clidiag.Warn("ctxloom", "container image %q not found; building it locally (first run — this may take a few minutes)", c.image)
	var lastErr error
	for _, src := range sources {
		err := buildImage(ctx, c.runtime, c.image, src.containerfile, selfExe, false, nil)
		if err == nil && !c.imagePresent(ctx) {
			err = fmt.Errorf("image %q is still absent after a build via the %s", c.image, src.desc)
		}
		if err == nil {
			return nil
		}
		clidiag.Warn("ctxloom", "agent image build (%s) failed: %v", src.desc, err)
		lastErr = err
	}
	return fmt.Errorf("local build of container image %q failed: %w", c.image, lastErr)
}

// ImageBuildOptions parameterize an explicit agent-image build
// (`ctxloom container build`).
type ImageBuildOptions struct {
	// BaseImage overlays ctxloom onto this user-chosen base — which must
	// already ship the client CLI — instead of the profile's build sources.
	BaseImage string
	// Runtime prefers a container runtime by name ("docker" | "podman");
	// empty auto-detects.
	Runtime string
	// KeepCache reuses cached layers. Default false: the build runs with
	// --pull --no-cache so the base image is refreshed and the client install
	// re-runs — the MOST RECENT client, never pinned.
	KeepCache bool
	// Output streams build output when set (the CLI); nil captures output and
	// surfaces only a failure tail.
	Output io.Writer
}

// BuildAgentImage builds the agent image for the REGISTERED backend name from
// the best available source — the caller's base-image overlay, the client's
// official image, or the embedded install Containerfile — layering the RUNNING
// ctxloom binary in (any dev build works; no ctxloom release needed). Each
// source validates the client inside the build (`<client> --version`), so a
// broken image never ships. Returns the image tag it built.
func BuildAgentImage(ctx context.Context, backend string, opts ImageBuildOptions) (string, error) {
	p := containerProfileFor(backend)
	sources := buildSources(p, opts.BaseImage)
	if len(sources) == 0 {
		return "", fmt.Errorf("backend %q has no local build recipe (no official client image and no embedded Containerfile); pass --base-image with the client preinstalled", backend)
	}
	rt := SelectRuntime(opts.Runtime)
	if _, isHost := rt.(Host); isHost {
		return "", fmt.Errorf("no container runtime (docker/podman) is available to build with")
	}
	selfExe, err := resolveSelfExe()
	if err != nil {
		return "", err
	}
	var lastErr error
	for _, src := range sources {
		if opts.Output != nil {
			fmt.Fprintf(opts.Output, "ctxloom: building %s via the %s (%s)\n", p.image, src.desc, rt.Name())
		}
		if err := buildImage(ctx, rt, p.image, src.containerfile, selfExe, !opts.KeepCache, opts.Output); err != nil {
			clidiag.Warn("ctxloom", "agent image build (%s) failed: %v", src.desc, err)
			lastErr = err
			continue
		}
		return p.image, nil
	}
	return "", lastErr
}

// selfLinuxExe returns the running executable's path when it can serve as the
// in-container ctxloom binary: a linux host (the container shares the host
// kernel/arch) and an ELF. Dynamic linkage is deliberately ALLOWED — the daily
// `just build` ctxloom is CGO/glibc-linked and runs fine on the glibc image
// bases; whether THIS binary actually runs in THIS image is proven by the
// in-image `ctxloom version` build gate (every build source ends with one), so
// an ABI mismatch fails the build and degrades instead of shipping a broken
// image. Non-linux / non-ELF errors so the caller degrades up front.
func selfLinuxExe() (string, error) {
	if runtime.GOOS != "linux" {
		return "", fmt.Errorf("host is %s and the agent image needs a linux ctxloom (build it ahead of time via the container-build just recipes)", runtime.GOOS)
	}
	exe, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("resolve running executable: %w", err)
	}
	if exe, err = filepath.EvalSymlinks(exe); err != nil {
		return "", fmt.Errorf("resolve running executable: %w", err)
	}
	f, err := elf.Open(exe)
	if err != nil {
		return "", fmt.Errorf("running executable is not an ELF binary: %w", err)
	}
	_ = f.Close()
	return exe, nil
}

// buildImage runs `<runtime> build -t <image>` over a temp context holding the
// Containerfile plus the running static ctxloom binary. fresh adds --pull
// --no-cache (refresh the base, re-run the client install → most recent
// client). output streams the build live when set; otherwise output is
// captured and surfaced (tail only) on failure. Capped at imageBuildTimeout.
func buildImage(ctx context.Context, rt ContainerRuntime, image string, containerfile []byte, selfExe string, fresh bool, output io.Writer) error {
	dir, err := os.MkdirTemp("", "ctxloom-imgbuild-")
	if err != nil {
		return fmt.Errorf("image build context: %w", err)
	}
	defer func() { _ = os.RemoveAll(dir) }()
	if err := os.WriteFile(filepath.Join(dir, "Containerfile"), containerfile, 0o644); err != nil {
		return fmt.Errorf("image build context: %w", err)
	}
	if err := copyExecutable(selfExe, filepath.Join(dir, "ctxloom")); err != nil {
		return fmt.Errorf("image build context: %w", err)
	}

	args := []string{"build", "-t", image}
	if fresh {
		args = append(args, "--pull", "--no-cache")
	}
	args = append(args, "-f", filepath.Join(dir, "Containerfile"), dir)

	bctx, cancel := context.WithTimeout(ctx, imageBuildTimeout)
	defer cancel()
	cmd := exec.CommandContext(bctx, rt.Binary(), args...)
	if output != nil {
		cmd.Stdout, cmd.Stderr = output, output
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("%s build: %w", rt.Name(), err)
		}
		return nil
	}
	var out bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &out
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%s build: %w\n%s", rt.Name(), err, tailLines(out.String(), 20))
	}
	return nil
}

// copyExecutable copies src to dst with the executable bit set (the build
// context is a fresh temp dir, so a plain copy suffices — no atomicity needed).
func copyExecutable(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o755)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		_ = out.Close()
		return err
	}
	return out.Close()
}

// tailLines returns the last n lines of s — enough build-failure context to
// diagnose without dumping a whole multi-minute build log into a warning.
func tailLines(s string, n int) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, "\n")
}
