// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: proto/fragments.proto

package fragmentspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FragmentService_CreateFragment_FullMethodName    = "/fragments.v1.FragmentService/CreateFragment"
	FragmentService_GetFragment_FullMethodName       = "/fragments.v1.FragmentService/GetFragment"
	FragmentService_GetFragmentByName_FullMethodName = "/fragments.v1.FragmentService/GetFragmentByName"
	FragmentService_UpdateFragment_FullMethodName    = "/fragments.v1.FragmentService/UpdateFragment"
	FragmentService_DeleteFragment_FullMethodName    = "/fragments.v1.FragmentService/DeleteFragment"
	FragmentService_ListFragments_FullMethodName     = "/fragments.v1.FragmentService/ListFragments"
	FragmentService_SearchFragments_FullMethodName   = "/fragments.v1.FragmentService/SearchFragments"
	FragmentService_DownloadFragment_FullMethodName  = "/fragments.v1.FragmentService/DownloadFragment"
	FragmentService_LikeFragment_FullMethodName      = "/fragments.v1.FragmentService/LikeFragment"
	FragmentService_DislikeFragment_FullMethodName   = "/fragments.v1.FragmentService/DislikeFragment"
	FragmentService_ListDislikes_FullMethodName      = "/fragments.v1.FragmentService/ListDislikes"
	FragmentService_CreatePersona_FullMethodName     = "/fragments.v1.FragmentService/CreatePersona"
	FragmentService_GetPersona_FullMethodName        = "/fragments.v1.FragmentService/GetPersona"
	FragmentService_GetPersonaByName_FullMethodName  = "/fragments.v1.FragmentService/GetPersonaByName"
	FragmentService_UpdatePersona_FullMethodName     = "/fragments.v1.FragmentService/UpdatePersona"
	FragmentService_DeletePersona_FullMethodName     = "/fragments.v1.FragmentService/DeletePersona"
	FragmentService_ListPersonas_FullMethodName      = "/fragments.v1.FragmentService/ListPersonas"
	FragmentService_DownloadPersona_FullMethodName   = "/fragments.v1.FragmentService/DownloadPersona"
	FragmentService_LikePersona_FullMethodName       = "/fragments.v1.FragmentService/LikePersona"
	FragmentService_DislikePersona_FullMethodName    = "/fragments.v1.FragmentService/DislikePersona"
)

// FragmentServiceClient is the client API for FragmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FragmentService provides CRUD operations for context fragments.
type FragmentServiceClient interface {
	// CreateFragment creates a new fragment.
	CreateFragment(ctx context.Context, in *CreateFragmentRequest, opts ...grpc.CallOption) (*Fragment, error)
	// GetFragment retrieves a fragment by ID.
	GetFragment(ctx context.Context, in *GetFragmentRequest, opts ...grpc.CallOption) (*Fragment, error)
	// GetFragmentByName retrieves a fragment by author, name, and optional version.
	GetFragmentByName(ctx context.Context, in *GetFragmentByNameRequest, opts ...grpc.CallOption) (*Fragment, error)
	// UpdateFragment updates an existing fragment.
	UpdateFragment(ctx context.Context, in *UpdateFragmentRequest, opts ...grpc.CallOption) (*Fragment, error)
	// DeleteFragment deletes a fragment.
	DeleteFragment(ctx context.Context, in *DeleteFragmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListFragments lists fragments with optional filtering.
	ListFragments(ctx context.Context, in *ListFragmentsRequest, opts ...grpc.CallOption) (*ListFragmentsResponse, error)
	// SearchFragments searches fragments by content.
	SearchFragments(ctx context.Context, in *SearchFragmentsRequest, opts ...grpc.CallOption) (*SearchFragmentsResponse, error)
	// DownloadFragment increments download count and returns the fragment.
	DownloadFragment(ctx context.Context, in *DownloadFragmentRequest, opts ...grpc.CallOption) (*Fragment, error)
	// LikeFragment adds a like to a fragment.
	LikeFragment(ctx context.Context, in *LikeFragmentRequest, opts ...grpc.CallOption) (*Fragment, error)
	// DislikeFragment adds a dislike to a fragment (reason required).
	DislikeFragment(ctx context.Context, in *DislikeFragmentRequest, opts ...grpc.CallOption) (*Fragment, error)
	// ListDislikes returns dislikes with reasons for a fragment.
	ListDislikes(ctx context.Context, in *ListDislikesRequest, opts ...grpc.CallOption) (*ListDislikesResponse, error)
	// CreatePersona creates a new persona.
	CreatePersona(ctx context.Context, in *CreatePersonaRequest, opts ...grpc.CallOption) (*Persona, error)
	// GetPersona retrieves a persona by ID.
	GetPersona(ctx context.Context, in *GetPersonaRequest, opts ...grpc.CallOption) (*Persona, error)
	// GetPersonaByName retrieves a persona by name, author, and optional version.
	GetPersonaByName(ctx context.Context, in *GetPersonaByNameRequest, opts ...grpc.CallOption) (*Persona, error)
	// UpdatePersona updates an existing persona.
	UpdatePersona(ctx context.Context, in *UpdatePersonaRequest, opts ...grpc.CallOption) (*Persona, error)
	// DeletePersona deletes a persona.
	DeletePersona(ctx context.Context, in *DeletePersonaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListPersonas lists personas with optional filtering.
	ListPersonas(ctx context.Context, in *ListPersonasRequest, opts ...grpc.CallOption) (*ListPersonasResponse, error)
	// DownloadPersona increments download count and returns persona with resolved fragments.
	DownloadPersona(ctx context.Context, in *DownloadPersonaRequest, opts ...grpc.CallOption) (*DownloadPersonaResponse, error)
	// LikePersona adds a like to a persona.
	LikePersona(ctx context.Context, in *LikePersonaRequest, opts ...grpc.CallOption) (*Persona, error)
	// DislikePersona adds a dislike to a persona (reason required).
	DislikePersona(ctx context.Context, in *DislikePersonaRequest, opts ...grpc.CallOption) (*Persona, error)
}

type fragmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFragmentServiceClient(cc grpc.ClientConnInterface) FragmentServiceClient {
	return &fragmentServiceClient{cc}
}

func (c *fragmentServiceClient) CreateFragment(ctx context.Context, in *CreateFragmentRequest, opts ...grpc.CallOption) (*Fragment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fragment)
	err := c.cc.Invoke(ctx, FragmentService_CreateFragment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) GetFragment(ctx context.Context, in *GetFragmentRequest, opts ...grpc.CallOption) (*Fragment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fragment)
	err := c.cc.Invoke(ctx, FragmentService_GetFragment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) GetFragmentByName(ctx context.Context, in *GetFragmentByNameRequest, opts ...grpc.CallOption) (*Fragment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fragment)
	err := c.cc.Invoke(ctx, FragmentService_GetFragmentByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) UpdateFragment(ctx context.Context, in *UpdateFragmentRequest, opts ...grpc.CallOption) (*Fragment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fragment)
	err := c.cc.Invoke(ctx, FragmentService_UpdateFragment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) DeleteFragment(ctx context.Context, in *DeleteFragmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FragmentService_DeleteFragment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) ListFragments(ctx context.Context, in *ListFragmentsRequest, opts ...grpc.CallOption) (*ListFragmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFragmentsResponse)
	err := c.cc.Invoke(ctx, FragmentService_ListFragments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) SearchFragments(ctx context.Context, in *SearchFragmentsRequest, opts ...grpc.CallOption) (*SearchFragmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFragmentsResponse)
	err := c.cc.Invoke(ctx, FragmentService_SearchFragments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) DownloadFragment(ctx context.Context, in *DownloadFragmentRequest, opts ...grpc.CallOption) (*Fragment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fragment)
	err := c.cc.Invoke(ctx, FragmentService_DownloadFragment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) LikeFragment(ctx context.Context, in *LikeFragmentRequest, opts ...grpc.CallOption) (*Fragment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fragment)
	err := c.cc.Invoke(ctx, FragmentService_LikeFragment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) DislikeFragment(ctx context.Context, in *DislikeFragmentRequest, opts ...grpc.CallOption) (*Fragment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fragment)
	err := c.cc.Invoke(ctx, FragmentService_DislikeFragment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) ListDislikes(ctx context.Context, in *ListDislikesRequest, opts ...grpc.CallOption) (*ListDislikesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDislikesResponse)
	err := c.cc.Invoke(ctx, FragmentService_ListDislikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) CreatePersona(ctx context.Context, in *CreatePersonaRequest, opts ...grpc.CallOption) (*Persona, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Persona)
	err := c.cc.Invoke(ctx, FragmentService_CreatePersona_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) GetPersona(ctx context.Context, in *GetPersonaRequest, opts ...grpc.CallOption) (*Persona, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Persona)
	err := c.cc.Invoke(ctx, FragmentService_GetPersona_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) GetPersonaByName(ctx context.Context, in *GetPersonaByNameRequest, opts ...grpc.CallOption) (*Persona, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Persona)
	err := c.cc.Invoke(ctx, FragmentService_GetPersonaByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) UpdatePersona(ctx context.Context, in *UpdatePersonaRequest, opts ...grpc.CallOption) (*Persona, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Persona)
	err := c.cc.Invoke(ctx, FragmentService_UpdatePersona_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) DeletePersona(ctx context.Context, in *DeletePersonaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FragmentService_DeletePersona_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) ListPersonas(ctx context.Context, in *ListPersonasRequest, opts ...grpc.CallOption) (*ListPersonasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPersonasResponse)
	err := c.cc.Invoke(ctx, FragmentService_ListPersonas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) DownloadPersona(ctx context.Context, in *DownloadPersonaRequest, opts ...grpc.CallOption) (*DownloadPersonaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadPersonaResponse)
	err := c.cc.Invoke(ctx, FragmentService_DownloadPersona_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) LikePersona(ctx context.Context, in *LikePersonaRequest, opts ...grpc.CallOption) (*Persona, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Persona)
	err := c.cc.Invoke(ctx, FragmentService_LikePersona_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fragmentServiceClient) DislikePersona(ctx context.Context, in *DislikePersonaRequest, opts ...grpc.CallOption) (*Persona, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Persona)
	err := c.cc.Invoke(ctx, FragmentService_DislikePersona_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FragmentServiceServer is the server API for FragmentService service.
// All implementations must embed UnimplementedFragmentServiceServer
// for forward compatibility.
//
// FragmentService provides CRUD operations for context fragments.
type FragmentServiceServer interface {
	// CreateFragment creates a new fragment.
	CreateFragment(context.Context, *CreateFragmentRequest) (*Fragment, error)
	// GetFragment retrieves a fragment by ID.
	GetFragment(context.Context, *GetFragmentRequest) (*Fragment, error)
	// GetFragmentByName retrieves a fragment by author, name, and optional version.
	GetFragmentByName(context.Context, *GetFragmentByNameRequest) (*Fragment, error)
	// UpdateFragment updates an existing fragment.
	UpdateFragment(context.Context, *UpdateFragmentRequest) (*Fragment, error)
	// DeleteFragment deletes a fragment.
	DeleteFragment(context.Context, *DeleteFragmentRequest) (*emptypb.Empty, error)
	// ListFragments lists fragments with optional filtering.
	ListFragments(context.Context, *ListFragmentsRequest) (*ListFragmentsResponse, error)
	// SearchFragments searches fragments by content.
	SearchFragments(context.Context, *SearchFragmentsRequest) (*SearchFragmentsResponse, error)
	// DownloadFragment increments download count and returns the fragment.
	DownloadFragment(context.Context, *DownloadFragmentRequest) (*Fragment, error)
	// LikeFragment adds a like to a fragment.
	LikeFragment(context.Context, *LikeFragmentRequest) (*Fragment, error)
	// DislikeFragment adds a dislike to a fragment (reason required).
	DislikeFragment(context.Context, *DislikeFragmentRequest) (*Fragment, error)
	// ListDislikes returns dislikes with reasons for a fragment.
	ListDislikes(context.Context, *ListDislikesRequest) (*ListDislikesResponse, error)
	// CreatePersona creates a new persona.
	CreatePersona(context.Context, *CreatePersonaRequest) (*Persona, error)
	// GetPersona retrieves a persona by ID.
	GetPersona(context.Context, *GetPersonaRequest) (*Persona, error)
	// GetPersonaByName retrieves a persona by name, author, and optional version.
	GetPersonaByName(context.Context, *GetPersonaByNameRequest) (*Persona, error)
	// UpdatePersona updates an existing persona.
	UpdatePersona(context.Context, *UpdatePersonaRequest) (*Persona, error)
	// DeletePersona deletes a persona.
	DeletePersona(context.Context, *DeletePersonaRequest) (*emptypb.Empty, error)
	// ListPersonas lists personas with optional filtering.
	ListPersonas(context.Context, *ListPersonasRequest) (*ListPersonasResponse, error)
	// DownloadPersona increments download count and returns persona with resolved fragments.
	DownloadPersona(context.Context, *DownloadPersonaRequest) (*DownloadPersonaResponse, error)
	// LikePersona adds a like to a persona.
	LikePersona(context.Context, *LikePersonaRequest) (*Persona, error)
	// DislikePersona adds a dislike to a persona (reason required).
	DislikePersona(context.Context, *DislikePersonaRequest) (*Persona, error)
	mustEmbedUnimplementedFragmentServiceServer()
}

// UnimplementedFragmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFragmentServiceServer struct{}

func (UnimplementedFragmentServiceServer) CreateFragment(context.Context, *CreateFragmentRequest) (*Fragment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFragment not implemented")
}
func (UnimplementedFragmentServiceServer) GetFragment(context.Context, *GetFragmentRequest) (*Fragment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFragment not implemented")
}
func (UnimplementedFragmentServiceServer) GetFragmentByName(context.Context, *GetFragmentByNameRequest) (*Fragment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFragmentByName not implemented")
}
func (UnimplementedFragmentServiceServer) UpdateFragment(context.Context, *UpdateFragmentRequest) (*Fragment, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFragment not implemented")
}
func (UnimplementedFragmentServiceServer) DeleteFragment(context.Context, *DeleteFragmentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFragment not implemented")
}
func (UnimplementedFragmentServiceServer) ListFragments(context.Context, *ListFragmentsRequest) (*ListFragmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFragments not implemented")
}
func (UnimplementedFragmentServiceServer) SearchFragments(context.Context, *SearchFragmentsRequest) (*SearchFragmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchFragments not implemented")
}
func (UnimplementedFragmentServiceServer) DownloadFragment(context.Context, *DownloadFragmentRequest) (*Fragment, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadFragment not implemented")
}
func (UnimplementedFragmentServiceServer) LikeFragment(context.Context, *LikeFragmentRequest) (*Fragment, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeFragment not implemented")
}
func (UnimplementedFragmentServiceServer) DislikeFragment(context.Context, *DislikeFragmentRequest) (*Fragment, error) {
	return nil, status.Error(codes.Unimplemented, "method DislikeFragment not implemented")
}
func (UnimplementedFragmentServiceServer) ListDislikes(context.Context, *ListDislikesRequest) (*ListDislikesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDislikes not implemented")
}
func (UnimplementedFragmentServiceServer) CreatePersona(context.Context, *CreatePersonaRequest) (*Persona, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePersona not implemented")
}
func (UnimplementedFragmentServiceServer) GetPersona(context.Context, *GetPersonaRequest) (*Persona, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPersona not implemented")
}
func (UnimplementedFragmentServiceServer) GetPersonaByName(context.Context, *GetPersonaByNameRequest) (*Persona, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPersonaByName not implemented")
}
func (UnimplementedFragmentServiceServer) UpdatePersona(context.Context, *UpdatePersonaRequest) (*Persona, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePersona not implemented")
}
func (UnimplementedFragmentServiceServer) DeletePersona(context.Context, *DeletePersonaRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePersona not implemented")
}
func (UnimplementedFragmentServiceServer) ListPersonas(context.Context, *ListPersonasRequest) (*ListPersonasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPersonas not implemented")
}
func (UnimplementedFragmentServiceServer) DownloadPersona(context.Context, *DownloadPersonaRequest) (*DownloadPersonaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadPersona not implemented")
}
func (UnimplementedFragmentServiceServer) LikePersona(context.Context, *LikePersonaRequest) (*Persona, error) {
	return nil, status.Error(codes.Unimplemented, "method LikePersona not implemented")
}
func (UnimplementedFragmentServiceServer) DislikePersona(context.Context, *DislikePersonaRequest) (*Persona, error) {
	return nil, status.Error(codes.Unimplemented, "method DislikePersona not implemented")
}
func (UnimplementedFragmentServiceServer) mustEmbedUnimplementedFragmentServiceServer() {}
func (UnimplementedFragmentServiceServer) testEmbeddedByValue()                         {}

// UnsafeFragmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FragmentServiceServer will
// result in compilation errors.
type UnsafeFragmentServiceServer interface {
	mustEmbedUnimplementedFragmentServiceServer()
}

func RegisterFragmentServiceServer(s grpc.ServiceRegistrar, srv FragmentServiceServer) {
	// If the following call panics, it indicates UnimplementedFragmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FragmentService_ServiceDesc, srv)
}

func _FragmentService_CreateFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFragmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).CreateFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_CreateFragment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).CreateFragment(ctx, req.(*CreateFragmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_GetFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFragmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).GetFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_GetFragment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).GetFragment(ctx, req.(*GetFragmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_GetFragmentByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFragmentByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).GetFragmentByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_GetFragmentByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).GetFragmentByName(ctx, req.(*GetFragmentByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_UpdateFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFragmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).UpdateFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_UpdateFragment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).UpdateFragment(ctx, req.(*UpdateFragmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_DeleteFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFragmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).DeleteFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_DeleteFragment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).DeleteFragment(ctx, req.(*DeleteFragmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_ListFragments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFragmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).ListFragments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_ListFragments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).ListFragments(ctx, req.(*ListFragmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_SearchFragments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFragmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).SearchFragments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_SearchFragments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).SearchFragments(ctx, req.(*SearchFragmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_DownloadFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFragmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).DownloadFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_DownloadFragment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).DownloadFragment(ctx, req.(*DownloadFragmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_LikeFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeFragmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).LikeFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_LikeFragment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).LikeFragment(ctx, req.(*LikeFragmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_DislikeFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DislikeFragmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).DislikeFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_DislikeFragment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).DislikeFragment(ctx, req.(*DislikeFragmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_ListDislikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDislikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).ListDislikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_ListDislikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).ListDislikes(ctx, req.(*ListDislikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_CreatePersona_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersonaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).CreatePersona(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_CreatePersona_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).CreatePersona(ctx, req.(*CreatePersonaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_GetPersona_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).GetPersona(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_GetPersona_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).GetPersona(ctx, req.(*GetPersonaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_GetPersonaByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonaByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).GetPersonaByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_GetPersonaByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).GetPersonaByName(ctx, req.(*GetPersonaByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_UpdatePersona_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePersonaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).UpdatePersona(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_UpdatePersona_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).UpdatePersona(ctx, req.(*UpdatePersonaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_DeletePersona_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePersonaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).DeletePersona(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_DeletePersona_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).DeletePersona(ctx, req.(*DeletePersonaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_ListPersonas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPersonasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).ListPersonas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_ListPersonas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).ListPersonas(ctx, req.(*ListPersonasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_DownloadPersona_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadPersonaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).DownloadPersona(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_DownloadPersona_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).DownloadPersona(ctx, req.(*DownloadPersonaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_LikePersona_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikePersonaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).LikePersona(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_LikePersona_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).LikePersona(ctx, req.(*LikePersonaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FragmentService_DislikePersona_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DislikePersonaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FragmentServiceServer).DislikePersona(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FragmentService_DislikePersona_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FragmentServiceServer).DislikePersona(ctx, req.(*DislikePersonaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FragmentService_ServiceDesc is the grpc.ServiceDesc for FragmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FragmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fragments.v1.FragmentService",
	HandlerType: (*FragmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFragment",
			Handler:    _FragmentService_CreateFragment_Handler,
		},
		{
			MethodName: "GetFragment",
			Handler:    _FragmentService_GetFragment_Handler,
		},
		{
			MethodName: "GetFragmentByName",
			Handler:    _FragmentService_GetFragmentByName_Handler,
		},
		{
			MethodName: "UpdateFragment",
			Handler:    _FragmentService_UpdateFragment_Handler,
		},
		{
			MethodName: "DeleteFragment",
			Handler:    _FragmentService_DeleteFragment_Handler,
		},
		{
			MethodName: "ListFragments",
			Handler:    _FragmentService_ListFragments_Handler,
		},
		{
			MethodName: "SearchFragments",
			Handler:    _FragmentService_SearchFragments_Handler,
		},
		{
			MethodName: "DownloadFragment",
			Handler:    _FragmentService_DownloadFragment_Handler,
		},
		{
			MethodName: "LikeFragment",
			Handler:    _FragmentService_LikeFragment_Handler,
		},
		{
			MethodName: "DislikeFragment",
			Handler:    _FragmentService_DislikeFragment_Handler,
		},
		{
			MethodName: "ListDislikes",
			Handler:    _FragmentService_ListDislikes_Handler,
		},
		{
			MethodName: "CreatePersona",
			Handler:    _FragmentService_CreatePersona_Handler,
		},
		{
			MethodName: "GetPersona",
			Handler:    _FragmentService_GetPersona_Handler,
		},
		{
			MethodName: "GetPersonaByName",
			Handler:    _FragmentService_GetPersonaByName_Handler,
		},
		{
			MethodName: "UpdatePersona",
			Handler:    _FragmentService_UpdatePersona_Handler,
		},
		{
			MethodName: "DeletePersona",
			Handler:    _FragmentService_DeletePersona_Handler,
		},
		{
			MethodName: "ListPersonas",
			Handler:    _FragmentService_ListPersonas_Handler,
		},
		{
			MethodName: "DownloadPersona",
			Handler:    _FragmentService_DownloadPersona_Handler,
		},
		{
			MethodName: "LikePersona",
			Handler:    _FragmentService_LikePersona_Handler,
		},
		{
			MethodName: "DislikePersona",
			Handler:    _FragmentService_DislikePersona_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fragments.proto",
}
