// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/fragments.proto

package fragmentspb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SortOrder specifies how to sort results.
type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_POPULARITY  SortOrder = 1 // downloads + (likes - dislikes)
	SortOrder_SORT_ORDER_DOWNLOADS   SortOrder = 2 // by download count
	SortOrder_SORT_ORDER_RECENT      SortOrder = 3 // by updated_at
	SortOrder_SORT_ORDER_NAME        SortOrder = 4 // alphabetical by name
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_POPULARITY",
		2: "SORT_ORDER_DOWNLOADS",
		3: "SORT_ORDER_RECENT",
		4: "SORT_ORDER_NAME",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_POPULARITY":  1,
		"SORT_ORDER_DOWNLOADS":   2,
		"SORT_ORDER_RECENT":      3,
		"SORT_ORDER_NAME":        4,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fragments_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_proto_fragments_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{0}
}

// Fragment represents a context fragment document.
type Fragment struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version   string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Author    string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Tags      []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Variables []string               `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty"`
	Content   string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Engagement metrics
	Downloads      int64 `protobuf:"varint,10,opt,name=downloads,proto3" json:"downloads,omitempty"`
	Likes          int64 `protobuf:"varint,11,opt,name=likes,proto3" json:"likes,omitempty"`
	Dislikes       int64 `protobuf:"varint,12,opt,name=dislikes,proto3" json:"dislikes,omitempty"`
	UsedByPersonas int64 `protobuf:"varint,13,opt,name=used_by_personas,json=usedByPersonas,proto3" json:"used_by_personas,omitempty"` // Count of personas referencing this fragment
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Fragment) Reset() {
	*x = Fragment{}
	mi := &file_proto_fragments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fragment) ProtoMessage() {}

func (x *Fragment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fragment.ProtoReflect.Descriptor instead.
func (*Fragment) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{0}
}

func (x *Fragment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Fragment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fragment) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Fragment) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Fragment) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Fragment) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Fragment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Fragment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Fragment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Fragment) GetDownloads() int64 {
	if x != nil {
		return x.Downloads
	}
	return 0
}

func (x *Fragment) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Fragment) GetDislikes() int64 {
	if x != nil {
		return x.Dislikes
	}
	return 0
}

func (x *Fragment) GetUsedByPersonas() int64 {
	if x != nil {
		return x.UsedByPersonas
	}
	return 0
}

// CreateFragmentRequest creates a new fragment.
type CreateFragmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Variables     []string               `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFragmentRequest) Reset() {
	*x = CreateFragmentRequest{}
	mi := &file_proto_fragments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFragmentRequest) ProtoMessage() {}

func (x *CreateFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFragmentRequest.ProtoReflect.Descriptor instead.
func (*CreateFragmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFragmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFragmentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateFragmentRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateFragmentRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateFragmentRequest) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *CreateFragmentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// UpdateFragmentRequest updates an existing fragment.
type UpdateFragmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Variables     []string               `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFragmentRequest) Reset() {
	*x = UpdateFragmentRequest{}
	mi := &file_proto_fragments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFragmentRequest) ProtoMessage() {}

func (x *UpdateFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFragmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateFragmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFragmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFragmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFragmentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateFragmentRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *UpdateFragmentRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateFragmentRequest) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *UpdateFragmentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// GetFragmentRequest retrieves a fragment by ID.
type GetFragmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFragmentRequest) Reset() {
	*x = GetFragmentRequest{}
	mi := &file_proto_fragments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFragmentRequest) ProtoMessage() {}

func (x *GetFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFragmentRequest.ProtoReflect.Descriptor instead.
func (*GetFragmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{3}
}

func (x *GetFragmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetFragmentByNameRequest retrieves a fragment by name, author, and optional version.
type GetFragmentByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // Optional: if empty, returns latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFragmentByNameRequest) Reset() {
	*x = GetFragmentByNameRequest{}
	mi := &file_proto_fragments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFragmentByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFragmentByNameRequest) ProtoMessage() {}

func (x *GetFragmentByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFragmentByNameRequest.ProtoReflect.Descriptor instead.
func (*GetFragmentByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{4}
}

func (x *GetFragmentByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetFragmentByNameRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetFragmentByNameRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// DeleteFragmentRequest deletes a fragment by ID.
type DeleteFragmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFragmentRequest) Reset() {
	*x = DeleteFragmentRequest{}
	mi := &file_proto_fragments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFragmentRequest) ProtoMessage() {}

func (x *DeleteFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFragmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteFragmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFragmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListFragmentsRequest lists fragments with optional filtering.
type ListFragmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`                               // Filter by tags (OR logic)
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`                           // Filter by author
	NamePrefix    string                 `protobuf:"bytes,3,opt,name=name_prefix,json=namePrefix,proto3" json:"name_prefix,omitempty"` // Filter by name prefix
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`      // Max results per page
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`    // Pagination token
	Sort          SortOrder              `protobuf:"varint,6,opt,name=sort,proto3,enum=fragments.v1.SortOrder" json:"sort,omitempty"`  // Sort order (default: POPULARITY)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFragmentsRequest) Reset() {
	*x = ListFragmentsRequest{}
	mi := &file_proto_fragments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFragmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFragmentsRequest) ProtoMessage() {}

func (x *ListFragmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFragmentsRequest.ProtoReflect.Descriptor instead.
func (*ListFragmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{6}
}

func (x *ListFragmentsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListFragmentsRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ListFragmentsRequest) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

func (x *ListFragmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFragmentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListFragmentsRequest) GetSort() SortOrder {
	if x != nil {
		return x.Sort
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

// ListFragmentsResponse returns a paginated list of fragments.
type ListFragmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fragments     []*Fragment            `protobuf:"bytes,1,rep,name=fragments,proto3" json:"fragments,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFragmentsResponse) Reset() {
	*x = ListFragmentsResponse{}
	mi := &file_proto_fragments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFragmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFragmentsResponse) ProtoMessage() {}

func (x *ListFragmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFragmentsResponse.ProtoReflect.Descriptor instead.
func (*ListFragmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{7}
}

func (x *ListFragmentsResponse) GetFragments() []*Fragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

func (x *ListFragmentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// SearchFragmentsRequest searches fragments by content.
type SearchFragmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // Full-text search query
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`   // Optional tag filter
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Sort          SortOrder              `protobuf:"varint,5,opt,name=sort,proto3,enum=fragments.v1.SortOrder" json:"sort,omitempty"` // Sort order (default: POPULARITY)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFragmentsRequest) Reset() {
	*x = SearchFragmentsRequest{}
	mi := &file_proto_fragments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFragmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFragmentsRequest) ProtoMessage() {}

func (x *SearchFragmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFragmentsRequest.ProtoReflect.Descriptor instead.
func (*SearchFragmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{8}
}

func (x *SearchFragmentsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchFragmentsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchFragmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchFragmentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchFragmentsRequest) GetSort() SortOrder {
	if x != nil {
		return x.Sort
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

// SearchFragmentsResponse returns search results.
type SearchFragmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fragments     []*Fragment            `protobuf:"bytes,1,rep,name=fragments,proto3" json:"fragments,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFragmentsResponse) Reset() {
	*x = SearchFragmentsResponse{}
	mi := &file_proto_fragments_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFragmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFragmentsResponse) ProtoMessage() {}

func (x *SearchFragmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFragmentsResponse.ProtoReflect.Descriptor instead.
func (*SearchFragmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{9}
}

func (x *SearchFragmentsResponse) GetFragments() []*Fragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

func (x *SearchFragmentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// DownloadFragmentRequest increments download count and returns fragment.
type DownloadFragmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFragmentRequest) Reset() {
	*x = DownloadFragmentRequest{}
	mi := &file_proto_fragments_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFragmentRequest) ProtoMessage() {}

func (x *DownloadFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFragmentRequest.ProtoReflect.Descriptor instead.
func (*DownloadFragmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadFragmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// LikeFragmentRequest adds a like to a fragment.
type LikeFragmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeFragmentRequest) Reset() {
	*x = LikeFragmentRequest{}
	mi := &file_proto_fragments_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeFragmentRequest) ProtoMessage() {}

func (x *LikeFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeFragmentRequest.ProtoReflect.Descriptor instead.
func (*LikeFragmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{11}
}

func (x *LikeFragmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DislikeFragmentRequest adds a dislike to a fragment with required reason.
type DislikeFragmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // Required: why the user disliked this fragment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DislikeFragmentRequest) Reset() {
	*x = DislikeFragmentRequest{}
	mi := &file_proto_fragments_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DislikeFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DislikeFragmentRequest) ProtoMessage() {}

func (x *DislikeFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DislikeFragmentRequest.ProtoReflect.Descriptor instead.
func (*DislikeFragmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{12}
}

func (x *DislikeFragmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DislikeFragmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Dislike represents a dislike record with reason.
type Dislike struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FragmentId    string                 `protobuf:"bytes,1,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dislike) Reset() {
	*x = Dislike{}
	mi := &file_proto_fragments_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dislike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dislike) ProtoMessage() {}

func (x *Dislike) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dislike.ProtoReflect.Descriptor instead.
func (*Dislike) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{13}
}

func (x *Dislike) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

func (x *Dislike) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Dislike) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListDislikesRequest lists dislikes for a fragment.
type ListDislikesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FragmentId    string                 `protobuf:"bytes,1,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDislikesRequest) Reset() {
	*x = ListDislikesRequest{}
	mi := &file_proto_fragments_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDislikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDislikesRequest) ProtoMessage() {}

func (x *ListDislikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDislikesRequest.ProtoReflect.Descriptor instead.
func (*ListDislikesRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{14}
}

func (x *ListDislikesRequest) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

// ListDislikesResponse returns dislikes for a fragment.
type ListDislikesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dislikes      []*Dislike             `protobuf:"bytes,1,rep,name=dislikes,proto3" json:"dislikes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDislikesResponse) Reset() {
	*x = ListDislikesResponse{}
	mi := &file_proto_fragments_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDislikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDislikesResponse) ProtoMessage() {}

func (x *ListDislikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDislikesResponse.ProtoReflect.Descriptor instead.
func (*ListDislikesResponse) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{15}
}

func (x *ListDislikesResponse) GetDislikes() []*Dislike {
	if x != nil {
		return x.Dislikes
	}
	return nil
}

// FragmentRef is a reference to a fragment by name, author, and version.
type FragmentRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FragmentRef) Reset() {
	*x = FragmentRef{}
	mi := &file_proto_fragments_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentRef) ProtoMessage() {}

func (x *FragmentRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentRef.ProtoReflect.Descriptor instead.
func (*FragmentRef) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{16}
}

func (x *FragmentRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FragmentRef) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *FragmentRef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Persona represents a named collection of fragment references.
type Persona struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Fragments     []*FragmentRef         `protobuf:"bytes,6,rep,name=fragments,proto3" json:"fragments,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Downloads     int64                  `protobuf:"varint,9,opt,name=downloads,proto3" json:"downloads,omitempty"`
	Likes         int64                  `protobuf:"varint,10,opt,name=likes,proto3" json:"likes,omitempty"`
	Dislikes      int64                  `protobuf:"varint,11,opt,name=dislikes,proto3" json:"dislikes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Persona) Reset() {
	*x = Persona{}
	mi := &file_proto_fragments_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Persona) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Persona) ProtoMessage() {}

func (x *Persona) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Persona.ProtoReflect.Descriptor instead.
func (*Persona) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{17}
}

func (x *Persona) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Persona) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Persona) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Persona) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Persona) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Persona) GetFragments() []*FragmentRef {
	if x != nil {
		return x.Fragments
	}
	return nil
}

func (x *Persona) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Persona) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Persona) GetDownloads() int64 {
	if x != nil {
		return x.Downloads
	}
	return 0
}

func (x *Persona) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Persona) GetDislikes() int64 {
	if x != nil {
		return x.Dislikes
	}
	return 0
}

// CreatePersonaRequest creates a new persona.
type CreatePersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Fragments     []*FragmentRef         `protobuf:"bytes,5,rep,name=fragments,proto3" json:"fragments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonaRequest) Reset() {
	*x = CreatePersonaRequest{}
	mi := &file_proto_fragments_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonaRequest) ProtoMessage() {}

func (x *CreatePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonaRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{18}
}

func (x *CreatePersonaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePersonaRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreatePersonaRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreatePersonaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePersonaRequest) GetFragments() []*FragmentRef {
	if x != nil {
		return x.Fragments
	}
	return nil
}

// UpdatePersonaRequest updates an existing persona.
type UpdatePersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Fragments     []*FragmentRef         `protobuf:"bytes,6,rep,name=fragments,proto3" json:"fragments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonaRequest) Reset() {
	*x = UpdatePersonaRequest{}
	mi := &file_proto_fragments_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonaRequest) ProtoMessage() {}

func (x *UpdatePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonaRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{19}
}

func (x *UpdatePersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePersonaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePersonaRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *UpdatePersonaRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdatePersonaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePersonaRequest) GetFragments() []*FragmentRef {
	if x != nil {
		return x.Fragments
	}
	return nil
}

// GetPersonaRequest retrieves a persona by ID.
type GetPersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonaRequest) Reset() {
	*x = GetPersonaRequest{}
	mi := &file_proto_fragments_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonaRequest) ProtoMessage() {}

func (x *GetPersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonaRequest.ProtoReflect.Descriptor instead.
func (*GetPersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{20}
}

func (x *GetPersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetPersonaByNameRequest retrieves a persona by name, author, and optional version.
type GetPersonaByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // Optional: if empty, returns latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonaByNameRequest) Reset() {
	*x = GetPersonaByNameRequest{}
	mi := &file_proto_fragments_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonaByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonaByNameRequest) ProtoMessage() {}

func (x *GetPersonaByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonaByNameRequest.ProtoReflect.Descriptor instead.
func (*GetPersonaByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{21}
}

func (x *GetPersonaByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPersonaByNameRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetPersonaByNameRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// DeletePersonaRequest deletes a persona by ID.
type DeletePersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonaRequest) Reset() {
	*x = DeletePersonaRequest{}
	mi := &file_proto_fragments_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonaRequest) ProtoMessage() {}

func (x *DeletePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonaRequest.ProtoReflect.Descriptor instead.
func (*DeletePersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{22}
}

func (x *DeletePersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListPersonasRequest lists personas with optional filtering.
type ListPersonasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	NamePrefix    string                 `protobuf:"bytes,2,opt,name=name_prefix,json=namePrefix,proto3" json:"name_prefix,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Sort          SortOrder              `protobuf:"varint,5,opt,name=sort,proto3,enum=fragments.v1.SortOrder" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonasRequest) Reset() {
	*x = ListPersonasRequest{}
	mi := &file_proto_fragments_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonasRequest) ProtoMessage() {}

func (x *ListPersonasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonasRequest.ProtoReflect.Descriptor instead.
func (*ListPersonasRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{23}
}

func (x *ListPersonasRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ListPersonasRequest) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

func (x *ListPersonasRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPersonasRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPersonasRequest) GetSort() SortOrder {
	if x != nil {
		return x.Sort
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

// ListPersonasResponse returns a paginated list of personas.
type ListPersonasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personas      []*Persona             `protobuf:"bytes,1,rep,name=personas,proto3" json:"personas,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonasResponse) Reset() {
	*x = ListPersonasResponse{}
	mi := &file_proto_fragments_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonasResponse) ProtoMessage() {}

func (x *ListPersonasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonasResponse.ProtoReflect.Descriptor instead.
func (*ListPersonasResponse) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{24}
}

func (x *ListPersonasResponse) GetPersonas() []*Persona {
	if x != nil {
		return x.Personas
	}
	return nil
}

func (x *ListPersonasResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// DownloadPersonaRequest increments download count and returns persona with resolved fragments.
type DownloadPersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPersonaRequest) Reset() {
	*x = DownloadPersonaRequest{}
	mi := &file_proto_fragments_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPersonaRequest) ProtoMessage() {}

func (x *DownloadPersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPersonaRequest.ProtoReflect.Descriptor instead.
func (*DownloadPersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{25}
}

func (x *DownloadPersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DownloadPersonaResponse returns the persona with all fragments resolved.
type DownloadPersonaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persona       *Persona               `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
	Fragments     []*Fragment            `protobuf:"bytes,2,rep,name=fragments,proto3" json:"fragments,omitempty"` // Resolved fragment contents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPersonaResponse) Reset() {
	*x = DownloadPersonaResponse{}
	mi := &file_proto_fragments_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPersonaResponse) ProtoMessage() {}

func (x *DownloadPersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPersonaResponse.ProtoReflect.Descriptor instead.
func (*DownloadPersonaResponse) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{26}
}

func (x *DownloadPersonaResponse) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

func (x *DownloadPersonaResponse) GetFragments() []*Fragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

// LikePersonaRequest adds a like to a persona.
type LikePersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePersonaRequest) Reset() {
	*x = LikePersonaRequest{}
	mi := &file_proto_fragments_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePersonaRequest) ProtoMessage() {}

func (x *LikePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePersonaRequest.ProtoReflect.Descriptor instead.
func (*LikePersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{27}
}

func (x *LikePersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DislikePersonaRequest adds a dislike to a persona with required reason.
type DislikePersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DislikePersonaRequest) Reset() {
	*x = DislikePersonaRequest{}
	mi := &file_proto_fragments_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DislikePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DislikePersonaRequest) ProtoMessage() {}

func (x *DislikePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fragments_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DislikePersonaRequest.ProtoReflect.Descriptor instead.
func (*DislikePersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_fragments_proto_rawDescGZIP(), []int{28}
}

func (x *DislikePersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DislikePersonaRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_fragments_proto protoreflect.FileDescriptor

const file_proto_fragments_proto_rawDesc = "" +
	"\n" +
	"\x15proto/fragments.proto\x12\ffragments.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9c\x03\n" +
	"\bFragment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1c\n" +
	"\tvariables\x18\x06 \x03(\tR\tvariables\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1c\n" +
	"\tdownloads\x18\n" +
	" \x01(\x03R\tdownloads\x12\x14\n" +
	"\x05likes\x18\v \x01(\x03R\x05likes\x12\x1a\n" +
	"\bdislikes\x18\f \x01(\x03R\bdislikes\x12(\n" +
	"\x10used_by_personas\x18\r \x01(\x03R\x0eusedByPersonas\"\xa9\x01\n" +
	"\x15CreateFragmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1c\n" +
	"\tvariables\x18\x05 \x03(\tR\tvariables\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\"\xb9\x01\n" +
	"\x15UpdateFragmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1c\n" +
	"\tvariables\x18\x06 \x03(\tR\tvariables\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\"$\n" +
	"\x12GetFragmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\x18GetFragmentByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"'\n" +
	"\x15DeleteFragmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcc\x01\n" +
	"\x14ListFragmentsRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1f\n" +
	"\vname_prefix\x18\x03 \x01(\tR\n" +
	"namePrefix\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12+\n" +
	"\x04sort\x18\x06 \x01(\x0e2\x17.fragments.v1.SortOrderR\x04sort\"u\n" +
	"\x15ListFragmentsResponse\x124\n" +
	"\tfragments\x18\x01 \x03(\v2\x16.fragments.v1.FragmentR\tfragments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xab\x01\n" +
	"\x16SearchFragmentsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12+\n" +
	"\x04sort\x18\x05 \x01(\x0e2\x17.fragments.v1.SortOrderR\x04sort\"w\n" +
	"\x17SearchFragmentsResponse\x124\n" +
	"\tfragments\x18\x01 \x03(\v2\x16.fragments.v1.FragmentR\tfragments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\")\n" +
	"\x17DownloadFragmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13LikeFragmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x16DislikeFragmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"}\n" +
	"\aDislike\x12\x1f\n" +
	"\vfragment_id\x18\x01 \x01(\tR\n" +
	"fragmentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"6\n" +
	"\x13ListDislikesRequest\x12\x1f\n" +
	"\vfragment_id\x18\x01 \x01(\tR\n" +
	"fragmentId\"I\n" +
	"\x14ListDislikesResponse\x121\n" +
	"\bdislikes\x18\x01 \x03(\v2\x15.fragments.v1.DislikeR\bdislikes\"S\n" +
	"\vFragmentRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x80\x03\n" +
	"\aPersona\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x127\n" +
	"\tfragments\x18\x06 \x03(\v2\x19.fragments.v1.FragmentRefR\tfragments\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1c\n" +
	"\tdownloads\x18\t \x01(\x03R\tdownloads\x12\x14\n" +
	"\x05likes\x18\n" +
	" \x01(\x03R\x05likes\x12\x1a\n" +
	"\bdislikes\x18\v \x01(\x03R\bdislikes\"\xb7\x01\n" +
	"\x14CreatePersonaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x127\n" +
	"\tfragments\x18\x05 \x03(\v2\x19.fragments.v1.FragmentRefR\tfragments\"\xc7\x01\n" +
	"\x14UpdatePersonaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x127\n" +
	"\tfragments\x18\x06 \x03(\v2\x19.fragments.v1.FragmentRefR\tfragments\"#\n" +
	"\x11GetPersonaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\x17GetPersonaByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"&\n" +
	"\x14DeletePersonaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb7\x01\n" +
	"\x13ListPersonasRequest\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x1f\n" +
	"\vname_prefix\x18\x02 \x01(\tR\n" +
	"namePrefix\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12+\n" +
	"\x04sort\x18\x05 \x01(\x0e2\x17.fragments.v1.SortOrderR\x04sort\"q\n" +
	"\x14ListPersonasResponse\x121\n" +
	"\bpersonas\x18\x01 \x03(\v2\x15.fragments.v1.PersonaR\bpersonas\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"(\n" +
	"\x16DownloadPersonaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x80\x01\n" +
	"\x17DownloadPersonaResponse\x12/\n" +
	"\apersona\x18\x01 \x01(\v2\x15.fragments.v1.PersonaR\apersona\x124\n" +
	"\tfragments\x18\x02 \x03(\v2\x16.fragments.v1.FragmentR\tfragments\"$\n" +
	"\x12LikePersonaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x15DislikePersonaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*\x88\x01\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SORT_ORDER_POPULARITY\x10\x01\x12\x18\n" +
	"\x14SORT_ORDER_DOWNLOADS\x10\x02\x12\x15\n" +
	"\x11SORT_ORDER_RECENT\x10\x03\x12\x13\n" +
	"\x0fSORT_ORDER_NAME\x10\x042\xf2\x11\n" +
	"\x0fFragmentService\x12g\n" +
	"\x0eCreateFragment\x12#.fragments.v1.CreateFragmentRequest\x1a\x16.fragments.v1.Fragment\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/fragments\x12c\n" +
	"\vGetFragment\x12 .fragments.v1.GetFragmentRequest\x1a\x16.fragments.v1.Fragment\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/fragments/{id}\x12\x81\x01\n" +
	"\x11GetFragmentByName\x12&.fragments.v1.GetFragmentByNameRequest\x1a\x16.fragments.v1.Fragment\",\x82\xd3\xe4\x93\x02&\x12$/v1/fragments/by-key/{author}/{name}\x12l\n" +
	"\x0eUpdateFragment\x12#.fragments.v1.UpdateFragmentRequest\x1a\x16.fragments.v1.Fragment\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/fragments/{id}\x12i\n" +
	"\x0eDeleteFragment\x12#.fragments.v1.DeleteFragmentRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/fragments/{id}\x12o\n" +
	"\rListFragments\x12\".fragments.v1.ListFragmentsRequest\x1a#.fragments.v1.ListFragmentsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/fragments\x12|\n" +
	"\x0fSearchFragments\x12$.fragments.v1.SearchFragmentsRequest\x1a%.fragments.v1.SearchFragmentsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/fragments/search\x12v\n" +
	"\x10DownloadFragment\x12%.fragments.v1.DownloadFragmentRequest\x1a\x16.fragments.v1.Fragment\"#\x82\xd3\xe4\x93\x02\x1d\"\x1b/v1/fragments/{id}/download\x12j\n" +
	"\fLikeFragment\x12!.fragments.v1.LikeFragmentRequest\x1a\x16.fragments.v1.Fragment\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/v1/fragments/{id}/like\x12v\n" +
	"\x0fDislikeFragment\x12$.fragments.v1.DislikeFragmentRequest\x1a\x16.fragments.v1.Fragment\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/fragments/{id}/dislike\x12\x83\x01\n" +
	"\fListDislikes\x12!.fragments.v1.ListDislikesRequest\x1a\".fragments.v1.ListDislikesResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/fragments/{fragment_id}/dislikes\x12c\n" +
	"\rCreatePersona\x12\".fragments.v1.CreatePersonaRequest\x1a\x15.fragments.v1.Persona\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/personas\x12_\n" +
	"\n" +
	"GetPersona\x12\x1f.fragments.v1.GetPersonaRequest\x1a\x15.fragments.v1.Persona\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/personas/{id}\x12}\n" +
	"\x10GetPersonaByName\x12%.fragments.v1.GetPersonaByNameRequest\x1a\x15.fragments.v1.Persona\"+\x82\xd3\xe4\x93\x02%\x12#/v1/personas/by-key/{author}/{name}\x12h\n" +
	"\rUpdatePersona\x12\".fragments.v1.UpdatePersonaRequest\x1a\x15.fragments.v1.Persona\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/personas/{id}\x12f\n" +
	"\rDeletePersona\x12\".fragments.v1.DeletePersonaRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/personas/{id}\x12k\n" +
	"\fListPersonas\x12!.fragments.v1.ListPersonasRequest\x1a\".fragments.v1.ListPersonasResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/personas\x12\x82\x01\n" +
	"\x0fDownloadPersona\x12$.fragments.v1.DownloadPersonaRequest\x1a%.fragments.v1.DownloadPersonaResponse\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/v1/personas/{id}/download\x12f\n" +
	"\vLikePersona\x12 .fragments.v1.LikePersonaRequest\x1a\x15.fragments.v1.Persona\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/v1/personas/{id}/like\x12r\n" +
	"\x0eDislikePersona\x12#.fragments.v1.DislikePersonaRequest\x1a\x15.fragments.v1.Persona\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/personas/{id}/dislikeB\x1fZ\x1dmlcm/server/proto/fragmentspbb\x06proto3"

var (
	file_proto_fragments_proto_rawDescOnce sync.Once
	file_proto_fragments_proto_rawDescData []byte
)

func file_proto_fragments_proto_rawDescGZIP() []byte {
	file_proto_fragments_proto_rawDescOnce.Do(func() {
		file_proto_fragments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fragments_proto_rawDesc), len(file_proto_fragments_proto_rawDesc)))
	})
	return file_proto_fragments_proto_rawDescData
}

var file_proto_fragments_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_fragments_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_fragments_proto_goTypes = []any{
	(SortOrder)(0),                   // 0: fragments.v1.SortOrder
	(*Fragment)(nil),                 // 1: fragments.v1.Fragment
	(*CreateFragmentRequest)(nil),    // 2: fragments.v1.CreateFragmentRequest
	(*UpdateFragmentRequest)(nil),    // 3: fragments.v1.UpdateFragmentRequest
	(*GetFragmentRequest)(nil),       // 4: fragments.v1.GetFragmentRequest
	(*GetFragmentByNameRequest)(nil), // 5: fragments.v1.GetFragmentByNameRequest
	(*DeleteFragmentRequest)(nil),    // 6: fragments.v1.DeleteFragmentRequest
	(*ListFragmentsRequest)(nil),     // 7: fragments.v1.ListFragmentsRequest
	(*ListFragmentsResponse)(nil),    // 8: fragments.v1.ListFragmentsResponse
	(*SearchFragmentsRequest)(nil),   // 9: fragments.v1.SearchFragmentsRequest
	(*SearchFragmentsResponse)(nil),  // 10: fragments.v1.SearchFragmentsResponse
	(*DownloadFragmentRequest)(nil),  // 11: fragments.v1.DownloadFragmentRequest
	(*LikeFragmentRequest)(nil),      // 12: fragments.v1.LikeFragmentRequest
	(*DislikeFragmentRequest)(nil),   // 13: fragments.v1.DislikeFragmentRequest
	(*Dislike)(nil),                  // 14: fragments.v1.Dislike
	(*ListDislikesRequest)(nil),      // 15: fragments.v1.ListDislikesRequest
	(*ListDislikesResponse)(nil),     // 16: fragments.v1.ListDislikesResponse
	(*FragmentRef)(nil),              // 17: fragments.v1.FragmentRef
	(*Persona)(nil),                  // 18: fragments.v1.Persona
	(*CreatePersonaRequest)(nil),     // 19: fragments.v1.CreatePersonaRequest
	(*UpdatePersonaRequest)(nil),     // 20: fragments.v1.UpdatePersonaRequest
	(*GetPersonaRequest)(nil),        // 21: fragments.v1.GetPersonaRequest
	(*GetPersonaByNameRequest)(nil),  // 22: fragments.v1.GetPersonaByNameRequest
	(*DeletePersonaRequest)(nil),     // 23: fragments.v1.DeletePersonaRequest
	(*ListPersonasRequest)(nil),      // 24: fragments.v1.ListPersonasRequest
	(*ListPersonasResponse)(nil),     // 25: fragments.v1.ListPersonasResponse
	(*DownloadPersonaRequest)(nil),   // 26: fragments.v1.DownloadPersonaRequest
	(*DownloadPersonaResponse)(nil),  // 27: fragments.v1.DownloadPersonaResponse
	(*LikePersonaRequest)(nil),       // 28: fragments.v1.LikePersonaRequest
	(*DislikePersonaRequest)(nil),    // 29: fragments.v1.DislikePersonaRequest
	(*timestamppb.Timestamp)(nil),    // 30: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 31: google.protobuf.Empty
}
var file_proto_fragments_proto_depIdxs = []int32{
	30, // 0: fragments.v1.Fragment.created_at:type_name -> google.protobuf.Timestamp
	30, // 1: fragments.v1.Fragment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: fragments.v1.ListFragmentsRequest.sort:type_name -> fragments.v1.SortOrder
	1,  // 3: fragments.v1.ListFragmentsResponse.fragments:type_name -> fragments.v1.Fragment
	0,  // 4: fragments.v1.SearchFragmentsRequest.sort:type_name -> fragments.v1.SortOrder
	1,  // 5: fragments.v1.SearchFragmentsResponse.fragments:type_name -> fragments.v1.Fragment
	30, // 6: fragments.v1.Dislike.created_at:type_name -> google.protobuf.Timestamp
	14, // 7: fragments.v1.ListDislikesResponse.dislikes:type_name -> fragments.v1.Dislike
	17, // 8: fragments.v1.Persona.fragments:type_name -> fragments.v1.FragmentRef
	30, // 9: fragments.v1.Persona.created_at:type_name -> google.protobuf.Timestamp
	30, // 10: fragments.v1.Persona.updated_at:type_name -> google.protobuf.Timestamp
	17, // 11: fragments.v1.CreatePersonaRequest.fragments:type_name -> fragments.v1.FragmentRef
	17, // 12: fragments.v1.UpdatePersonaRequest.fragments:type_name -> fragments.v1.FragmentRef
	0,  // 13: fragments.v1.ListPersonasRequest.sort:type_name -> fragments.v1.SortOrder
	18, // 14: fragments.v1.ListPersonasResponse.personas:type_name -> fragments.v1.Persona
	18, // 15: fragments.v1.DownloadPersonaResponse.persona:type_name -> fragments.v1.Persona
	1,  // 16: fragments.v1.DownloadPersonaResponse.fragments:type_name -> fragments.v1.Fragment
	2,  // 17: fragments.v1.FragmentService.CreateFragment:input_type -> fragments.v1.CreateFragmentRequest
	4,  // 18: fragments.v1.FragmentService.GetFragment:input_type -> fragments.v1.GetFragmentRequest
	5,  // 19: fragments.v1.FragmentService.GetFragmentByName:input_type -> fragments.v1.GetFragmentByNameRequest
	3,  // 20: fragments.v1.FragmentService.UpdateFragment:input_type -> fragments.v1.UpdateFragmentRequest
	6,  // 21: fragments.v1.FragmentService.DeleteFragment:input_type -> fragments.v1.DeleteFragmentRequest
	7,  // 22: fragments.v1.FragmentService.ListFragments:input_type -> fragments.v1.ListFragmentsRequest
	9,  // 23: fragments.v1.FragmentService.SearchFragments:input_type -> fragments.v1.SearchFragmentsRequest
	11, // 24: fragments.v1.FragmentService.DownloadFragment:input_type -> fragments.v1.DownloadFragmentRequest
	12, // 25: fragments.v1.FragmentService.LikeFragment:input_type -> fragments.v1.LikeFragmentRequest
	13, // 26: fragments.v1.FragmentService.DislikeFragment:input_type -> fragments.v1.DislikeFragmentRequest
	15, // 27: fragments.v1.FragmentService.ListDislikes:input_type -> fragments.v1.ListDislikesRequest
	19, // 28: fragments.v1.FragmentService.CreatePersona:input_type -> fragments.v1.CreatePersonaRequest
	21, // 29: fragments.v1.FragmentService.GetPersona:input_type -> fragments.v1.GetPersonaRequest
	22, // 30: fragments.v1.FragmentService.GetPersonaByName:input_type -> fragments.v1.GetPersonaByNameRequest
	20, // 31: fragments.v1.FragmentService.UpdatePersona:input_type -> fragments.v1.UpdatePersonaRequest
	23, // 32: fragments.v1.FragmentService.DeletePersona:input_type -> fragments.v1.DeletePersonaRequest
	24, // 33: fragments.v1.FragmentService.ListPersonas:input_type -> fragments.v1.ListPersonasRequest
	26, // 34: fragments.v1.FragmentService.DownloadPersona:input_type -> fragments.v1.DownloadPersonaRequest
	28, // 35: fragments.v1.FragmentService.LikePersona:input_type -> fragments.v1.LikePersonaRequest
	29, // 36: fragments.v1.FragmentService.DislikePersona:input_type -> fragments.v1.DislikePersonaRequest
	1,  // 37: fragments.v1.FragmentService.CreateFragment:output_type -> fragments.v1.Fragment
	1,  // 38: fragments.v1.FragmentService.GetFragment:output_type -> fragments.v1.Fragment
	1,  // 39: fragments.v1.FragmentService.GetFragmentByName:output_type -> fragments.v1.Fragment
	1,  // 40: fragments.v1.FragmentService.UpdateFragment:output_type -> fragments.v1.Fragment
	31, // 41: fragments.v1.FragmentService.DeleteFragment:output_type -> google.protobuf.Empty
	8,  // 42: fragments.v1.FragmentService.ListFragments:output_type -> fragments.v1.ListFragmentsResponse
	10, // 43: fragments.v1.FragmentService.SearchFragments:output_type -> fragments.v1.SearchFragmentsResponse
	1,  // 44: fragments.v1.FragmentService.DownloadFragment:output_type -> fragments.v1.Fragment
	1,  // 45: fragments.v1.FragmentService.LikeFragment:output_type -> fragments.v1.Fragment
	1,  // 46: fragments.v1.FragmentService.DislikeFragment:output_type -> fragments.v1.Fragment
	16, // 47: fragments.v1.FragmentService.ListDislikes:output_type -> fragments.v1.ListDislikesResponse
	18, // 48: fragments.v1.FragmentService.CreatePersona:output_type -> fragments.v1.Persona
	18, // 49: fragments.v1.FragmentService.GetPersona:output_type -> fragments.v1.Persona
	18, // 50: fragments.v1.FragmentService.GetPersonaByName:output_type -> fragments.v1.Persona
	18, // 51: fragments.v1.FragmentService.UpdatePersona:output_type -> fragments.v1.Persona
	31, // 52: fragments.v1.FragmentService.DeletePersona:output_type -> google.protobuf.Empty
	25, // 53: fragments.v1.FragmentService.ListPersonas:output_type -> fragments.v1.ListPersonasResponse
	27, // 54: fragments.v1.FragmentService.DownloadPersona:output_type -> fragments.v1.DownloadPersonaResponse
	18, // 55: fragments.v1.FragmentService.LikePersona:output_type -> fragments.v1.Persona
	18, // 56: fragments.v1.FragmentService.DislikePersona:output_type -> fragments.v1.Persona
	37, // [37:57] is the sub-list for method output_type
	17, // [17:37] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_fragments_proto_init() }
func file_proto_fragments_proto_init() {
	if File_proto_fragments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fragments_proto_rawDesc), len(file_proto_fragments_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fragments_proto_goTypes,
		DependencyIndexes: file_proto_fragments_proto_depIdxs,
		EnumInfos:         file_proto_fragments_proto_enumTypes,
		MessageInfos:      file_proto_fragments_proto_msgTypes,
	}.Build()
	File_proto_fragments_proto = out.File
	file_proto_fragments_proto_goTypes = nil
	file_proto_fragments_proto_depIdxs = nil
}
