package coord

import (
	"io"
	"sync"
	"sync/atomic"
	"time"

	agentcoordpb "github.com/ctxloom/ctxloom/internal/agentcoord"
)

// TERMINAL INJECTION — the delivery half of the session-owner's wake.
//
// A child's arrival wakes it structurally: SetTurnSink hands the pushed
// message straight to the engine as a new turn. A session-owner Home never
// gets a turn sink (no EngineHost is ever built for it — see
// llm_runner_common.go), so deliverNotice's third case buffers the message
// and calls terminalNudge instead. TerminalInjector is what that hook is set
// to: it turns "mail arrived, nobody had a route to give it" into a literal
// keystroke in the engine's own stdin, so the SAME mechanism that lets a
// human type into a running session (the interceptor/PTY seam) also carries
// the coordinator's own wake.
//
// The injected text is a generated ctxloom-reminder frame
// (MailPendingReminder.XmlLike, "call agent_recv") — the wire format this
// repo already defines for exactly this purpose (coordination.proto: "NEVER
// WIRE TRAFFIC; exist to be rendered into injected ... frames", generated by
// xmllike_gen.go) and had zero callers before this file. It reads to the
// engine as if the human had typed a direct instruction, which is what makes
// it something the model ACTS on rather than narrates.

const (
	// terminalInjectQuiet is how long the engine's own output must have been
	// silent before an injection is considered safe: long enough that a
	// normal inter-token gap during streaming doesn't look quiet, short
	// enough that a genuinely idle engine is nudged promptly.
	terminalInjectQuiet = 500 * time.Millisecond
	// terminalInjectTick is how often quiet is re-checked.
	terminalInjectTick = 25 * time.Millisecond
	// terminalInjectMaxWait bounds the total wait. Reaching it is not an
	// error — there is no turn-boundary signal available to a terminal-driven
	// engine to wait for instead, so past this bound the injector delivers
	// anyway rather than risk waiting forever on an engine that is idling
	// noisily (a spinner, a heartbeat) and never looks quiet by the strict
	// definition above.
	terminalInjectMaxWait = 4 * time.Second
)

// TerminalInjector is a Home's registered terminalNudge target. Construct one
// with NewTerminalInjector and call Wrap once, at the moment the interactive
// engine's own stdin/stdout become available, to obtain the seams Execute
// should actually hand the engine.
type TerminalInjector struct {
	quiet, tick, maxWait time.Duration

	lastWrite atomic.Int64 // unix nanos of the last stdout passthrough write

	mu      sync.Mutex
	waiting bool // an injection cycle is already scheduled/running
	inject  func(string)
	count   func() int
}

// NewTerminalInjector builds an injector for home and registers it as home's
// terminal nudge immediately: a nudge that fires before Wrap is called finds
// inject nil and is a no-op (the message stays buffered for the next nudge,
// or a real Recv), rather than lost.
func NewTerminalInjector(home *Home) *TerminalInjector {
	ti := &TerminalInjector{
		quiet:   terminalInjectQuiet,
		tick:    terminalInjectTick,
		maxWait: terminalInjectMaxWait,
		count:   home.BufferedMailCount,
	}
	home.SetTerminalNudge(ti.nudge)
	return ti
}

// Wrap returns the stdin/stdout an interactive Execute should use in place of
// the real terminal seams: stdout is tapped for the quiet signal (every
// passthrough write resets the idle clock), and stdin gains the injection
// channel a nudge cycle writes into.
func (ti *TerminalInjector) Wrap(stdin io.Reader, stdout io.Writer) (io.Reader, io.Writer) {
	r := newNudgeReader(stdin)
	ti.mu.Lock()
	ti.inject = r.Inject
	ti.mu.Unlock()
	return r, &quietTap{dst: stdout, lastWrite: &ti.lastWrite}
}

// nudge is home's terminalNudge callback: it must not block (deliverNotice
// calls it inline, on the goroutine that just received the coordinator's
// push), so it only arms a background wait-and-inject cycle, coalescing
// concurrent arrivals into the one cycle already running.
func (ti *TerminalInjector) nudge() {
	ti.mu.Lock()
	if ti.waiting {
		ti.mu.Unlock()
		return
	}
	ti.waiting = true
	ti.mu.Unlock()
	go ti.run()
}

// run waits for quiet (or the bound) and then injects, if there is still
// anything to report — a Recv the engine made on its own between the nudge
// and now may already have drained the buffer, in which case there is
// nothing to say and injecting would be a stale, content-free interruption.
func (ti *TerminalInjector) run() {
	defer func() {
		ti.mu.Lock()
		ti.waiting = false
		ti.mu.Unlock()
	}()
	deadline := time.Now().Add(ti.maxWait)
	for {
		idle := time.Duration(time.Now().UnixNano() - ti.lastWrite.Load())
		if idle >= ti.quiet || !time.Now().Before(deadline) {
			break
		}
		time.Sleep(ti.tick)
	}
	ti.mu.Lock()
	inject := ti.inject
	ti.mu.Unlock()
	if inject == nil {
		return // Wrap was never called: no interactive stdin exists to inject into
	}
	if n := ti.count(); n > 0 {
		inject((&agentcoordpb.MailPendingReminder{Count: uint32(n)}).XmlLike() + "\n")
	}
}

// quietTap wraps an engine's stdout, recording when the last byte actually
// reached it — TerminalInjector's quiet signal. It is a plain pass-through
// otherwise; unlike termui's outputGate (the HOST-side surround's own
// idle heuristic, unreachable from here — this runs in the runner process,
// the host in a separate one) it holds nothing back.
type quietTap struct {
	dst       io.Writer
	lastWrite *atomic.Int64
}

func (t *quietTap) Write(p []byte) (int, error) {
	n, err := t.dst.Write(p)
	t.lastWrite.Store(time.Now().UnixNano())
	return n, err
}

// nudgeReader wraps the real interactive stdin so injected text can be
// delivered even while the human is typing nothing at all: a background pump
// is the only way to do that, since the real reader's Read blocks on a live
// terminal with no other way to interrupt it.
type nudgeReader struct {
	inject chan []byte
	real   chan []byte
	errCh  chan error

	leftover []byte // read by Read's single caller only; no lock needed
}

func newNudgeReader(real io.Reader) *nudgeReader {
	r := &nudgeReader{
		inject: make(chan []byte, 1), // coalesced: one pending frame is all there ever is
		real:   make(chan []byte),
		errCh:  make(chan error, 1),
	}
	go r.pump(real)
	return r
}

func (r *nudgeReader) pump(real io.Reader) {
	buf := make([]byte, 4096)
	for {
		n, err := real.Read(buf)
		if n > 0 {
			chunk := make([]byte, n)
			copy(chunk, buf[:n])
			r.real <- chunk
		}
		if err != nil {
			r.errCh <- err
			return
		}
	}
}

// Read favors already-injected bytes over the real stream (an injected frame
// should not be stuck behind a keystroke that has not arrived yet), then
// blocks on whichever of the two produces first.
func (r *nudgeReader) Read(p []byte) (int, error) {
	if len(r.leftover) > 0 {
		n := copy(p, r.leftover)
		r.leftover = r.leftover[n:]
		return n, nil
	}
	select {
	case chunk := <-r.inject:
		return r.deliver(p, chunk)
	default:
	}
	select {
	case chunk := <-r.inject:
		return r.deliver(p, chunk)
	case chunk := <-r.real:
		return r.deliver(p, chunk)
	case err := <-r.errCh:
		return 0, err
	}
}

func (r *nudgeReader) deliver(p, chunk []byte) (int, error) {
	n := copy(p, chunk)
	if n < len(chunk) {
		r.leftover = chunk[n:]
	}
	return n, nil
}

// Inject queues text for the next Read, as if it had been typed. It never
// blocks: the channel holds exactly one pending frame, which is the
// coalescing contract (TerminalInjector.run only ever has one cycle in
// flight) — a full channel means a frame is already queued and unread, so a
// second Inject before the first is consumed replaces it rather than piling
// up (the replacement's count is the more current one anyway).
func (r *nudgeReader) Inject(text string) {
	select {
	case r.inject <- []byte(text):
	default:
		select {
		case <-r.inject:
		default:
		}
		select {
		case r.inject <- []byte(text):
		default:
		}
	}
}
