module github.com/ctxloom/ctxloom

go 1.25.0

// ctxloom-local fork of hashicorp/go-plugin@v1.7.0 with a single env-gated
// serverListener patch (PLUGIN_LISTEN_TCP=1 forces the TCP listener) so the
// containerized backend plugin can speak TCP over host loopback across the
// Docker Desktop VM boundary on macOS/Windows. Self-contained relative replace:
// resolves identically under the host go.work AND container/CI GOWORK=off builds
// (the devcontainer mounts the repo root, so ./third_party is present). See
// third_party/go-plugin/CTXLOOM_FORK.md. Migrate to an org fork before release.
replace github.com/hashicorp/go-plugin => ./third_party/go-plugin

// TEMPORARY: ctxloom's ACP wire types (internal/acp/api, deleted in this
// change) are now schema-generated by benjaminabbitt/acp-go-sdk, a fork of
// coder/acp-go-sdk (branch schema-v1.19.0) that adds a generator + targets
// ACP schema-v1.19.0 — byte-identical to ctxloom's own vendored schema at
// internal/acptest/acp-schema-v1.json. The fork's PR upstream to
// coder/acp-go-sdk has NOT yet merged, so this replace redirects the
// upstream-named requirement to the fork until it does.
// REMOVAL CONDITION: once github.com/coder/acp-go-sdk publishes a release
// carrying schema-v1.19.0 (i.e. the fork's PR merges and ships), delete this
// replace line and bump the github.com/coder/acp-go-sdk require version to
// that release — no source changes needed, ctxloom imports the upstream
// path already.
replace github.com/coder/acp-go-sdk => github.com/benjaminabbitt/acp-go-sdk v0.13.6-0.20260716172546-89c5c8173ab4

// clifmt (Phase 0 of the CLI-primary reorg) is a separate, independently
// versioned module shared across ctxloom/harp/taskloom/ltk. No tagged
// release exists yet, so it resolves via a relative replace to the sibling
// checkout at ../../clifmt (both are worktrees under workspace/ctxloom/).
// Swap this for a real version requirement once clifmt cuts its first tag.
replace github.com/ctxloom/clifmt => ../../clifmt

require (
	github.com/Masterminds/semver/v3 v3.5.0
	github.com/bmatcuk/doublestar/v4 v4.10.0
	github.com/cbroglie/mustache v1.4.0
	github.com/charmbracelet/bubbles v0.21.0
	github.com/charmbracelet/bubbletea v1.3.10
	github.com/charmbracelet/lipgloss v1.1.0
	// Required under its real upstream name (coder/acp-go-sdk) so ctxloom's
	// source imports "github.com/coder/acp-go-sdk" — see the TEMPORARY
	// replace directive below for why the code that actually satisfies this
	// requirement is a fork, and what removes the redirect.
	github.com/coder/acp-go-sdk v0.13.5
	github.com/cucumber/godog v0.15.1
	github.com/go-git/go-git/v5 v5.19.1
	github.com/go-viper/mapstructure/v2 v2.4.0
	github.com/gofrs/flock v0.13.0
	github.com/google/go-github/v60 v60.0.0
	github.com/google/jsonschema-go v0.4.3
	github.com/gtramontina/ooze v0.2.0
	github.com/hashicorp/go-hclog v1.6.3
	github.com/hashicorp/go-plugin v1.7.0
	github.com/hiddeco/sshsig v0.2.0
	github.com/modelcontextprotocol/go-sdk v1.6.1
	github.com/pelletier/go-toml/v2 v2.4.3
	github.com/pmezard/go-difflib v1.0.0
	github.com/santhosh-tekuri/jsonschema/v5 v5.3.1
	github.com/smacker/go-tree-sitter v0.0.0-20240827094217-dd81d9e9be82
	github.com/spf13/afero v1.15.0
	github.com/spf13/cobra v1.10.2
	github.com/stretchr/testify v1.11.1
	go.uber.org/goleak v1.3.0
	go.uber.org/zap v1.27.1
	golang.org/x/crypto v0.51.0
	golang.org/x/sync v0.20.0
	golang.org/x/term v0.43.0
	google.golang.org/genproto/googleapis/rpc v0.0.0-20260526163538-3dc84a4a5aaa
	google.golang.org/grpc v1.81.1
	google.golang.org/protobuf v1.36.11
	gopkg.in/yaml.v3 v3.0.1
	mvdan.cc/sh/v3 v3.13.1
)

require (
	github.com/aymanbagabas/go-pty v0.2.3
	github.com/fsnotify/fsnotify v1.10.1
	github.com/klauspost/cpuid/v2 v2.3.0 // indirect
	golang.org/x/sys v0.44.0
)

require github.com/ctxloom/clifmt v0.0.0-00010101000000-000000000000

require (
	dario.cat/mergo v1.0.2 // indirect
	github.com/Microsoft/go-winio v0.6.2 // indirect
	github.com/ProtonMail/go-crypto v1.1.6 // indirect
	github.com/aymanbagabas/go-osc52/v2 v2.0.1 // indirect
	github.com/charmbracelet/colorprofile v0.2.3-0.20250311203215-f60798e515dc // indirect
	github.com/charmbracelet/x/ansi v0.10.1 // indirect
	github.com/charmbracelet/x/cellbuf v0.0.13-0.20250311204145-2c3ea96c31dd // indirect
	github.com/charmbracelet/x/term v0.2.1 // indirect
	github.com/cloudflare/circl v1.6.3 // indirect
	github.com/cpuguy83/go-md2man/v2 v2.0.6 // indirect
	github.com/creack/pty v1.1.24 // indirect
	github.com/cucumber/gherkin/go/v26 v26.2.0 // indirect
	github.com/cucumber/messages/go/v21 v21.0.1 // indirect
	github.com/cyphar/filepath-securejoin v0.6.1 // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/emirpasic/gods v1.18.1 // indirect
	github.com/erikgeiser/coninput v0.0.0-20211004153227-1c3628e74d0f // indirect
	github.com/fatih/color v1.16.0 // indirect
	github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376 // indirect
	github.com/go-git/go-billy/v5 v5.9.0 // indirect
	github.com/gofrs/uuid v4.3.1+incompatible // indirect
	github.com/golang/groupcache v0.0.0-20241129210726-2c02b8208cf8 // indirect
	github.com/golang/protobuf v1.5.4 // indirect
	github.com/google/go-querystring v1.2.0 // indirect
	github.com/hashicorp/go-immutable-radix v1.3.1 // indirect
	github.com/hashicorp/go-memdb v1.3.4 // indirect
	github.com/hashicorp/go-uuid v1.0.3 // indirect
	github.com/hashicorp/golang-lru v0.5.4 // indirect
	github.com/hashicorp/yamux v0.1.2 // indirect
	github.com/hexops/gotextdiff v1.0.3 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99 // indirect
	github.com/kevinburke/ssh_config v1.2.0 // indirect
	github.com/lucasb-eyer/go-colorful v1.2.0 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/mattn/go-localereader v0.0.1 // indirect
	github.com/mattn/go-runewidth v0.0.16 // indirect
	github.com/muesli/ansi v0.0.0-20230316100256-276c6243b2f6 // indirect
	github.com/muesli/cancelreader v0.2.2 // indirect
	github.com/muesli/termenv v0.16.0 // indirect
	github.com/oklog/run v1.1.0 // indirect
	github.com/pjbgf/sha1cd v0.6.0 // indirect
	github.com/rivo/uniseg v0.4.7 // indirect
	github.com/rogpeppe/go-internal v1.15.0 // indirect
	github.com/russross/blackfriday/v2 v2.1.0 // indirect
	github.com/segmentio/asm v1.1.3 // indirect
	github.com/segmentio/encoding v0.5.4 // indirect
	github.com/sergi/go-diff v1.3.2-0.20230802210424-5b0b94c5c0d3 // indirect
	github.com/skeema/knownhosts v1.3.1 // indirect
	github.com/spf13/pflag v1.0.10 // indirect
	github.com/u-root/u-root v0.16.0 // indirect
	github.com/xanzy/ssh-agent v0.3.3 // indirect
	github.com/xo/terminfo v0.0.0-20220910002029-abceb7e1c41e // indirect
	github.com/yosida95/uritemplate/v3 v3.0.2 // indirect
	go.uber.org/multierr v1.10.0 // indirect
	go.yaml.in/yaml/v3 v3.0.4 // indirect
	golang.org/x/net v0.54.0 // indirect
	golang.org/x/oauth2 v0.36.0 // indirect
	golang.org/x/text v0.37.0 // indirect
	gopkg.in/warnings.v0 v0.1.2 // indirect
)
