//go:build parked_engines

package codex

import (
	"path/filepath"

	"github.com/ctxloom/ctxloom/internal/paths"
)

// SessionHome is the per-session "virtual project dir" ctxloom points codex's
// home at for ONE session in workDir — <workDir>/.ctxloom/state/<harp>/home,
// from which cellScopedCodexHome derives the actual CODEX_HOME by appending
// ".codex" (ConfigDirName). The instance therefore lands at
// <workDir>/.ctxloom/state/<harp>/home/.codex, a sibling of claude's "claude"
// and kiro's "kiro" leaves under the same per-session root — the three are
// pairwise distinct, so one root hosts every engine a session runs.
//
// PER SESSION, not per project, and DISPOSABLE. Everything in it is either
// regenerated by ctxloom's managed-block writers, synthesized here (the
// config.toml tables and the `[projects."<abs WorkDir>"]` trust pre-seed), or
// one-way copied in from the real ~/.codex at instance time. The real ~/.codex
// stays the durable truth — codex keeps its per-project trust entries and its
// own accumulated state there — and ctxloom never writes it.
//
// WHO GETS ONE: only a run resolved through an agent binding whose EFFECTIVE
// config_home is "project". Every other in-tree run — no binding, an undeclared
// binding, an explicit `host` — uses the REAL ~/.codex directly, exactly like
// claude and kiro. codex read config_home for the first time in S5; before
// that it relocated CODEX_HOME unconditionally, which under a DISPOSABLE
// instance would have taken the human's own interactive codex state away every
// session. See operations.InTreeAgentHomeEnv, the one place that condition is
// decided for all three engines, and resolveCodexProjectDir for how the
// decision reaches this package (as an isolation-provided CODEX_HOME).
//
// codex's cwd-keyed surface, AGENTS.md, is untouched by this and stays at the
// project root where codex natively reads it.
//
// The error is harp validation (paths.SessionStatePath): a harpless caller
// cannot resolve an instance at all, which is what keeps the retired durable
// project home from quietly regrowing.
func SessionHome(workDir, harp string) (string, error) {
	return paths.SessionHomePath(filepath.Join(workDir, paths.AppDirName), harp)
}
