// Code generated by internal/agentcoord/mcpschema/gen. DO NOT EDIT.
//
// <ctxloom-reminder> frame encoders, generated from the (message_schema).xml_like and
// (xml_role) options in internal/agentcoord/*.proto. Regenerate with
// `just gen-mcp-schemas`.
//
// These are the ONLY place a frame is constructed. Hand-writing one elsewhere
// bypasses the escaping and the opt-in rendering rules the generator enforces
// at build time, so don't: add a message, annotate its fields, regenerate.

package agentcoord

import (
	"strconv"
	"strings"
)

// XmlLike renders x as its injected <ctxloom-reminder> frame.
func (x *MailPendingReminder) XmlLike() string {
	var b strings.Builder
	b.WriteString(`<ctxloom-reminder kind="mail-pending"`)
	xmlLikeAttr(&b, `count`, strconv.FormatUint(uint64(x.GetCount()), 10))
	b.WriteString(">")
	b.WriteString(`call agent_recv`)
	b.WriteString(`</ctxloom-reminder>`)
	return b.String()
}

// XmlLike renders x as its injected <ctxloom-reminder> frame.
func (x *PausedReminder) XmlLike() string {
	var b strings.Builder
	b.WriteString(`<ctxloom-reminder kind="paused"`)
	b.WriteString(">")
	b.WriteString(`this session is paused`)
	b.WriteString(`</ctxloom-reminder>`)
	return b.String()
}

// XmlLike renders x as its injected <ctxloom-reminder> frame.
func (x *QuestionPendingReminder) XmlLike() string {
	var b strings.Builder
	b.WriteString(`<ctxloom-reminder kind="question-pending"`)
	b.WriteString(">")
	b.WriteString(`call agent_recv`)
	b.WriteString(`</ctxloom-reminder>`)
	return b.String()
}

// XmlLike renders x as its injected <ctxloom-reminder> frame.
func (x *ResumedReminder) XmlLike() string {
	var b strings.Builder
	b.WriteString(`<ctxloom-reminder kind="resumed"`)
	b.WriteString(">")
	b.WriteString(`this session has resumed`)
	b.WriteString(`</ctxloom-reminder>`)
	return b.String()
}

// XmlLike renders x as its injected <ctxloom-reminder> frame.
func (x *SteerPendingReminder) XmlLike() string {
	var b strings.Builder
	b.WriteString(`<ctxloom-reminder kind="steer-pending"`)
	b.WriteString(">")
	b.WriteString(`call agent_recv`)
	b.WriteString(`</ctxloom-reminder>`)
	return b.String()
}

// xmlLikeAttr appends one escaped attribute. Only enums and short numeric
// scalars reach here (the generator refuses free text as an attribute), so the
// escaping is belt over braces — the guarantee lives in the CODE rather than in
// an argument about which values are safe.
func xmlLikeAttr(b *strings.Builder, name, value string) {
	b.WriteString(" ")
	b.WriteString(name)
	b.WriteString("=\"")
	b.WriteString(xmlLikeEscape(value))
	b.WriteString("\"")
}

// xmlLikeEscape neutralises every byte that could close, reopen, or forge a
// frame. It is deliberately blunt: this is presentation encoding for an LLM,
// not a standards-conformant XML serializer, and over-escaping costs nothing a
// model notices while under-escaping is a forged <ctxloom-reminder>.
func xmlLikeEscape(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch r {
		case '&':
			b.WriteString("&amp;")
		case '<':
			b.WriteString("&lt;")
		case '>':
			b.WriteString("&gt;")
		case '"':
			b.WriteString("&quot;")
		case '\'':
			b.WriteString("&#39;")
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}
