// Package tasks provides a per-project task store keyed by harp IDs
// (see github.com/ctxloom/ctxloom/internal/shared/harp). The source of truth is an append-only
// JSONL event log at ~/.ctxloom/tasks/<project-id>.jsonl (ADR 0025); current
// state is the fold of its events.
package tasks

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"sort"
	"strings"
	"time"

	"github.com/ctxloom/ctxloom/internal/shared/harp"
)

// Default status names. Hardcoded in v1; revisit if user-defined statuses
// become a real need.
const (
	StatusInProgress = "In Progress"
	StatusToDo       = "To Do"
	StatusDeferred   = "Deferred"
	StatusDone       = "Done"
	StatusArchived   = "Archived"
)

// StatusInfo describes one status for clients that render the taxonomy (status
// group headers, status pickers) instead of hardcoding it. `terminal` marks the
// completed statuses (Done/Archived); `requires_trigger` marks statuses that
// need a revive condition (Deferred), so a UI knows to prompt for one.
type StatusInfo struct {
	Name            string `json:"name"`
	Order           int    `json:"order"`
	Terminal        bool   `json:"terminal"`
	RequiresTrigger bool   `json:"requires_trigger"`
}

// statusTaxonomy is the canonical status set in display order, each entry
// carrying its own terminal / requires-trigger bits. It is the ONE place a
// status's name, position and meaning are declared: Statuses() publishes it,
// IsTerminalStatus answers from it, and the @-class expansion
// (ExpandStatusClasses) selects over it. Adding a status here is therefore
// the whole change — nothing downstream restates the set, its order, or which
// members are terminal.
//
// Order is deliberately NOT written here: Statuses() assigns it from the slice
// index, so display order and declaration order cannot drift apart.
var statusTaxonomy = []StatusInfo{
	{Name: StatusInProgress},
	{Name: StatusToDo},
	{Name: StatusDeferred, RequiresTrigger: true},
	{Name: StatusDone, Terminal: true},
	{Name: StatusArchived, Terminal: true},
}

// Statuses returns the canonical status taxonomy in display order — the single
// source of truth a client can read instead of baking in the status set, its
// order, or which statuses are terminal / need a trigger. The returned slice
// and its entries are copies; mutating them does not touch the taxonomy.
func Statuses() []StatusInfo {
	out := make([]StatusInfo, len(statusTaxonomy))
	for i, s := range statusTaxonomy {
		s.Order = i
		out[i] = s
	}
	return out
}

// errTriggerRequired is returned when a task is set Deferred without a trigger.
// A Deferred task is parked on a named wake-up condition (mirroring an ADR
// revive trigger), so the condition must be supplied.
var errTriggerRequired = errors.New("a Deferred task requires a non-empty trigger (the condition that should revive it)")

// validateStatusTrigger enforces the Deferred invariant: a task may only be
// Deferred when it carries a non-empty trigger. The store calls this before
// persisting an add or status change, so the CLI and MCP paths share one rule.
func validateStatusTrigger(status, trigger string) error {
	if status == StatusDeferred && strings.TrimSpace(trigger) == "" {
		return errTriggerRequired
	}
	return nil
}

// Task is one row in the store. The JSON tags are a cross-surface contract:
// `taskloom list --json` marshals Task directly and the taskloom MCP tools
// emit the same snake_case keys, so scripted consumers can treat both
// surfaces identically. (Persistence is unaffected — the JSONL log writes
// its own event struct, never Task.)
type Task struct {
	HarpID   string `json:"harp_id"`   // "swift-amber-falcon" — generated by shared/harp
	Text     string `json:"text"`      // trimmed, no harp ID inside
	Status   string `json:"status"`    // a statusTaxonomy name, or user-supplied
	Checked  bool   `json:"checked"`   // true when status is Done/Archived
	TextHash string `json:"text_hash"` // sha256(trimmed text), hex-encoded, first 12 chars

	// Trigger is the named wake-up condition for a Deferred task: a free-text
	// description of what should revive it, in the spirit of an ADR revive
	// trigger. Required when Status is Deferred; preserved across status
	// changes so a task re-deferred later keeps its condition unless a new one
	// is supplied. Empty for non-Deferred tasks that never carried one.
	Trigger string `json:"trigger,omitempty"`

	// OriginSession is the harp of the session that created the task, from the
	// `add` event; empty for tasks added outside a session.
	OriginSession string `json:"origin_session,omitempty"`

	// Tags is the task's current flat tag set, derived by folding add/tag/untag
	// events (never persisted as a snapshot). Always kept sorted for
	// deterministic output across `taskloom list --json` and MCP. Not part of
	// TextHash — tagging a task never changes its text identity.
	Tags []string `json:"tags,omitempty"`

	// CreatedAt is the task's creation timestamp — the `add` event's Ts, set
	// once at fold-time and never overwritten by a later event (a status/tag/
	// text change never touches it). internal/shared/tasks/priority reads it
	// to derive a task's age (now - CreatedAt) for decay_fn/priority_fn
	// evaluation. omitzero (not omitempty — time.Time isn't one of the types
	// omitempty recognizes) drops it from JSON only for the zero value, which
	// in practice means never once a task actually exists.
	CreatedAt time.Time `json:"created_at,omitzero"`

	// DerivedPriority is a task's rank-normalized [0,5] display priority (see
	// internal/shared/tasks/priority.Compute) — computed at READ time, never
	// persisted, and populated only when a caller actually asked for it
	// (`taskloom list --sort priority`, task_list's sort="priority"). nil
	// otherwise, so every other read path is byte-for-byte unaffected. A
	// pointer (not a bare float64) so a genuinely computed 0 is distinguishable
	// from "not computed".
	DerivedPriority *float64 `json:"derived_priority,omitempty"`
}

// Summary holds counts per status and the harp IDs currently in-progress.
type Summary struct {
	Counts     map[string]int `json:"counts"`
	InProgress []string       `json:"in_progress"`
}

// effectiveTrigger picks the trigger to persist on a status change: a non-empty
// new value wins, otherwise the task's existing trigger is preserved.
func effectiveTrigger(newTrigger, existing string) string {
	if t := strings.TrimSpace(newTrigger); t != "" {
		return t
	}
	return existing
}

// IsTerminalStatus reports whether status is one of the completed statuses
// (Done/Archived) — the same answer StatusInfo.Terminal carries in the
// taxonomy Statuses() publishes, in predicate form for callers that hold a
// status string rather than the taxonomy. It is exported because it is not
// derivable from the exported surface without re-deciding which statuses are
// terminal, which is how the read-time priority package came to carry a
// hand-maintained second copy of it.
//
// It reads statusTaxonomy rather than comparing against StatusDone/
// StatusArchived by hand, so a status's terminal bit is declared exactly once.
// A status not in the taxonomy at all (the store accepts user-supplied names)
// is not terminal: the taxonomy is what decides completion, and a name it has
// never heard of cannot claim it.
func IsTerminalStatus(status string) bool {
	for _, s := range statusTaxonomy {
		if s.Name == status {
			return s.Terminal
		}
	}
	return false
}

func hashText(s string) string {
	h := sha256.Sum256([]byte(strings.TrimSpace(s)))
	return hex.EncodeToString(h[:])[:12]
}

// uniqueHarpIDFromSet picks a fresh short harp id not already in `used`. Tasks
// use the two-word short harp (adj-noun): per-project task counts are small, so
// the smaller identity space is ample and the ids stay tidy in the list. 100
// attempts is overkill against the name space and a small set; the log backend's
// mint-with-check (and the fold-and-repair pass) cover the residual case.
func uniqueHarpIDFromSet(used map[string]struct{}) (string, error) {
	return harp.UniqueFrom(used, harp.GenerateShortName)
}

// normalizeTags trims, drops empties, dedupes, and sorts tags for
// deterministic storage and output. Applied on every write path (add/tag)
// and never trusted from raw event input.
func normalizeTags(tags []string) []string {
	if len(tags) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(tags))
	out := make([]string, 0, len(tags))
	for _, t := range tags {
		t = strings.TrimSpace(t)
		if t == "" {
			continue
		}
		if _, ok := seen[t]; ok {
			continue
		}
		seen[t] = struct{}{}
		out = append(out, t)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return nil
	}
	return out
}

// unionTags returns the normalized union of base and add — the fold rule for
// a `tag` event. Idempotent: unioning an already-present tag is a no-op.
func unionTags(base, add []string) []string {
	merged := make([]string, 0, len(base)+len(add))
	merged = append(merged, base...)
	merged = append(merged, add...)
	return normalizeTags(merged)
}

// subtractTags returns base with every tag in remove taken out — the fold
// rule for an `untag` event. Removing an absent tag is a no-op; base is
// assumed already normalized, so the result stays sorted.
func subtractTags(base, remove []string) []string {
	if len(base) == 0 || len(remove) == 0 {
		return base
	}
	removeSet := make(map[string]struct{}, len(remove))
	for _, t := range remove {
		removeSet[strings.TrimSpace(t)] = struct{}{}
	}
	out := make([]string, 0, len(base))
	for _, t := range base {
		if _, drop := removeSet[t]; drop {
			continue
		}
		out = append(out, t)
	}
	if len(out) == 0 {
		return nil
	}
	return out
}
