// Package tasks provides a per-project task store keyed by harp IDs
// (see github.com/ctxloom/ctxloom/internal/shared/harp). The source of truth is an append-only
// JSONL event log at ~/.ctxloom/tasks/<project-id>.jsonl (ADR 0025); current
// state is the fold of its events.
package tasks

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/ctxloom/ctxloom/internal/shared/harp"
	"github.com/ctxloom/ctxloom/pkg/tagquery"
)

// Default status names. Hardcoded in v1; revisit if user-defined statuses
// become a real need.
const (
	StatusInProgress = "In Progress"
	StatusToDo       = "To Do"
	StatusDeferred   = "Deferred"
	StatusDone       = "Done"
	StatusArchived   = "Archived"
)

// DefaultStatusOrder is the canonical status ordering for display.
var DefaultStatusOrder = []string{StatusInProgress, StatusToDo, StatusDeferred, StatusDone, StatusArchived}

// StatusInfo describes one status for clients that render the taxonomy (status
// group headers, status pickers) instead of hardcoding it. `terminal` marks the
// completed statuses (Done/Archived); `requires_trigger` marks statuses that
// need a revive condition (Deferred), so a UI knows to prompt for one.
type StatusInfo struct {
	Name            string `json:"name"`
	Order           int    `json:"order"`
	Terminal        bool   `json:"terminal"`
	RequiresTrigger bool   `json:"requires_trigger"`
}

// Statuses returns the canonical status taxonomy in display order — the single
// source of truth a client can read instead of baking in the status set, its
// order, or which statuses are terminal / need a trigger.
func Statuses() []StatusInfo {
	out := make([]StatusInfo, len(DefaultStatusOrder))
	for i, name := range DefaultStatusOrder {
		out[i] = StatusInfo{
			Name:            name,
			Order:           i,
			Terminal:        statusIsDone(name),
			RequiresTrigger: name == StatusDeferred,
		}
	}
	return out
}

// ErrTriggerRequired is returned when a task is set Deferred without a trigger.
// A Deferred task is parked on a named wake-up condition (mirroring an ADR
// revive trigger), so the condition must be supplied.
var ErrTriggerRequired = errors.New("a Deferred task requires a non-empty trigger (the condition that should revive it)")

// ValidateStatusTrigger enforces the Deferred invariant: a task may only be
// Deferred when it carries a non-empty trigger. The store calls this before
// persisting an add or status change, so the CLI and MCP paths share one rule.
func ValidateStatusTrigger(status, trigger string) error {
	if status == StatusDeferred && strings.TrimSpace(trigger) == "" {
		return ErrTriggerRequired
	}
	return nil
}

// Task is one row in the store. The JSON tags are a cross-surface contract:
// `taskloom list --json` marshals Task directly and the taskloom MCP tools
// emit the same snake_case keys, so scripted consumers can treat both
// surfaces identically. (Persistence is unaffected — the JSONL log writes
// its own event struct, never Task.)
type Task struct {
	HarpID   string `json:"harp_id"`   // "swift-amber-falcon" — generated by shared/harp
	Text     string `json:"text"`      // trimmed, no harp ID inside
	Status   string `json:"status"`    // one of DefaultStatusOrder or user-supplied
	Checked  bool   `json:"checked"`   // true when status is Done/Archived
	TextHash string `json:"text_hash"` // sha256(trimmed text), hex-encoded, first 12 chars

	// Trigger is the named wake-up condition for a Deferred task: a free-text
	// description of what should revive it, in the spirit of an ADR revive
	// trigger. Required when Status is Deferred; preserved across status
	// changes so a task re-deferred later keeps its condition unless a new one
	// is supplied. Empty for non-Deferred tasks that never carried one.
	Trigger string `json:"trigger,omitempty"`

	// OriginSession is the harp of the session that created the task, from the
	// `add` event; empty for tasks added outside a session.
	OriginSession string `json:"origin_session,omitempty"`

	// Tags is the task's current flat tag set, derived by folding add/tag/untag
	// events (never persisted as a snapshot). Always kept sorted for
	// deterministic output across `taskloom list --json` and MCP. Not part of
	// TextHash — tagging a task never changes its text identity.
	Tags []string `json:"tags,omitempty"`
}

// Summary holds counts per status and the harp IDs currently in-progress.
type Summary struct {
	Counts     map[string]int `json:"counts"`
	InProgress []string       `json:"in_progress"`
}

// effectiveTrigger picks the trigger to persist on a status change: a non-empty
// new value wins, otherwise the task's existing trigger is preserved.
func effectiveTrigger(newTrigger, existing string) string {
	if t := strings.TrimSpace(newTrigger); t != "" {
		return t
	}
	return existing
}

func statusIsDone(status string) bool {
	return status == StatusDone || status == StatusArchived
}

func hashText(s string) string {
	h := sha256.Sum256([]byte(strings.TrimSpace(s)))
	return hex.EncodeToString(h[:])[:12]
}

// uniqueHarpIDFromSet picks a fresh short harp id not already in `used`. Tasks
// use the two-word short harp (adj-noun): per-project task counts are small, so
// the smaller identity space is ample and the ids stay tidy in the list. 100
// attempts is overkill against the name space and a small set; the log backend's
// mint-with-check (and the fold-and-repair pass) cover the residual case.
func uniqueHarpIDFromSet(used map[string]struct{}) string {
	return harp.UniqueFrom(used, harp.GenerateShortName)
}

// filterTasks applies status/term/tag-query filters to a task list. An empty
// tagQuery applies no tag filter; a non-empty one is parsed once (via
// pkg/tagquery) and evaluated per task. A malformed tagQuery is returned as
// an error — never silently degraded to an empty or unfiltered result (see
// CLAUDE.md fail-loud philosophy).
func filterTasks(all []Task, statuses []string, term, tagQuery string) ([]Task, error) {
	var statusSet map[string]bool
	if len(statuses) > 0 {
		statusSet = make(map[string]bool, len(statuses))
		for _, s := range statuses {
			statusSet[s] = true
		}
	}
	var expr *tagquery.Expr
	if strings.TrimSpace(tagQuery) != "" {
		e, err := tagquery.Parse(tagQuery)
		if err != nil {
			return nil, fmt.Errorf("tag query %q: %w", tagQuery, err)
		}
		expr = &e
	}
	termLower := strings.ToLower(strings.TrimSpace(term))
	out := make([]Task, 0, len(all))
	for _, t := range all {
		if statusSet != nil && !statusSet[t.Status] {
			continue
		}
		if termLower != "" && !strings.Contains(strings.ToLower(t.Text), termLower) {
			continue
		}
		if expr != nil && !expr.Matches(taskHasTag(t)) {
			continue
		}
		out = append(out, t)
	}
	return out, nil
}

// taskHasTag returns a tagquery-shaped "has this tag" predicate for t. Tags
// are always stored sorted+deduped, so a linear scan is ample for the small
// per-task tag sets this system expects.
func taskHasTag(t Task) func(tag string) bool {
	return func(tag string) bool {
		for _, has := range t.Tags {
			if has == tag {
				return true
			}
		}
		return false
	}
}

// normalizeTags trims, drops empties, dedupes, and sorts tags for
// deterministic storage and output. Applied on every write path (add/tag)
// and never trusted from raw event input.
func normalizeTags(tags []string) []string {
	if len(tags) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(tags))
	out := make([]string, 0, len(tags))
	for _, t := range tags {
		t = strings.TrimSpace(t)
		if t == "" {
			continue
		}
		if _, ok := seen[t]; ok {
			continue
		}
		seen[t] = struct{}{}
		out = append(out, t)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return nil
	}
	return out
}

// unionTags returns the normalized union of base and add — the fold rule for
// a `tag` event. Idempotent: unioning an already-present tag is a no-op.
func unionTags(base, add []string) []string {
	merged := make([]string, 0, len(base)+len(add))
	merged = append(merged, base...)
	merged = append(merged, add...)
	return normalizeTags(merged)
}

// subtractTags returns base with every tag in remove taken out — the fold
// rule for an `untag` event. Removing an absent tag is a no-op; base is
// assumed already normalized, so the result stays sorted.
func subtractTags(base, remove []string) []string {
	if len(base) == 0 || len(remove) == 0 {
		return base
	}
	removeSet := make(map[string]struct{}, len(remove))
	for _, t := range remove {
		removeSet[strings.TrimSpace(t)] = struct{}{}
	}
	out := make([]string, 0, len(base))
	for _, t := range base {
		if _, drop := removeSet[t]; drop {
			continue
		}
		out = append(out, t)
	}
	if len(out) == 0 {
		return nil
	}
	return out
}
