// Package tasks provides a per-project task store keyed by harp IDs
// (see github.com/ctxloom/ctxloom/internal/shared/harp). The source of truth is an append-only
// JSONL event log at ~/.ctxloom/tasks/<project-id>.jsonl (ADR 0025); current
// state is the fold of its events.
package tasks

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"sort"
	"strings"

	tagma "github.com/benjaminabbitt/tagma/ports/go"
	"github.com/ctxloom/ctxloom/internal/shared/harp"
)

// Default status names. Hardcoded in v1; revisit if user-defined statuses
// become a real need.
const (
	StatusInProgress = "In Progress"
	StatusToDo       = "To Do"
	StatusDeferred   = "Deferred"
	StatusDone       = "Done"
	StatusArchived   = "Archived"
)

// DefaultStatusOrder is the canonical status ordering for display.
var DefaultStatusOrder = []string{StatusInProgress, StatusToDo, StatusDeferred, StatusDone, StatusArchived}

// StatusInfo describes one status for clients that render the taxonomy (status
// group headers, status pickers) instead of hardcoding it. `terminal` marks the
// completed statuses (Done/Archived); `requires_trigger` marks statuses that
// need a revive condition (Deferred), so a UI knows to prompt for one.
type StatusInfo struct {
	Name            string `json:"name"`
	Order           int    `json:"order"`
	Terminal        bool   `json:"terminal"`
	RequiresTrigger bool   `json:"requires_trigger"`
}

// Statuses returns the canonical status taxonomy in display order — the single
// source of truth a client can read instead of baking in the status set, its
// order, or which statuses are terminal / need a trigger.
func Statuses() []StatusInfo {
	out := make([]StatusInfo, len(DefaultStatusOrder))
	for i, name := range DefaultStatusOrder {
		out[i] = StatusInfo{
			Name:            name,
			Order:           i,
			Terminal:        statusIsDone(name),
			RequiresTrigger: name == StatusDeferred,
		}
	}
	return out
}

// ErrTriggerRequired is returned when a task is set Deferred without a trigger.
// A Deferred task is parked on a named wake-up condition (mirroring an ADR
// revive trigger), so the condition must be supplied.
var ErrTriggerRequired = errors.New("a Deferred task requires a non-empty trigger (the condition that should revive it)")

// ValidateStatusTrigger enforces the Deferred invariant: a task may only be
// Deferred when it carries a non-empty trigger. The store calls this before
// persisting an add or status change, so the CLI and MCP paths share one rule.
func ValidateStatusTrigger(status, trigger string) error {
	if status == StatusDeferred && strings.TrimSpace(trigger) == "" {
		return ErrTriggerRequired
	}
	return nil
}

// Task is one row in the store. The JSON tags are a cross-surface contract:
// `taskloom list --json` marshals Task directly and the taskloom MCP tools
// emit the same snake_case keys, so scripted consumers can treat both
// surfaces identically. (Persistence is unaffected — the JSONL log writes
// its own event struct, never Task.)
type Task struct {
	HarpID   string `json:"harp_id"`   // "swift-amber-falcon" — generated by shared/harp
	Text     string `json:"text"`      // trimmed, no harp ID inside
	Status   string `json:"status"`    // one of DefaultStatusOrder or user-supplied
	Checked  bool   `json:"checked"`   // true when status is Done/Archived
	TextHash string `json:"text_hash"` // sha256(trimmed text), hex-encoded, first 12 chars

	// Trigger is the named wake-up condition for a Deferred task: a free-text
	// description of what should revive it, in the spirit of an ADR revive
	// trigger. Required when Status is Deferred; preserved across status
	// changes so a task re-deferred later keeps its condition unless a new one
	// is supplied. Empty for non-Deferred tasks that never carried one.
	Trigger string `json:"trigger,omitempty"`

	// OriginSession is the harp of the session that created the task, from the
	// `add` event; empty for tasks added outside a session.
	OriginSession string `json:"origin_session,omitempty"`

	// Tags is the task's current flat tag set, derived by folding add/tag/untag
	// events (never persisted as a snapshot). Always kept sorted for
	// deterministic output across `taskloom list --json` and MCP. Not part of
	// TextHash — tagging a task never changes its text identity.
	Tags []string `json:"tags,omitempty"`
}

// Summary holds counts per status and the harp IDs currently in-progress.
type Summary struct {
	Counts     map[string]int `json:"counts"`
	InProgress []string       `json:"in_progress"`
}

// effectiveTrigger picks the trigger to persist on a status change: a non-empty
// new value wins, otherwise the task's existing trigger is preserved.
func effectiveTrigger(newTrigger, existing string) string {
	if t := strings.TrimSpace(newTrigger); t != "" {
		return t
	}
	return existing
}

func statusIsDone(status string) bool {
	return status == StatusDone || status == StatusArchived
}

func hashText(s string) string {
	h := sha256.Sum256([]byte(strings.TrimSpace(s)))
	return hex.EncodeToString(h[:])[:12]
}

// uniqueHarpIDFromSet picks a fresh short harp id not already in `used`. Tasks
// use the two-word short harp (adj-noun): per-project task counts are small, so
// the smaller identity space is ample and the ids stay tidy in the list. 100
// attempts is overkill against the name space and a small set; the log backend's
// mint-with-check (and the fold-and-repair pass) cover the residual case.
func uniqueHarpIDFromSet(used map[string]struct{}) string {
	return harp.UniqueFrom(used, harp.GenerateShortName)
}

// ErrTagQuery marks an error as originating from a malformed --tag-query
// (tagma's Compile/QueryPostfix), letting a caller distinguish "the query
// itself is bad" from an unrelated failure (store I/O, project resolution)
// without depending on tagma's own error shape — tagma reports a parse
// failure as a plain error, not a distinct type, unlike the retired
// pkg/tagquery.ParseError. cmd/taskloom's wrapTagQueryError uses this via
// errors.Is to decide whether to append its postfix-grammar usage hint.
var ErrTagQuery = errors.New("tag query")

// filterTasks applies status/term/tag-query filters to a task list. An empty
// tagQuery applies no tag filter — the tagma index is never even built in
// that case. A non-empty tagQuery is evaluated by building a *tagma.Index
// over the CANDIDATES that already passed the status/term filter (not the
// full task list) and running QueryPostfix against it once. A malformed
// tagQuery is returned as an error — never silently degraded to an empty or
// unfiltered result (see CLAUDE.md fail-loud philosophy).
//
// Scoping the index to the status/term-passing candidates — rather than
// building it over every task — matters specifically for `not`: tagma's
// "not" complements over the index's *participating* universe (every item
// that was given at least one query-visible tag via AddItem), not over some
// wider notion of "everything". Building the index over all tasks would let
// `not urgent` return every task minus the urgent ones, including tasks a
// status/term filter should have excluded. Scoping to candidates first
// makes `not urgent` mean exactly what the old per-task
// Expr.Matches(taskHasTag(t)) loop meant: "true for every candidate that
// doesn't carry the urgent tag".
func filterTasks(all []Task, statuses []string, term, tagQuery string) ([]Task, error) {
	var statusSet map[string]bool
	if len(statuses) > 0 {
		statusSet = make(map[string]bool, len(statuses))
		for _, s := range statuses {
			statusSet[s] = true
		}
	}
	termLower := strings.ToLower(strings.TrimSpace(term))

	candidates := make([]Task, 0, len(all))
	for _, t := range all {
		if statusSet != nil && !statusSet[t.Status] {
			continue
		}
		if termLower != "" && !strings.Contains(strings.ToLower(t.Text), termLower) {
			continue
		}
		candidates = append(candidates, t)
	}

	if strings.TrimSpace(tagQuery) == "" {
		return candidates, nil
	}

	idx := tagma.NewIndex()
	for _, t := range candidates {
		// AddItem only records an id in the index if it's given at least one
		// tag — an item that never appears in idx.items doesn't participate
		// in the universe QueryPostfix's `not` complements against (see
		// tagma's Index.participatingIDs). A candidate with zero (or zero
		// still-parseable, see tagsToTagmaTags) real tags would then be
		// silently dropped from `not X` results even though the old engine
		// included it (an untagged task has no tag named X, so `not X`
		// matched it). presenceTag guarantees every candidate always
		// contributes at least one tag, so every candidate always
		// participates — matching the old per-task semantics exactly. Its
		// reserved namespace never collides with a real bare-token tag (a
		// bare tag always parses with a nil namespace), so it can never
		// match a real query atom.
		idx.AddItem(t.HarpID, append(tagsToTagmaTags(t.Tags), presenceTag()))
	}
	ids, err := idx.QueryPostfix(tagQuery)
	if err != nil {
		return nil, fmt.Errorf("%w %q: %w", ErrTagQuery, tagQuery, err)
	}
	matched := make(map[string]struct{}, len(ids))
	for _, id := range ids {
		matched[id] = struct{}{}
	}

	// Preserve input order: today's per-task loop appends in candidate
	// order, so iterate candidates and keep the ones tagma matched, rather
	// than trusting QueryPostfix's (sorted-by-id) return order.
	out := make([]Task, 0, len(candidates))
	for _, t := range candidates {
		if _, ok := matched[t.HarpID]; ok {
			out = append(out, t)
		}
	}
	return out, nil
}

// presenceNamespace is a reserved tagma namespace used only by
// presenceTag, never by a real stored tag: every stored tag comes from
// normalizeTags/ValidateTag, which only ever accept plain bare tokens —
// tagma.ParseTag on a bare token always yields a nil Namespace, so a tag
// carrying this (or any) explicit namespace can never collide with one a
// user wrote.
const presenceNamespace = "taskloom.internal"

// presenceTag is an inert marker tag added alongside every candidate's real
// tags in filterTasks — see that function's doc for why. It never matches
// a real query atom: taskloom's tag queries are always plain bare tokens
// (see this package's own tests), and a bare query atom only matches tags
// with a nil namespace (tagma's nsMatches), never a namespaced one like
// this.
func presenceTag() tagma.Tag {
	ns := presenceNamespace
	return tagma.Tag{Namespace: &ns, Key: "candidate"}
}

// tagsToTagmaTags converts a task's stored flat tag strings into tagma.Tag
// values for indexing. Stored tags are always plain bare tokens under
// today's write-time guard (see operations.validateTag), but the reader
// stays lenient: an existing log may still carry a tag written before that
// guard existed, so a tag that fails tagma.ParseTag here is skipped rather
// than failing the whole query — mirroring the old engine, whose
// taskHasTag predicate was a plain string scan that never errored on tag
// shape either.
func tagsToTagmaTags(tags []string) []tagma.Tag {
	out := make([]tagma.Tag, 0, len(tags))
	for _, s := range tags {
		tag, err := tagma.ParseTag(s)
		if err != nil {
			continue
		}
		out = append(out, tag)
	}
	return out
}

// normalizeTags trims, drops empties, dedupes, and sorts tags for
// deterministic storage and output. Applied on every write path (add/tag)
// and never trusted from raw event input.
func normalizeTags(tags []string) []string {
	if len(tags) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(tags))
	out := make([]string, 0, len(tags))
	for _, t := range tags {
		t = strings.TrimSpace(t)
		if t == "" {
			continue
		}
		if _, ok := seen[t]; ok {
			continue
		}
		seen[t] = struct{}{}
		out = append(out, t)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return nil
	}
	return out
}

// unionTags returns the normalized union of base and add — the fold rule for
// a `tag` event. Idempotent: unioning an already-present tag is a no-op.
func unionTags(base, add []string) []string {
	merged := make([]string, 0, len(base)+len(add))
	merged = append(merged, base...)
	merged = append(merged, add...)
	return normalizeTags(merged)
}

// subtractTags returns base with every tag in remove taken out — the fold
// rule for an `untag` event. Removing an absent tag is a no-op; base is
// assumed already normalized, so the result stays sorted.
func subtractTags(base, remove []string) []string {
	if len(base) == 0 || len(remove) == 0 {
		return base
	}
	removeSet := make(map[string]struct{}, len(remove))
	for _, t := range remove {
		removeSet[strings.TrimSpace(t)] = struct{}{}
	}
	out := make([]string, 0, len(base))
	for _, t := range base {
		if _, drop := removeSet[t]; drop {
			continue
		}
		out = append(out, t)
	}
	if len(out) == 0 {
		return nil
	}
	return out
}
