package docsgen

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

type gadgetInput struct {
	Name   string   `json:"name" jsonschema:"The gadget to poke."`
	Levels []string `json:"levels,omitempty" jsonschema:"Poke levels."`
}

// docServer builds a tiny MCP surface: one tool, no resources, no templates —
// deliberately narrower than taskloom's real server (which does register
// resources, see cmd/taskloom/mcp_resources.go), so GenMCPTools's "omit an
// empty section" behavior stays covered by this fixture staying resource-less.
func docServer(t *testing.T) *mcp.Server {
	t.Helper()
	s := mcp.NewServer(&mcp.Implementation{Name: "widget"}, nil)
	mcp.AddTool(s,
		&mcp.Tool{Name: "gadget_poke", Description: "Poke a gadget."},
		func(_ context.Context, _ *mcp.CallToolRequest, _ gadgetInput) (*mcp.CallToolResult, any, error) {
			return nil, nil, nil
		})
	return s
}

func TestGenMCPTools(t *testing.T) {
	dir := t.TempDir()
	p := fakeProduct()
	p.MCPServer = docServer(t)
	p.MCPSource = "cmd/widget/mcp_tools.go"
	p.MCPCommand = "widget mcp"
	p.MCPIntro = "Widget tools for agents."

	if err := GenMCPTools(context.Background(), p, dir); err != nil {
		t.Fatalf("GenMCPTools: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "mcp-tools.md"))
	if err != nil {
		t.Fatalf("expected mcp-tools.md: %v", err)
	}
	page := string(data)

	for _, want := range []string{
		`title: "MCP Tools Reference"`,
		"GENERATED by `just gen-docs`",
		"cmd/widget/mcp_tools.go",
		"`widget mcp`",
		"Widget tools for agents.",
		"### gadget_poke",
		"Poke a gadget.",
		// Parameter table derived from the reflected input schema, not hand-copied.
		"| `name` | string | Yes | The gadget to poke. |",
		"| `levels` | string[] | No | Poke levels. |",
	} {
		if !strings.Contains(page, want) {
			t.Errorf("mcp-tools.md missing %q:\n%s", want, page)
		}
	}

	// A server with no resources or resource templates must not emit empty
	// sections — the page would advertise a surface that does not exist.
	for _, unwanted := range []string{"## Resources", "## Resource Templates"} {
		if strings.Contains(page, unwanted) {
			t.Errorf("mcp-tools.md emitted %q for a server with none:\n%s", unwanted, page)
		}
	}
}

// U051-F04: enumerateMCPSurface must not silently truncate a surface larger
// than one listing page. Force a two-tool server to paginate with PageSize:1
// (well below the SDK's default of 1000) and confirm both tools reach the
// generated page, not just the first page's worth.
func TestGenMCPTools_PaginatesBeyondOnePage(t *testing.T) {
	s := mcp.NewServer(&mcp.Implementation{Name: "widget"}, &mcp.ServerOptions{PageSize: 1})
	mcp.AddTool(s,
		&mcp.Tool{Name: "gadget_alpha", Description: "First gadget."},
		func(_ context.Context, _ *mcp.CallToolRequest, _ gadgetInput) (*mcp.CallToolResult, any, error) {
			return nil, nil, nil
		})
	mcp.AddTool(s,
		&mcp.Tool{Name: "gadget_zeta", Description: "Second gadget."},
		func(_ context.Context, _ *mcp.CallToolRequest, _ gadgetInput) (*mcp.CallToolResult, any, error) {
			return nil, nil, nil
		})

	p := fakeProduct()
	p.MCPServer = s
	p.MCPSource = "cmd/widget/mcp_tools.go"
	p.MCPCommand = "widget mcp"

	dir := t.TempDir()
	if err := GenMCPTools(context.Background(), p, dir); err != nil {
		t.Fatalf("GenMCPTools: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "mcp-tools.md"))
	if err != nil {
		t.Fatalf("expected mcp-tools.md: %v", err)
	}
	page := string(data)

	for _, want := range []string{"### gadget_alpha", "### gadget_zeta"} {
		if !strings.Contains(page, want) {
			t.Errorf("mcp-tools.md missing %q (page size 1 must not truncate the tool listing):\n%s", want, page)
		}
	}
}

// TestGenMCPToolsRequiresServer: asking for an MCP page from a product that has
// no MCP surface (ltk) is a generator misconfiguration, not a silent no-op.
func TestGenMCPToolsRequiresServer(t *testing.T) {
	p := fakeProduct()
	if err := GenMCPTools(context.Background(), p, t.TempDir()); err == nil {
		t.Fatal("expected an error generating an MCP page for a product with no MCP server")
	}
}

// U051-F11: propertyDescription surfaces p.Enum but never p.Items.Enum, so an
// array parameter whose ITEMS are enum-constrained documents no allowed
// values at all.
func TestPropertyDescription_SurfacesItemsEnum(t *testing.T) {
	p := mcpToolProperty{
		Type:        []any{"array"},
		Description: "Levels to poke at.",
		Items: &mcpToolProperty{
			Type: "string",
			Enum: []any{"low", "medium", "high"},
		},
	}
	got := propertyDescription(p)
	for _, want := range []string{"low", "medium", "high"} {
		if !strings.Contains(got, want) {
			t.Errorf("propertyDescription(%+v) = %q, missing items enum value %q", p, got, want)
		}
	}
}

// U051-F10: mcpFrontmatter interpolates p.MCPSource/p.MCPCommand unguarded,
// so an unset field used to render a banner like "as served by ``" instead of
// signalling the misconfiguration. Require both non-empty before generating.
func TestGenMCPTools_RequiresSourceAndCommand(t *testing.T) {
	for _, tc := range []struct {
		name       string
		mcpSource  string
		mcpCommand string
	}{
		{"missing MCPSource", "", "widget mcp"},
		{"missing MCPCommand", "cmd/widget/mcp_tools.go", ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := fakeProduct()
			p.MCPServer = docServer(t)
			p.MCPSource = tc.mcpSource
			p.MCPCommand = tc.mcpCommand

			if err := GenMCPTools(context.Background(), p, t.TempDir()); err == nil {
				t.Fatal("expected an error generating an MCP page with an empty MCPSource/MCPCommand")
			}
		})
	}
}

// U051-F02(a): a server with zero registered tools used to still write a
// page with an empty "## Tools" section and return nil -- the same
// misconfiguration TestGenMCPToolsRequiresServer already treats as fatal for
// a nil server, but not for an empty one.
func TestGenMCPTools_ZeroToolsFailsLoud(t *testing.T) {
	s := mcp.NewServer(&mcp.Implementation{Name: "empty"}, nil)
	p := fakeProduct()
	p.MCPServer = s

	dir := t.TempDir()
	if err := GenMCPTools(context.Background(), p, dir); err == nil {
		t.Fatal("expected an error generating an MCP page for a server with no registered tools")
	}
	if _, err := os.Stat(filepath.Join(dir, "mcp-tools.md")); err == nil {
		t.Error("a refused generation must not leave a toolless page behind")
	}
}

// U051-F02(b): decodeToolSchema used to swallow a schema it could not decode
// and return a zero mcpToolSchema, which writeMCPTool then rendered as
// "_No parameters._" -- identical to a genuinely parameterless tool. Register
// a tool via the SDK's low-level (non-generic) AddTool with a raw
// InputSchema whose top level satisfies the SDK's own "type: object" check
// (so registration itself does not panic) but whose "properties" entry is a
// shape mcpToolSchema/mcpToolProperty cannot unmarshal -- a bare string
// where an object is expected -- and prove the page generation now fails
// instead of publishing "no parameters" for a tool that plainly has one.
func TestGenMCPTools_UndecodableInputSchemaFailsLoud(t *testing.T) {
	s := mcp.NewServer(&mcp.Implementation{Name: "widget"}, nil)
	s.AddTool(&mcp.Tool{
		Name:        "gadget_poke",
		Description: "Poke a gadget.",
		InputSchema: map[string]any{
			"type":       "object",
			"properties": map[string]any{"name": "not an object"},
		},
	}, func(_ context.Context, _ *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return nil, nil
	})

	p := fakeProduct()
	p.MCPServer = s

	dir := t.TempDir()
	if err := GenMCPTools(context.Background(), p, dir); err == nil {
		t.Fatal("expected an error when a tool's input schema cannot be decoded")
	}
}
