package operations

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/spf13/afero"

	"github.com/ctxloom/ctxloom/internal/bundles"
	"github.com/ctxloom/ctxloom/internal/config"
	"github.com/ctxloom/ctxloom/internal/remote"
)

// parsePullToken parses a pull token in the format "itemType:remote/path@sha".
// Pull tokens are generated by FetchRemoteContent and used by confirm_pull.
// The format is different from standard references - the itemType prefix
// must be stripped to avoid creating directories like "bundle:personal".
func parsePullToken(token string) (itemType, ref, sha string, err error) {
	if token == "" {
		return "", "", "", fmt.Errorf("empty pull token")
	}

	// Find the type prefix (e.g., "bundle:" or "profile:")
	colonIdx := strings.Index(token, ":")
	if colonIdx == -1 {
		return "", "", "", fmt.Errorf("invalid pull token format: missing type prefix (expected 'bundle:' or 'profile:')")
	}

	itemType = token[:colonIdx]
	if itemType != "bundle" && itemType != "profile" {
		return "", "", "", fmt.Errorf("invalid pull token type: %s", itemType)
	}

	// Remainder is "remote/path@sha"
	remainder := token[colonIdx+1:]

	// Find the SHA suffix
	atIdx := strings.LastIndex(remainder, "@")
	if atIdx == -1 {
		return "", "", "", fmt.Errorf("invalid pull token format: missing @sha suffix")
	}

	ref = remainder[:atIdx]
	sha = remainder[atIdx+1:]

	if ref == "" {
		return "", "", "", fmt.Errorf("invalid pull token: empty reference")
	}
	if sha == "" {
		return "", "", "", fmt.Errorf("invalid pull token: empty sha")
	}

	return itemType, ref, sha, nil
}

// FetchRemoteContentRequest contains parameters for fetching remote content.
type FetchRemoteContentRequest struct {
	Reference string `json:"reference"`
	ItemType  string `json:"item_type"` // "bundle" or "profile"

	// Registry is an optional pre-configured registry (for testing).
	Registry *remote.Registry `json:"-"`
	// Fetcher is an optional pre-configured fetcher (for testing).
	Fetcher remote.Fetcher `json:"-"`
}

// FetchRemoteContentResult contains the fetched content.
type FetchRemoteContentResult struct {
	Reference  string `json:"reference"`
	ItemType   string `json:"item_type"`
	SHA        string `json:"sha"`
	FullSHA    string `json:"full_sha"`
	SourceURL  string `json:"source_url"`
	FilePath   string `json:"file_path"`
	Content    string `json:"content"`
	PullToken  string `json:"pull_token"`
	Warning    string `json:"warning"`
	RemoteName string `json:"-"` // Internal use
}

// parseRemoteItemType maps the request item_type string to a remote.ItemType,
// accepting only "bundle" and "profile".
func parseRemoteItemType(s string) (remote.ItemType, error) {
	switch s {
	case "bundle":
		return remote.ItemTypeBundle, nil
	case "profile":
		return remote.ItemTypeProfile, nil
	}
	return "", fmt.Errorf("invalid item_type: %s (only bundle and profile supported)", s)
}

// resolveContentSHA resolves a content version to a commit SHA, defaulting to
// the repo's default branch when no version is pinned.
func resolveContentSHA(ctx context.Context, fetcher remote.Fetcher, owner, repo, contentVersion string) (string, error) {
	if contentVersion == "" {
		var err error
		contentVersion, err = fetcher.GetDefaultBranch(ctx, owner, repo)
		if err != nil {
			return "", fmt.Errorf("failed to get default branch: %w", err)
		}
	}
	sha, err := fetcher.ResolveRef(ctx, owner, repo, contentVersion)
	if err != nil {
		return "", fmt.Errorf("failed to resolve ref '%s': %w", contentVersion, err)
	}
	return sha, nil
}

// FetchRemoteContent fetches content from a remote for preview.
// This is used by the MCP preview_remote tool.
func FetchRemoteContent(ctx context.Context, cfg *config.Config, req FetchRemoteContentRequest) (*FetchRemoteContentResult, error) {
	if req.Reference == "" {
		return nil, fmt.Errorf("reference is required")
	}
	if req.ItemType == "" {
		return nil, fmt.Errorf("item_type is required")
	}

	itemType, err := parseRemoteItemType(req.ItemType)
	if err != nil {
		return nil, err
	}

	ref, err := remote.ParseReference(req.Reference)
	if err != nil {
		return nil, fmt.Errorf("invalid reference: %w", err)
	}

	registry, err := resolveRegistry(cfg, req.Registry)
	if err != nil {
		return nil, err
	}

	rem, err := registry.Get(ref.Remote)
	if err != nil {
		return nil, err
	}

	fetcher, owner, repo, err := resolveBrowseFetcher(cfg, rem, req.Fetcher)
	if err != nil {
		return nil, err
	}

	sha, err := resolveContentSHA(ctx, fetcher, owner, repo, ref.ContentVersion)
	if err != nil {
		return nil, err
	}

	// Fetch content
	filePath := ref.BuildFilePath(itemType)
	content, err := fetcher.FetchFile(ctx, owner, repo, filePath, sha)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch: %w", err)
	}

	// Generate pull token (item_type:reference@SHA for re-fetch capability)
	pullToken := fmt.Sprintf("%s:%s/%s@%s", req.ItemType, ref.Remote, ref.Path, sha)

	return &FetchRemoteContentResult{
		Reference:  req.Reference,
		ItemType:   req.ItemType,
		SHA:        shortSHA(sha),
		FullSHA:    sha,
		SourceURL:  rem.URL,
		FilePath:   filePath,
		Content:    string(content),
		PullToken:  pullToken,
		Warning:    "REVIEW THIS CONTENT CAREFULLY. Malicious prompts can override AI safety guidelines, exfiltrate data, or execute unintended actions. Use confirm_pull with the pull_token to install.",
		RemoteName: ref.Remote,
	}, nil
}

// WriteRemoteItemRequest contains parameters for writing a fetched item.
type WriteRemoteItemRequest struct {
	Reference string   `json:"reference"` // The pull token reference
	ItemType  string   `json:"item_type"`
	Content   []byte   `json:"-"`
	SHA       string   `json:"sha"`
	FS        afero.Fs `json:"-"` // Optional filesystem (defaults to OS filesystem if nil)
}

// WriteRemoteItemResult contains the result of writing an item.
type WriteRemoteItemResult struct {
	Status      string `json:"status"` // "installed" or "updated"
	Reference   string `json:"reference"`
	ItemType    string `json:"item_type"`
	LocalPath   string `json:"local_path"`
	SHA         string `json:"sha"`
	Overwritten bool   `json:"overwritten"`
}

// cleanPullTokenRef unwraps a "bundle:remote/path@sha" / "profile:…" pull token
// (returned by FetchRemoteContent) to its clean reference. Tokens must be
// parsed specially to avoid creating directories with colons like
// "bundle:personal". Non-token references are returned unchanged.
func cleanPullTokenRef(refStr string) (string, error) {
	if !strings.HasPrefix(refStr, "bundle:") && !strings.HasPrefix(refStr, "profile:") {
		return refStr, nil
	}
	_, cleanRef, _, err := parsePullToken(refStr)
	if err != nil {
		return "", fmt.Errorf("invalid pull token: %w", err)
	}
	return cleanRef, nil
}

// WriteRemoteItem writes fetched content to the local filesystem.
// This is used by the MCP confirm_pull tool.
func WriteRemoteItem(ctx context.Context, cfg *config.Config, req WriteRemoteItemRequest) (*WriteRemoteItemResult, error) {
	fs := getFS(req.FS)

	itemType, err := parseRemoteItemType(req.ItemType)
	if err != nil {
		return nil, err
	}

	refStr, err := cleanPullTokenRef(req.Reference)
	if err != nil {
		return nil, err
	}

	ref, err := remote.ParseReference(refStr)
	if err != nil {
		return nil, fmt.Errorf("invalid reference: %w", err)
	}

	// Use config's ctxloom path
	baseDir := getBaseDir(cfg)
	localPath := ref.LocalPath(baseDir, itemType)

	// Check for existing file
	overwritten := false
	if _, err := fs.Stat(localPath); err == nil {
		overwritten = true
	}

	// Write file
	if err := fs.MkdirAll(filepath.Dir(localPath), 0755); err != nil {
		return nil, fmt.Errorf("failed to create directory: %w", err)
	}

	if err := afero.WriteFile(fs, localPath, req.Content, 0644); err != nil {
		return nil, fmt.Errorf("failed to write file: %w", err)
	}

	status := "installed"
	if overwritten {
		status = "updated"
	}

	return &WriteRemoteItemResult{
		Status:      status,
		Reference:   req.Reference,
		ItemType:    req.ItemType,
		LocalPath:   localPath,
		SHA:         shortSHA(req.SHA),
		Overwritten: overwritten,
	}, nil
}

// PullItemRequest contains parameters for a direct pull operation.
type PullItemRequest struct {
	Reference string `json:"reference"`
	ItemType  string `json:"item_type"` // "bundle" or "profile"
	Force     bool   `json:"force"`
	Blind     bool   `json:"blind"` // Skip security review display (implies Force)
	Cascade   bool   `json:"cascade"`

	// Registry is an optional pre-configured registry (for testing).
	Registry *remote.Registry `json:"-"`
	// Puller is an optional pre-configured puller (for testing).
	Puller Puller `json:"-"`
	// FS is an optional filesystem (for testing).
	FS afero.Fs `json:"-"`
}

// PullItemResult contains the result of a pull operation.
type PullItemResult struct {
	LocalPath     string   `json:"local_path"`
	SHA           string   `json:"sha"`
	Overwritten   bool     `json:"overwritten"`
	CascadePulled []string `json:"cascade_pulled,omitempty"`
	Installation  string   `json:"installation,omitempty"` // Setup instructions for the user
}

// PullItem performs a direct pull operation using the existing Puller.
// This wraps the remote.Puller with correct config-based LocalDir.
func PullItem(ctx context.Context, cfg *config.Config, req PullItemRequest) (*PullItemResult, error) {
	itemType, err := parseRemoteItemType(req.ItemType)
	if err != nil {
		return nil, err
	}

	baseDir := getBaseDir(cfg)
	puller, err := resolvePullItemPuller(cfg, req, baseDir)
	if err != nil {
		return nil, err
	}

	opts := remote.PullOptions{
		LocalDir: baseDir, // THIS IS THE BUG FIX
		Force:    req.Force,
		Blind:    req.Blind,
		ItemType: itemType,
		Cascade:  req.Cascade,
	}

	result, err := puller.Pull(ctx, req.Reference, opts)
	if err != nil {
		return nil, err
	}

	return &PullItemResult{
		LocalPath:     result.LocalPath,
		SHA:           result.SHA,
		Overwritten:   result.Overwritten,
		CascadePulled: result.CascadePulled,
		Installation:  bundleInstallation(itemType, result.Content),
	}, nil
}

// resolvePullItemPuller returns the injected puller, or builds one from an
// injected/loaded registry.
func resolvePullItemPuller(cfg *config.Config, req PullItemRequest, baseDir string) (Puller, error) {
	if req.Puller != nil {
		return req.Puller, nil
	}
	registry := req.Registry
	if registry == nil {
		var err error
		registry, err = getRegistry(cfg, remote.WithRegistryFS(getFS(req.FS)))
		if err != nil {
			return nil, fmt.Errorf("failed to initialize registry: %w", err)
		}
	}
	auth := remote.LoadAuth(baseDir)
	return remote.NewPuller(registry, auth, remote.WithFetcherFactory(newCachedFetcherFactory(cfg))), nil
}

// bundleInstallation extracts a pulled bundle's installation instructions from
// its content. After PR 1 the bundle bytes come back on result.Content
// (LocalPath is synthetic), so parse those directly instead of reading disk.
// Returns "" for non-bundles, empty content, or parse failures.
func bundleInstallation(itemType remote.ItemType, content []byte) string {
	if itemType != remote.ItemTypeBundle || len(content) == 0 {
		return ""
	}
	bundle, err := bundles.ParseBundle(content)
	if err != nil {
		return ""
	}
	return bundle.Installation
}
