package docsgen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// fakeProduct builds a small three-command tree standing in for a real binary,
// with one hidden subcommand to exercise the unhide list.
func fakeProduct() *Product {
	// Every leaf is Runnable: cobra's doc generators skip commands that are
	// neither runnable nor parents, so a fixture without Run funcs would
	// generate nothing at all.
	noop := func(*cobra.Command, []string) {}
	root := &cobra.Command{Use: "widget", Short: "Weave widgets", Run: noop}
	sub := &cobra.Command{Use: "make", Short: "Make a widget", Run: noop}
	hidden := &cobra.Command{Use: "advanced", Short: "Advanced widgetry", Hidden: true}
	hidden.AddCommand(&cobra.Command{Use: "poke", Short: "Poke a widget", Run: noop})
	root.AddCommand(sub, hidden)

	return &Product{
		Bin:       "widget",
		Root:      root,
		CLISource: "cmd/widget",
		LinkBase:  "/widget/reference/cli/",
		ManTitle:  "WIDGET",
		ManManual: "User Commands",
		Unhide:    []string{"advanced"},
	}
}

// TestPrepareTree pins the invariants the generated docs depend on: deterministic
// output (cobra's auto-gen timestamp disabled on every command) and the
// product's declared hidden commands unhidden so their pages still generate.
func TestPrepareTree(t *testing.T) {
	p := fakeProduct()
	p.PrepareTree()

	var walk func(*cobra.Command)
	sawAdvanced := false
	walk = func(c *cobra.Command) {
		if !c.DisableAutoGenTag {
			t.Errorf("DisableAutoGenTag not set on %q", c.CommandPath())
		}
		if c.Name() == "advanced" {
			sawAdvanced = true
			if c.Hidden {
				t.Error("advanced command still hidden after PrepareTree")
			}
		}
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(p.Root)

	if !sawAdvanced {
		t.Fatal("advanced command not found in the tree")
	}
}

// TestPrepareTreeLeavesUnlistedHiddenCommands makes sure the unhide list is a
// list, not a blanket unhide: a hidden command nobody asked for stays hidden.
func TestPrepareTreeLeavesUnlistedHiddenCommands(t *testing.T) {
	p := fakeProduct()
	p.Unhide = nil
	p.PrepareTree()

	for _, c := range p.Root.Commands() {
		if c.Name() == "advanced" && !c.Hidden {
			t.Error("advanced unhidden despite an empty Unhide list")
		}
	}
}

func TestGenMarkdown(t *testing.T) {
	dir := t.TempDir()
	p := fakeProduct()
	p.PrepareTree()

	// A stale page from a since-renamed command, and the hand-written index
	// the generator must never touch.
	stale := filepath.Join(dir, "widget_gone.md")
	if err := os.WriteFile(stale, []byte("stale"), 0o644); err != nil {
		t.Fatal(err)
	}
	index := filepath.Join(dir, "index.md")
	if err := os.WriteFile(index, []byte("hand-written"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := GenMarkdown(p, dir); err != nil {
		t.Fatalf("GenMarkdown: %v", err)
	}

	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("stale generated page not removed")
	}
	if data, err := os.ReadFile(index); err != nil || string(data) != "hand-written" {
		t.Errorf("hand-written index.md was clobbered: %q, %v", data, err)
	}

	page, err := os.ReadFile(filepath.Join(dir, "widget_make.md"))
	if err != nil {
		t.Fatalf("expected a page for `widget make`: %v", err)
	}
	for _, want := range []string{
		`title: "widget make"`,
		"GENERATED by `just gen-docs`",
		"cmd/widget",
		"generated from `widget make --help`",
	} {
		if !strings.Contains(string(page), want) {
			t.Errorf("widget_make.md missing %q:\n%s", want, page)
		}
	}

	// The unhidden command's subtree generates too, and inter-page links are
	// rewritten to the product's site route, not a bare .md path.
	root, err := os.ReadFile(filepath.Join(dir, "widget.md"))
	if err != nil {
		t.Fatalf("expected a root page: %v", err)
	}
	if !strings.Contains(string(root), "/widget/reference/cli/widget_make/") {
		t.Errorf("root page does not link through LinkBase:\n%s", root)
	}
	if _, err := os.Stat(filepath.Join(dir, "widget_advanced_poke.md")); err != nil {
		t.Errorf("unhidden subtree did not generate: %v", err)
	}
}

// The man-page sweep pattern <bin>*.1 is a prefix glob, not a word
// match, so it can delete an unrelated binary's pages whose name happens to
// start with this product's Bin (e.g. "widget" sweeping "widgets-make.1",
// a different product's page).
func TestGenManSweepIsPrefixSafe(t *testing.T) {
	dir := t.TempDir()
	// A different product ("widgets", not "widget") whose man page name
	// happens to start with this product's Bin.
	otherProduct := filepath.Join(dir, "widgets-make.1")
	if err := os.WriteFile(otherProduct, []byte("another product"), 0o644); err != nil {
		t.Fatal(err)
	}

	p := fakeProduct()
	p.PrepareTree()
	if err := GenMan(p, dir); err != nil {
		t.Fatalf("GenMan: %v", err)
	}

	if _, err := os.Stat(otherProduct); err != nil {
		t.Errorf("a same-prefix product's man page was wrongly swept: %v", err)
	}
}

// GenMan/GenMarkdown used to return MkdirAll's bare error, with no
// indication of which operation or directory failed. Force MkdirAll to fail
// (a path component that's a regular file, not a directory) and require the
// wrapped error to name the operation and the directory.
func TestGenMarkdown_MkdirFailureHasContext(t *testing.T) {
	base := t.TempDir()
	blocker := filepath.Join(base, "blocker")
	if err := os.WriteFile(blocker, []byte("not a dir"), 0o644); err != nil {
		t.Fatal(err)
	}
	dir := filepath.Join(blocker, "markdown")

	p := fakeProduct()
	p.PrepareTree()
	err := GenMarkdown(p, dir)
	if err == nil {
		t.Fatal("expected an error creating markdown dir under a file")
	}
	if !strings.Contains(err.Error(), "markdown dir") || !strings.Contains(err.Error(), dir) {
		t.Errorf("GenMarkdown error lacks operation/dir context: %v", err)
	}
}

func TestGenMan_MkdirFailureHasContext(t *testing.T) {
	base := t.TempDir()
	blocker := filepath.Join(base, "blocker")
	if err := os.WriteFile(blocker, []byte("not a dir"), 0o644); err != nil {
		t.Fatal(err)
	}
	dir := filepath.Join(blocker, "man1")

	p := fakeProduct()
	p.PrepareTree()
	err := GenMan(p, dir)
	if err == nil {
		t.Fatal("expected an error creating man dir under a file")
	}
	if !strings.Contains(err.Error(), "man dir") || !strings.Contains(err.Error(), dir) {
		t.Errorf("GenMan error lacks operation/dir context: %v", err)
	}
}

// filePrepender interpolates p.CLISource unguarded, so an unset
// field used to render an empty code span in the "generated from ... --help"
// banner instead of signalling the misconfiguration. Require CLISource
// non-empty before generating markdown.
func TestGenMarkdown_RequiresCLISource(t *testing.T) {
	p := fakeProduct()
	p.PrepareTree()
	p.CLISource = ""

	if err := GenMarkdown(p, t.TempDir()); err == nil {
		t.Fatal("expected an error generating markdown pages with an empty CLISource")
	}
}

func TestGenMan(t *testing.T) {
	dir := t.TempDir()
	p := fakeProduct()
	p.PrepareTree()

	stale := filepath.Join(dir, "widget-gone.1")
	if err := os.WriteFile(stale, []byte("stale"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := GenMan(p, dir); err != nil {
		t.Fatalf("GenMan: %v", err)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("stale man page not removed")
	}
	page, err := os.ReadFile(filepath.Join(dir, "widget-make.1"))
	if err != nil {
		t.Fatalf("expected a man page for `widget make`: %v", err)
	}
	if !strings.Contains(string(page), "WIDGET") {
		t.Errorf("man page missing the product title:\n%s", page)
	}
}

// TestGenManOnlyRemovesOwnPages guards the shared man/man1 directory: three
// products generate into it, so one product's regeneration must not delete
// another's pages.
func TestGenManOnlyRemovesOwnPages(t *testing.T) {
	dir := t.TempDir()
	other := filepath.Join(dir, "gadget-make.1")
	if err := os.WriteFile(other, []byte("another product"), 0o644); err != nil {
		t.Fatal(err)
	}

	p := fakeProduct()
	p.PrepareTree()
	if err := GenMan(p, dir); err != nil {
		t.Fatalf("GenMan: %v", err)
	}

	if _, err := os.Stat(other); err != nil {
		t.Errorf("another product's man page was removed: %v", err)
	}
}
