//go:build parked_engines

package kiro

import (
	"github.com/spf13/afero"

	"github.com/ctxloom/ctxloom/internal/shared/agent"
)

// NewInstanceConfigWriter constructs kiro's instance-config generator, whose
// ambient contribution is EMPTY — BY DESIGN, not by omission. The method exists
// so kiro's answer is DECLARED rather than inferred from a nil: an engine
// missing from the roster and an engine that genuinely contributes nothing look
// identical to a caller, and only one of them is a fact about the engine.
//
// WHY NOTHING CROSSES, verified rather than assumed:
//
//   - No credential is seedable. kiro's subscription auth lives in a global
//     SQLite database under $XDG_DATA_HOME (~/.local/share/kiro-cli/data.sqlite3,
//     live-verified against kiro-cli 2.12.1), which KIRO_HOME does not relocate
//     — so a FRESH instance home stays authenticated and there is no file to
//     copy. isolation's credentialSeedSpecs["kiro"] records the same fact as
//     HonoursVarForCreds:false with no sourceFiles.
//   - No config SHOULD cross. Since kiro-cli 2.3.0 KIRO_HOME relocates the full
//     home — global agents, prompts, skills, steering, settings and sessions.
//     Copying any of that into an instance would hand a delegated agent the
//     human's own global agents and steering, which is precisely what pointing
//     an agent run at a fresh KIRO_HOME exists to prevent. Everything the
//     instance needs is GENERATED by kiro's own surfaces at launch.
//   - No trust or onboarding answer to carry. kiro has no workspace-trust
//     prompt of claude's or codex's shape, so there is no per-project answer an
//     instance would re-ask for.
func NewInstanceConfigWriter(o agent.SettingsOptions) agent.InstanceConfigWriter {
	return &kiroInstanceConfig{FS: o.FS}
}

// kiroInstanceConfig implements agent.InstanceConfigWriter for kiro.
type kiroInstanceConfig struct {
	FS afero.Fs
}

var _ agent.InstanceConfigWriter = (*kiroInstanceConfig)(nil)

// WriteInstanceConfig writes nothing and reports nothing — see
// NewInstanceConfigWriter for the three independent reasons. It returns a zero
// report and a nil error, never an error: "this engine contributes no ambient
// config" is a normal, correct outcome, not a fault.
func (w *kiroInstanceConfig) WriteInstanceConfig(agent.InstanceConfigRequest) (agent.InstanceConfigReport, error) {
	return agent.InstanceConfigReport{}, nil
}
