package main

import (
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/ctxloom/ctxloom/internal/cli"
)

// TestPrepareTree pins the two invariants the generated docs depend on:
// deterministic output (auto-gen tag disabled everywhere) and the hidden
// `bundle` command being unhidden so its pages generate.
func TestPrepareTree(t *testing.T) {
	root := cli.GetRootCmd()
	prepareTree(root)

	sawBundle := false
	var walk func(*cobra.Command)
	walk = func(c *cobra.Command) {
		if !c.DisableAutoGenTag {
			t.Errorf("DisableAutoGenTag not set on %q", c.CommandPath())
		}
		if c.Name() == "bundle" && c.Parent() == root {
			sawBundle = true
			if c.Hidden {
				t.Error("bundle command still hidden after prepareTree")
			}
		}
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(root)

	if !sawBundle {
		t.Fatal("bundle command not found in the command tree")
	}
}

func TestFilePrepender(t *testing.T) {
	got := filePrepender("website/src/content/docs/reference/cli/ctxloom_profile_create.md")
	for _, want := range []string{
		`title: "ctxloom profile create"`,
		"GENERATED by `just gen-docs`",
		"generated from `ctxloom profile create --help`",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("filePrepender output missing %q:\n%s", want, got)
		}
	}
}

func TestLinkHandler(t *testing.T) {
	if got, want := linkHandler("ctxloom_profile_create.md"), "/reference/cli/ctxloom_profile_create/"; got != want {
		t.Errorf("linkHandler = %q, want %q", got, want)
	}
}
