package archrules

// WriteDisciplineAllowed is the write-discipline gate's shrinking allowlist:
// a durable "file.go#Symbol" reference mapped to the fix required to remove
// the entry. It is generated MECHANICALLY — run the gate with an empty map
// and transcribe what it reports — so the baseline records exactly what the
// scan sees, and it only ever tightens: a raw filesystem write is migrated
// to iox and its entry deleted, never added without a reason. The analyzer
// fails an entry the scan no longer reports.
var WriteDisciplineAllowed = map[string]string{
	"internal/core/coord/artifactstore.go#artifactStore.publish":                "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/adapters/runner/homeartifacts.go#placeVerified":                   "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/adapters/coordgrpc/httpserver.go#coordServing.saveEndpointLocked": "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/core/coord/journal.go#openStoreFromOffset":                        "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/core/coord/statedir.go#claimOwner":                                "advisory lock file's own O_EXCL create — mechanically parallel to the old filelock package's (deleted) exemption but never itself part of it (fs-consolidation plan C10 to decide: fold into a shared lock-file-create helper or exempt structurally)",
	"internal/adapters/coordgrpc/mcpschema/gen/main.go#writeSpec":               "pre-ratchet baseline, codegen tool — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/core/spool/ops.go#renameInto":                                     "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/core/spool/writer.go#Writer.Write":                                "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/core/spool/writer.go#writeAndSync":                                "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/core/bundles/skill_archive.go#ImportSkillArchive":                 "C10 content/skill_archive sweep: fsys.Rename here is a WHOLE-DIRECTORY swap (staged tree -> final, and final -> aside on replace), not a single-file content write — outside iox's WriteFileAtomicFs API, which has no directory-rename surface. This is a deliberate, already-safe swap-never-clear-then-hope idiom (see the function's own doc) with its own aside/restore recovery; exempt, not a violation to migrate.",
	"internal/adapters/companions/companion_pin.go#PinAdmittedCompanions":       "os.Rename here publishes a WHOLE DIRECTORY (the staged pin -> its content-addressed name, and a bad one replaced), the same shape as skill_archive.go#ImportSkillArchive — outside iox, which has no directory-rename surface; the files inside go through iox.WriteFileAtomic. Removed when iox grows a directory publish.",
	"internal/adapters/cli/bundle_items.go#editInEditor":                        "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/adapters/cli/run_terminal_ui.go#redirectDiagnosticsForTUI":        "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/adapters/contextmetrics/contextmetrics.go#Append":                 "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/adapters/isolation/imagebuild.go#buildBaseImage":                  "C10 isolation sweep: writes inside a newOwnedScratch dir (imageBaseScratchPrefix, OS temp), removed by its release and, after a crash, reaped by the next owned-scratch creation — temp-dir-scoped, verified. Migration deferred to a future slice (mechanical, low priority — no concurrent-writer risk).",
	"internal/adapters/isolation/imagebuild.go#buildImage":                      "C10 isolation sweep: writes inside a newOwnedScratch dir (imageBuildScratchPrefix, OS temp), removed by its release and, after a crash, reaped by the next owned-scratch creation — temp-dir-scoped, verified. Migration deferred to a future slice (mechanical, low priority — no concurrent-writer risk).",
	"internal/adapters/isolation/sharedfs.go#probeOneRoot":                      "C10 isolation sweep: writes a marker file inside a newOwnedScratch dir (probeScratchPrefix, under the probed root), removed by its deferred release and, after a crash, reaped by the next probe — scratch-scoped, verified. Migration deferred to a future slice (mechanical, low priority).",
	"internal/adapters/isolation/statemounts.go#ensureFile":                     "C10 isolation sweep: the plan's 'all ~26 seams are temp-dir-scoped' claim is WRONG for this one — ensureFile's caller passes the LIVE ~/.ctxloom/tasks/<project>.jsonl path (taskpaths.HomeTasksLogPath) and its advisory-lock sidecar, to stand up the container bind-mount SOURCE before `run`. Not a write-discipline risk in practice: O_CREATE|O_WRONLY with no O_TRUNC only creates-if-absent and immediately Closes, matching the doc's 'never truncating a log that already has tasks in it' — but it is not temp-scoped, and iox's whole-file-replace API is the wrong shape for a create-if-absent primitive anyway. Reported, not migrated.",
	"internal/adapters/isolation/traceprobe.go#traceProbeFromEnv":               "C10 isolation sweep: writes into the probe's own trace dir, reaped by RemoveAll per the adjacent comment — temp-dir-scoped, verified. Migration deferred to a future slice (mechanical, low priority).",
	"internal/ltk/tools/extract-defaults/main.go#main":                          "pre-ratchet baseline, standalone codegen tool under internal/ltk — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/engines/mock/runtime/runtime.go#Runtime.emitReport":               "pre-ratchet baseline, mock engine test double — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/adapters/operations/delegate.go#copyUntrackedFile":                "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/adapters/operations/review_snapshots.go#moveTrustObjects":         "C10 operations sweep: fs.Rename(src, dst) here is a whole-DIRECTORY rename attempt (EXDEV-fallback pattern; falls back to copyTrustObjects, now migrated, + RemoveAll on cross-device failure) — not a single-file content write, outside iox's WriteFileAtomicFs API. Exempt, not a violation to migrate.",
	"internal/core/profiles/profiles.go#Loader.CommitUpgrade":                   "pre-ratchet baseline — internal/core/profiles is outside C10's five swept areas, left for a future slice (fs-consolidation plan C10)",
	"internal/core/profiles/profiles.go#Loader.Save":                            "pre-ratchet baseline — internal/core/profiles is outside C10's five swept areas, left for a future slice (fs-consolidation plan C10)",
	"internal/core/sessions/transcript.go#linkEngineTranscript":                 "per-vendor-log symlink create (fs-consolidation plan C12, Q2 RULED) — iox writes byte CONTENT and has no symlink primitive; the first-sighting os.Symlink here is the create-once path",
	"internal/core/sessions/transcript.go#atomicSymlink":                        "per-vendor-log symlink ATOMIC replace, the session-id-reuse anomaly path only (fs-consolidation plan C12, Q2 RULED) — unique-temp-name+rename mirrors iox's own algorithm, hand-applied because iox's primitives write byte content and have no symlink surface to delegate to",
	"internal/core/sessions/manager.go#Manager.Rename":                          "the flagged call MOVES a whole session DIRECTORY from its old harp name to its new one — the directory IS the session record, so a rename must carry essence, persisted files and sidecar together, and rename(2) leaves the tree at exactly one of the two names. iox writes byte content to a destination path and has no move primitive; copy-then-delete would open a window in which the session exists at neither name or both. Removing this entry requires a rename/move primitive on iox, not a rewrite of this call site.",
	"internal/core/agent/contextfile.go#WriteContextFile":                       "pre-ratchet baseline — internal/core/agent is outside C10's five swept areas, left for a future slice (fs-consolidation plan C10)",
	"internal/core/agent/packagefiles.go#WriteManagedPackageFiles":              "C11's DELIBERATE render-to-temp-then-swap design (fs-consolidation plan D8), not un-swept legacy: afero.WriteFile renders each file into a sibling afero.TempDir tree, then fs.Rename swaps each into place as a single atomic per-file replace — this IS the fix humorless-factor/dutiful-water required, and the flagged calls are its two working parts, not a queued migration (fs-consolidation closing verification, stale-reason finding: the original baseline predates C11's rewrite of this function)",
	"internal/core/agent/rendezvous.go#writeMarker":                             "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/core/agent/settings_io.go#RefuseCorrupt":                          "pre-ratchet baseline — internal/core/agent is outside C10's five swept areas, left for a future slice (fs-consolidation plan C10)",
	"internal/shared/logsink/logsink.go#Open":                                   "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/shared/logsink/logsink.go#rollIfOversized":                        "pre-ratchet baseline — migrate to iox (fs-consolidation plan C3/C10)",
	"internal/shared/tasks/taskstest/gitfixture.go#RealGitWorktreeFixture":      "test fixture package, not shipped production code — pre-ratchet baseline (fs-consolidation plan C10)",
	"internal/testsupport/containercell/containercell.go#Runtime.buildImage":    "test harness, never linked into a binary — pre-ratchet baseline (fs-consolidation plan C10)",
	"internal/testsupport/containercell/containercell.go#buildBinary":           "test harness, never linked into a binary — pre-ratchet baseline (fs-consolidation plan C10)",
	"internal/testsupport/containercell/containercell.go#buildProbeCat":         "test harness, never linked into a binary — pre-ratchet baseline (fs-consolidation plan C10)",
	"internal/adapters/transcript/recorder.go#openAppendFile":                   "the recorder holds ONE fd open across every Record call for a session's lifetime (opened lazily on the first captured event, closed by Close) and streams into it. WriteFileInPlace(AppendInPlace) is one-shot — it opens, writes and closes per call — so routing this through it would reopen the transcript per event and, more importantly, dissolve the `open func(path string) (io.WriteCloser, error)` seam the partial-write tests drive, which iox deliberately provides no twin for. The exemption is the HELD DESCRIPTOR; it lasts as long as the recorder streams rather than writes.",
}
