package archrules

// WriteDisciplineAllowed is the write-discipline gate's shrinking allowlist:
// a durable "file.go#Symbol" reference mapped to the fix required to remove
// the entry. It is generated MECHANICALLY — run the gate with an empty map
// and transcribe what it reports — so the baseline records exactly what the
// scan sees, and it only ever tightens: a raw filesystem write is migrated
// to safefs and its entry deleted, never added without a reason. The analyzer
// fails an entry the scan no longer reports.
var WriteDisciplineAllowed = map[string]string{
	"internal/shared/platform/posix/dirlink.go#Linker.LinkDir":               "the POSIX directory link (the session home's relative link into native/ history) — safefs writes byte CONTENT and has no symlink primitive; create-once into a freshly prepared home, never replaced (a wrong occupant is refused)",
	"internal/core/coord/journal.go#openStoreFromOffset":                     "the journal is ONE long-lived O_RDWR handle (replay, torn-tail truncate, then appends from its single writer goroutine), opened through the coordinator's Root.Fs — safefs has no append-handle primitive; needs one that carries the guard and durability for an append stream",
	"internal/shared/tasks/log.go#eventLog.append":                           "append rollback: os.Truncate restores the pre-append length after a failed safefs.WriteFileInPlace append — needs an in-place append that rolls itself back inside safefs",
	"internal/adapters/coordgrpc/mcpschema/gen/main.go#writeSpec":            "pre-ratchet baseline, codegen tool — migrate to safefs (fs-consolidation plan C3/C10)",
	"internal/adapters/cli/bundle_items.go#editInEditor":                     "pre-ratchet baseline — migrate to safefs (fs-consolidation plan C3/C10)",
	"internal/adapters/cli/run_terminal_ui.go#redirectDiagnosticsForTUI":     "pre-ratchet baseline — migrate to safefs (fs-consolidation plan C3/C10)",
	"internal/adapters/contextmetrics/contextmetrics.go#Append":              "pre-ratchet baseline — migrate to safefs (fs-consolidation plan C3/C10)",
	"internal/adapters/isolation/imagebuild.go#buildBaseImage":               "C10 isolation sweep: writes inside a newOwnedScratch dir (imageBaseScratchPrefix, OS temp), removed by its release and, after a crash, reaped by the next owned-scratch creation — temp-dir-scoped, verified. Migration deferred to a future slice (mechanical, low priority — no concurrent-writer risk).",
	"internal/adapters/isolation/imagebuild.go#buildImage":                   "C10 isolation sweep: writes inside a newOwnedScratch dir (imageBuildScratchPrefix, OS temp), removed by its release and, after a crash, reaped by the next owned-scratch creation — temp-dir-scoped, verified. Migration deferred to a future slice (mechanical, low priority — no concurrent-writer risk).",
	"internal/adapters/isolation/sharedfs.go#probeOneRoot":                   "C10 isolation sweep: writes a marker file inside a newOwnedScratch dir (probeScratchPrefix, under the probed root), removed by its deferred release and, after a crash, reaped by the next probe — scratch-scoped, verified. Migration deferred to a future slice (mechanical, low priority).",
	"internal/adapters/isolation/statemounts.go#ensureFile":                  "C10 isolation sweep: the plan's 'all ~26 seams are temp-dir-scoped' claim is WRONG for this one — ensureFile's caller passes the LIVE ~/.ctxloom/tasks/<project>.jsonl path (taskpaths.HomeTasksLogPath) and its advisory-lock sidecar, to stand up the container bind-mount SOURCE before `run`. Not a write-discipline risk in practice: O_CREATE|O_WRONLY with no O_TRUNC only creates-if-absent and immediately Closes, matching the doc's 'never truncating a log that already has tasks in it' — but it is not temp-scoped, and safefs's whole-file-replace API is the wrong shape for a create-if-absent primitive anyway. Reported, not migrated.",
	"internal/ltk/tools/extract-defaults/main.go#main":                       "pre-ratchet baseline, standalone codegen tool under internal/ltk — migrate to safefs (fs-consolidation plan C3/C10)",
	"internal/engines/mock/runtime/runtime.go#Runtime.emitReport":            "pre-ratchet baseline, mock engine test double — migrate to safefs (fs-consolidation plan C3/C10)",
	"internal/adapters/operations/delegate.go#copyUntrackedFile":             "pre-ratchet baseline — migrate to safefs (fs-consolidation plan C3/C10)",
	"internal/core/profiles/profiles.go#Loader.Save":                         "pre-ratchet baseline — internal/core/profiles is outside C10's five swept areas, left for a future slice (fs-consolidation plan C10)",
	"internal/core/agent/contextfile.go#WriteContextFile":                    "pre-ratchet baseline — internal/core/agent is outside C10's five swept areas, left for a future slice (fs-consolidation plan C10)",
	"internal/core/agent/packagefiles.go#writeManagedPackageFilesLocked":     "C11's DELIBERATE render-to-temp-then-swap design (fs-consolidation plan D8), not un-swept legacy: afero.WriteFile renders each file into a sibling afero.TempDir tree, then fs.Rename swaps each into place as a single atomic per-file replace — this IS the fix humorless-factor/dutiful-water required, and the flagged calls are its two working parts, not a queued migration (fs-consolidation closing verification, stale-reason finding: the original baseline predates C11's rewrite of this function)",
	"internal/core/agent/rendezvous.go#writeMarker":                          "pre-ratchet baseline — migrate to safefs (fs-consolidation plan C3/C10)",
	"internal/core/agent/settings_io.go#RefuseCorrupt":                       "pre-ratchet baseline — internal/core/agent is outside C10's five swept areas, left for a future slice (fs-consolidation plan C10)",
	"internal/shared/logsink/logsink.go#Open":                                "pre-ratchet baseline — migrate to safefs (fs-consolidation plan C3/C10)",
	"internal/shared/logsink/logsink.go#rollIfOversized":                     "pre-ratchet baseline — migrate to safefs (fs-consolidation plan C3/C10)",
	"internal/shared/tasks/taskstest/gitfixture.go#RealGitWorktreeFixture":   "test fixture package, not shipped production code — pre-ratchet baseline (fs-consolidation plan C10)",
	"internal/testsupport/containercell/containercell.go#Runtime.buildImage": "test harness, never linked into a binary — pre-ratchet baseline (fs-consolidation plan C10)",
	"internal/testsupport/containercell/containercell.go#buildBinary":        "test harness, never linked into a binary — pre-ratchet baseline (fs-consolidation plan C10)",
	"internal/testsupport/containercell/containercell.go#buildProbeCat":      "test harness, never linked into a binary — pre-ratchet baseline (fs-consolidation plan C10)",
	"internal/adapters/transcript/recorder.go#openAppendFile":                "the recorder holds ONE fd open across every Record call for a session's lifetime (opened lazily on the first captured event, closed by Close) and streams into it. WriteFileInPlace(AppendInPlace) is one-shot — it opens, writes and closes per call — so routing this through it would reopen the transcript per event and, more importantly, dissolve the `open func(path string) (io.WriteCloser, error)` seam the partial-write tests drive, which safefs deliberately provides no twin for. The exemption is the HELD DESCRIPTOR; it lasts as long as the recorder streams rather than writes.",
}
