package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/ctxloom/ctxloom/internal/operations"
)

// TestEnsureGitignoreEntry covers ctxloom init's "keep ctxloom's private
// working state (ephemeral cache + project-id marker) out of source control"
// sweep. Cases cover all the file-state branches.
func TestEnsureGitignoreEntry(t *testing.T) {
	const ephemeral = ".ctxloom/ephemeral/"
	const marker = ".ctxloom/project-id"

	t.Run("creates_gitignore_when_missing", func(t *testing.T) {
		dir := t.TempDir()
		require.NoError(t, ensureGitignoreEntry(dir))

		data, err := os.ReadFile(filepath.Join(dir, ".gitignore"))
		require.NoError(t, err)
		assert.Contains(t, string(data), ephemeral)
		assert.Contains(t, string(data), marker,
			"the project-id marker must be ignored (ADR 0025 private/distributable wall)")
		assert.Contains(t, string(data), "ctxloom private working state",
			"comment must be written so the entries are self-documenting")
	})

	t.Run("appends_to_existing_gitignore", func(t *testing.T) {
		dir := t.TempDir()
		existing := "*.log\nbin/\n"
		require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(existing), 0o644))

		require.NoError(t, ensureGitignoreEntry(dir))
		data, _ := os.ReadFile(filepath.Join(dir, ".gitignore"))
		body := string(data)
		assert.Contains(t, body, "*.log", "existing content must survive")
		assert.Contains(t, body, "bin/")
		assert.Contains(t, body, ephemeral)
	})

	t.Run("idempotent_when_entry_present", func(t *testing.T) {
		dir := t.TempDir()
		existing := "# something\n.ctxloom/ephemeral/\n"
		require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(existing), 0o644))

		require.NoError(t, ensureGitignoreEntry(dir))
		data, _ := os.ReadFile(filepath.Join(dir, ".gitignore"))
		// Entry should appear exactly once.
		assert.Equal(t, 1, strings.Count(string(data), ephemeral),
			"re-running must NOT add a duplicate entry")
	})

	t.Run("idempotent_with_whitespace_around_entry", func(t *testing.T) {
		dir := t.TempDir()
		// Existing entry has trailing whitespace — the equality check
		// uses TrimSpace, so this must still detect the entry.
		existing := "  .ctxloom/ephemeral/  \n"
		require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(existing), 0o644))

		require.NoError(t, ensureGitignoreEntry(dir))
		data, _ := os.ReadFile(filepath.Join(dir, ".gitignore"))
		assert.Equal(t, 1, strings.Count(string(data), ephemeral),
			"trim-aware match prevents duplicate-on-whitespace")
	})

	t.Run("idempotent_across_reruns", func(t *testing.T) {
		dir := t.TempDir()
		require.NoError(t, ensureGitignoreEntry(dir))
		require.NoError(t, ensureGitignoreEntry(dir))
		data, _ := os.ReadFile(filepath.Join(dir, ".gitignore"))
		assert.Equal(t, 1, strings.Count(string(data), marker),
			"marker must not be duplicated on rerun")
		assert.Equal(t, 1, strings.Count(string(data), ephemeral),
			"ephemeral must not be duplicated on rerun")
	})

	t.Run("adds_missing_marker_to_gitignore_that_has_only_ephemeral", func(t *testing.T) {
		dir := t.TempDir()
		existing := "# ctxloom ephemeral data\n.ctxloom/ephemeral/\n"
		require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(existing), 0o644))

		require.NoError(t, ensureGitignoreEntry(dir))
		data, _ := os.ReadFile(filepath.Join(dir, ".gitignore"))
		assert.Equal(t, 1, strings.Count(string(data), ephemeral),
			"pre-existing ephemeral entry must not be re-added")
		assert.Contains(t, string(data), marker,
			"the marker must be appended to a gitignore that predates ADR 0025")
	})

	t.Run("adds_newline_when_file_lacks_trailing_newline", func(t *testing.T) {
		dir := t.TempDir()
		// File ends without \n — common when generated by an editor that
		// didn't auto-append. Our writer should insert one before its
		// comment so the entry doesn't end up on the same line as the
		// last existing rule.
		existing := "*.log" // no \n
		require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(existing), 0o644))

		require.NoError(t, ensureGitignoreEntry(dir))
		data, _ := os.ReadFile(filepath.Join(dir, ".gitignore"))
		assert.False(t, strings.Contains(string(data), "*.log#"),
			"must NOT concatenate with previous content")
		// Confirm the ephemeral entry survived.
		assert.Contains(t, string(data), ephemeral)
	})

	t.Run("error_when_projectdir_unwritable", func(t *testing.T) {
		// Pointing at a non-existent dir surfaces an error from OpenFile.
		err := ensureGitignoreEntry("/nonexistent/path/that/does/not/exist")
		assert.Error(t, err)
	})
}

// TestGenerateConfig covers the ctxloom init config builder. The selected
// engine's backend type lands in the registry, and the output must be valid
// YAML ending in a newline.
func TestGenerateConfig(t *testing.T) {
	for _, engine := range []string{"claude-code", "gemini", "codex"} {
		t.Run(engine, func(t *testing.T) {
			data, err := operations.BuildInitialConfig(engine)
			require.NoError(t, err)
			body := string(data)
			assert.Contains(t, body, "type: "+engine,
				"engine must appear as a registry entry type")
			assert.NotContains(t, body, "role:",
				"role is registry-only and stripped on write")
			assert.True(t, strings.HasSuffix(body, "\n"),
				"config must end with newline (POSIX-friendly + diff-friendly)")
		})
	}
}

func TestGenerateConfig_DefaultsBlock(t *testing.T) {
	data, err := operations.BuildInitialConfig("claude-code")
	require.NoError(t, err)
	body := string(data)
	// The scaffold settings survive into the written config.
	assert.Contains(t, body, "use_distilled: true")
	assert.Contains(t, body, "auto_register_ctxloom: true")
	// The engine's role pair is wired into llm.defaults.
	assert.Contains(t, body, "primary: claude-code")
	assert.Contains(t, body, "fast: claude-fast")
}
