package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestEnsureGitignoreEntry covers ctxloom init's "make sure
// .ctxloom/ephemeral/ stays out of source control" sweep. Six cases
// covering all the file-state branches.
func TestEnsureGitignoreEntry(t *testing.T) {
	const ephemeral = ".ctxloom/ephemeral/"

	t.Run("creates_gitignore_when_missing", func(t *testing.T) {
		dir := t.TempDir()
		require.NoError(t, ensureGitignoreEntry(dir))

		data, err := os.ReadFile(filepath.Join(dir, ".gitignore"))
		require.NoError(t, err)
		assert.Contains(t, string(data), ephemeral)
		assert.Contains(t, string(data), "ctxloom ephemeral data",
			"comment must be written so the entry is self-documenting")
	})

	t.Run("appends_to_existing_gitignore", func(t *testing.T) {
		dir := t.TempDir()
		existing := "*.log\nbin/\n"
		require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(existing), 0o644))

		require.NoError(t, ensureGitignoreEntry(dir))
		data, _ := os.ReadFile(filepath.Join(dir, ".gitignore"))
		body := string(data)
		assert.Contains(t, body, "*.log", "existing content must survive")
		assert.Contains(t, body, "bin/")
		assert.Contains(t, body, ephemeral)
	})

	t.Run("idempotent_when_entry_present", func(t *testing.T) {
		dir := t.TempDir()
		existing := "# something\n.ctxloom/ephemeral/\n"
		require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(existing), 0o644))

		require.NoError(t, ensureGitignoreEntry(dir))
		data, _ := os.ReadFile(filepath.Join(dir, ".gitignore"))
		// Entry should appear exactly once.
		assert.Equal(t, 1, strings.Count(string(data), ephemeral),
			"re-running must NOT add a duplicate entry")
	})

	t.Run("idempotent_with_whitespace_around_entry", func(t *testing.T) {
		dir := t.TempDir()
		// Existing entry has trailing whitespace — the equality check
		// uses TrimSpace, so this must still detect the entry.
		existing := "  .ctxloom/ephemeral/  \n"
		require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(existing), 0o644))

		require.NoError(t, ensureGitignoreEntry(dir))
		data, _ := os.ReadFile(filepath.Join(dir, ".gitignore"))
		assert.Equal(t, 1, strings.Count(string(data), ephemeral),
			"trim-aware match prevents duplicate-on-whitespace")
	})

	t.Run("adds_newline_when_file_lacks_trailing_newline", func(t *testing.T) {
		dir := t.TempDir()
		// File ends without \n — common when generated by an editor that
		// didn't auto-append. Our writer should insert one before its
		// comment so the entry doesn't end up on the same line as the
		// last existing rule.
		existing := "*.log" // no \n
		require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(existing), 0o644))

		require.NoError(t, ensureGitignoreEntry(dir))
		data, _ := os.ReadFile(filepath.Join(dir, ".gitignore"))
		assert.False(t, strings.Contains(string(data), "*.log#"),
			"must NOT concatenate with previous content")
		// Confirm the ephemeral entry survived.
		assert.Contains(t, string(data), ephemeral)
	})

	t.Run("error_when_projectdir_unwritable", func(t *testing.T) {
		// Pointing at a non-existent dir surfaces an error from OpenFile.
		err := ensureGitignoreEntry("/nonexistent/path/that/does/not/exist")
		assert.Error(t, err)
	})
}

// TestGenerateConfig covers the ctxloom init config template. The
// engine name appears in two places (llm.plugins.<engine> and
// defaults.llm_plugin), and the template must be valid YAML.
func TestGenerateConfig(t *testing.T) {
	for _, engine := range []string{"claude-code", "gemini", "codex"} {
		t.Run(engine, func(t *testing.T) {
			data := generateConfig(engine)
			body := string(data)
			// Two substitution sites.
			assert.Contains(t, body, "  "+engine+": {}",
				"engine must appear as a key under llm.plugins")
			assert.Contains(t, body, "llm_plugin: "+engine,
				"engine must appear as defaults.llm_plugin")
			// Sanity: must be parseable shape (top-level keys, ends with newline).
			assert.True(t, strings.HasPrefix(body, "# ctxloom Configuration"),
				"comment header pins the file's identity")
			assert.True(t, strings.HasSuffix(body, "\n"),
				"config must end with newline (POSIX-friendly + diff-friendly)")
		})
	}
}

func TestGenerateConfig_DefaultsBlock(t *testing.T) {
	data := generateConfig("claude-code")
	body := string(data)
	// Three default fields land at the top level so a user can grep for
	// each without parsing.
	assert.Contains(t, body, "defaults:")
	assert.Contains(t, body, "use_distilled: true")
	assert.Contains(t, body, "auto_register_ctxloom: true")
}
