// Package tasks provides a flesler-style file-backed task store keyed by
// harp IDs (see internal/harp). The file format is human-editable
// markdown sectioned by status, e.g.:
//
//	# Tasks
//
//	<!-- ctxloom-tasks:v1 -->
//
//	## In Progress
//	- [ ] `swift-amber-falcon` implement the storage layer
//
//	## To Do
//	- [ ] `quiet-silver-meadow` write storage layer
//
//	## Done
//	- [x] `misty-golden-river` spike session naming
//
// v1 caveat: non-task lines between tasks (free-form notes, blockquotes,
// etc.) are NOT preserved across mutations. The file is rewritten in a
// canonical shape on every Store.Add / SetStatus. If you want
// to keep notes alongside tasks, put them elsewhere for now. This will be
// addressed in a v2 if needed.
package tasks

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"

	"github.com/ctxloom/ctxloom/internal/filelock"
	"github.com/ctxloom/ctxloom/internal/harp"
)

// Default status names. flesler is configurable via env vars; we hardcode
// in v1 and revisit if user-defined statuses become a real need.
const (
	StatusInProgress = "In Progress"
	StatusToDo       = "To Do"
	StatusDone       = "Done"
	StatusArchived   = "Archived"
)

// DefaultStatusOrder is the canonical section order in tasks.md.
var DefaultStatusOrder = []string{StatusInProgress, StatusToDo, StatusDone, StatusArchived}

// Task is one row in the store.
type Task struct {
	HarpID   string // "swift-amber-falcon" — generated by internal/harp
	Text     string // trimmed, no harp ID inside
	Status   string // section name; one of DefaultStatusOrder or user-supplied
	Checked  bool   // true when status is Done/Archived; tracks the `[x]` bit on disk
	TextHash string // sha256(trimmed text), hex-encoded, first 12 chars

	// OriginSession is the harp of the session that created the task. Set by
	// the append-only log backend (ADR 0025) from the `add` event; empty for
	// legacy markdown stores, which carry no provenance.
	OriginSession string
}

// Store is a file-backed task store. tasks.md is the source of truth;
// every mutation reads, modifies, and atomically rewrites the file.
//
// The store is driven concurrently by separate processes (the MCP server,
// the bare `ctxloom tasks` CLI, and the out-of-process PostToolUse capture
// hook) as well as goroutines within one process. Mutations therefore hold
// both an in-process mutex and a cross-process advisory file lock spanning
// the whole read-modify-write, and rewrites go through a unique temp file so
// concurrent writers never collide on a fixed temp name.
type Store struct {
	path string
	mu   sync.Mutex

	// log, when non-nil, is the append-only JSONL backend (ADR 0025). In that
	// mode the public methods delegate to it and the markdown read/write path
	// (snapshot/write) is unused. nil selects the legacy markdown store.
	log *eventLog
}

// Open returns a Store rooted at <projectDir>/.ctxloom/tasks.md. The file
// is created lazily on first Add; reads of a missing file return an empty
// task list with no error.
func Open(projectDir string) (*Store, error) {
	if projectDir == "" {
		return nil, fmt.Errorf("projectDir required")
	}
	return &Store{path: filepath.Join(projectDir, ".ctxloom", "tasks.md")}, nil
}

// OpenPath returns a Store backed by an explicit tasks.md path. Unlike Open
// (which derives the legacy <projectDir>/.ctxloom/tasks.md location), this lets
// callers target a session-scoped store at ~/.ctxloom/sessions/<harp>/tasks.md
// (see HarpStorePath) or any other known location.
func OpenPath(path string) *Store {
	return &Store{path: path}
}

// OpenLog returns a Store backed by the append-only per-project task log at
// path (see paths.TasksLogPath), in ADR 0025 log mode. sessionHarp is stamped
// as the origin on created tasks and the actor on status/remove events; it may
// be empty (e.g. a bare CLI invocation outside a session).
func OpenLog(path, sessionHarp string) (*Store, error) {
	if path == "" {
		return nil, fmt.Errorf("log path required")
	}
	return &Store{path: path, log: &eventLog{path: path, session: sessionHarp}}, nil
}

// Path returns the absolute path of the tasks file.
func (s *Store) Path() string { return s.path }

// List returns tasks filtered by status (empty = all statuses) and term
// (empty = no filter). Term is matched case-insensitively as a substring
// of the trimmed task text.
func (s *Store) List(statuses []string, term string) ([]Task, error) {
	if s.log != nil {
		return s.log.list(statuses, term)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	all, err := s.snapshot()
	if err != nil {
		return nil, err
	}
	return filterTasks(all, statuses, term), nil
}

// Add appends a new task with an auto-generated unique harp ID. Empty
// status defaults to StatusToDo. Returns the persisted task.
func (s *Store) Add(text, status string) (Task, error) {
	if s.log != nil {
		return s.log.add(text, status)
	}
	text = strings.TrimSpace(text)
	if text == "" {
		return Task{}, fmt.Errorf("text required")
	}
	if status == "" {
		status = StatusToDo
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	unlock, err := filelock.Lock(s.path + ".lock")
	if err != nil {
		return Task{}, fmt.Errorf("lock: %w", err)
	}
	defer unlock()

	all, err := s.snapshot()
	if err != nil {
		return Task{}, err
	}
	task := Task{
		HarpID:   uniqueHarpID(all),
		Text:     text,
		Status:   status,
		Checked:  statusIsDone(status),
		TextHash: hashText(text),
	}
	all = append(all, task)
	if err := s.write(all); err != nil {
		return Task{}, err
	}
	return task, nil
}

// insert adds a task while preserving an explicit harp id (unlike Add, which
// generates one). A pre-existing task with the same harp id is replaced in
// place. Empty status defaults to StatusToDo. Checked/TextHash are derived.
// Returns the persisted task. Used by MoveTask to carry a task's identity
// across stores.
func (s *Store) insert(t Task) (Task, error) {
	t.Text = strings.TrimSpace(t.Text)
	if t.Text == "" {
		return Task{}, fmt.Errorf("text required")
	}
	if t.HarpID == "" {
		return Task{}, fmt.Errorf("harp id required")
	}
	if t.Status == "" {
		t.Status = StatusToDo
	}
	t.Checked = statusIsDone(t.Status)
	t.TextHash = hashText(t.Text)

	s.mu.Lock()
	defer s.mu.Unlock()
	unlock, err := filelock.Lock(s.path + ".lock")
	if err != nil {
		return Task{}, fmt.Errorf("lock: %w", err)
	}
	defer unlock()

	all, err := s.snapshot()
	if err != nil {
		return Task{}, err
	}
	replaced := false
	for i := range all {
		if all[i].HarpID == t.HarpID {
			all[i] = t
			replaced = true
			break
		}
	}
	if !replaced {
		all = append(all, t)
	}
	if err := s.write(all); err != nil {
		return Task{}, err
	}
	return t, nil
}

// Remove deletes the task with harpID and returns the removed task. Errors if
// the harp ID isn't present.
func (s *Store) Remove(harpID string) (Task, error) {
	if s.log != nil {
		return s.log.remove(harpID)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	unlock, err := filelock.Lock(s.path + ".lock")
	if err != nil {
		return Task{}, fmt.Errorf("lock: %w", err)
	}
	defer unlock()

	all, err := s.snapshot()
	if err != nil {
		return Task{}, err
	}
	for i := range all {
		if all[i].HarpID != harpID {
			continue
		}
		removed := all[i]
		all = append(all[:i], all[i+1:]...)
		if err := s.write(all); err != nil {
			return Task{}, err
		}
		return removed, nil
	}
	return Task{}, fmt.Errorf("task not found: %s", harpID)
}

// SetStatus moves a task to a different section. Errors if the harp ID
// isn't present.
func (s *Store) SetStatus(harpID, status string) (Task, error) {
	if s.log != nil {
		return s.log.setStatus(harpID, status)
	}
	if status == "" {
		return Task{}, fmt.Errorf("status required")
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	unlock, err := filelock.Lock(s.path + ".lock")
	if err != nil {
		return Task{}, fmt.Errorf("lock: %w", err)
	}
	defer unlock()

	all, err := s.snapshot()
	if err != nil {
		return Task{}, err
	}
	for i := range all {
		if all[i].HarpID != harpID {
			continue
		}
		all[i].Status = status
		all[i].Checked = statusIsDone(status)
		if err := s.write(all); err != nil {
			return Task{}, err
		}
		return all[i], nil
	}
	return Task{}, fmt.Errorf("task not found: %s", harpID)
}

// Snapshot returns every task in the store, in file order.
func (s *Store) Snapshot() ([]Task, error) {
	if s.log != nil {
		return s.log.snapshot()
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.snapshot()
}

// Repair re-introduces any displaced duplicate-add the log detected, under a
// fresh harp (idempotent). No-op for the legacy markdown store.
func (s *Store) Repair() error {
	if s.log != nil {
		return s.log.repair()
	}
	return nil
}

// Import seeds a log-backed store with pre-existing tasks (preserving harp
// identity and origin), skipping any whose harp is already present. Requires a
// log-backed store.
func (s *Store) Import(in []Task) error {
	if s.log == nil {
		return fmt.Errorf("import requires a log-backed store")
	}
	return s.log.importTasks(in)
}

// Summary holds counts per status and the harp IDs currently in-progress.
type Summary struct {
	Counts     map[string]int
	InProgress []string
}

// Summarize counts tasks per status. Deterministic; no LLM call. Used by
// the task_summary MCP surface and as the source for the one-line summary
// written to ~/.ctxloom/sessions/<harp>/tasks.md on compaction.
func (s *Store) Summarize() (Summary, error) {
	if s.log != nil {
		return s.log.summarize()
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	all, err := s.snapshot()
	if err != nil {
		return Summary{}, err
	}
	out := Summary{Counts: map[string]int{}}
	for _, t := range all {
		out.Counts[t.Status]++
		if t.Status == StatusInProgress {
			out.InProgress = append(out.InProgress, t.HarpID)
		}
	}
	return out, nil
}

// --- internals ---

func (s *Store) snapshot() ([]Task, error) {
	data, err := os.ReadFile(s.path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return parseFile(string(data)), nil
}

// write atomically rewrites the file. Callers must hold s.mu and the file
// lock. A unique temp name (rather than a fixed "<path>.tmp") keeps
// concurrent writers — even ones that slip past the advisory lock — from
// clobbering each other's in-flight temp file before the rename.
func (s *Store) write(tasks []Task) error {
	dir := filepath.Dir(s.path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	body := renderFile(tasks)
	tmp, err := os.CreateTemp(dir, ".tasks-*.md.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	if _, err := tmp.WriteString(body); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	if err := os.Chmod(tmpName, 0o644); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	if err := os.Rename(tmpName, s.path); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	return nil
}

func statusIsDone(status string) bool {
	return status == StatusDone || status == StatusArchived
}

func hashText(s string) string {
	h := sha256.Sum256([]byte(strings.TrimSpace(s)))
	return hex.EncodeToString(h[:])[:12]
}

func uniqueHarpID(existing []Task) string {
	seen := make(map[string]struct{}, len(existing))
	for _, t := range existing {
		seen[t.HarpID] = struct{}{}
	}
	return uniqueHarpIDFromSet(seen)
}

// uniqueHarpIDFromSet picks a fresh short harp id not already in `used`. Tasks
// use the two-word short harp (adj-noun): per-project task counts are small, so
// the smaller identity space is ample and the ids stay tidy in the list. 100
// attempts is overkill against the name space and a small set; the log backend's
// mint-with-check (and the fold-and-repair pass) cover the residual case.
func uniqueHarpIDFromSet(used map[string]struct{}) string {
	for range 100 {
		id := harp.GenerateShortName()
		if _, dup := used[id]; !dup {
			return id
		}
	}
	return harp.GenerateShortName()
}

func filterTasks(all []Task, statuses []string, term string) []Task {
	var statusSet map[string]bool
	if len(statuses) > 0 {
		statusSet = make(map[string]bool, len(statuses))
		for _, s := range statuses {
			statusSet[s] = true
		}
	}
	termLower := strings.ToLower(strings.TrimSpace(term))
	out := make([]Task, 0, len(all))
	for _, t := range all {
		if statusSet != nil && !statusSet[t.Status] {
			continue
		}
		if termLower != "" && !strings.Contains(strings.ToLower(t.Text), termLower) {
			continue
		}
		out = append(out, t)
	}
	return out
}

// --- parsing / rendering ---

// taskLine matches `- [ ] \`harp-id\` text` or `- [x] \`harp-id\` text`.
// The harp-id is restricted to [a-z][a-z0-9-]* to match the harp generator.
var taskLine = regexp.MustCompile("^- \\[([ x])\\] `([a-z][a-z0-9-]*)` (.+)$")

// sectionHeader matches `## Status Name`.
var sectionHeader = regexp.MustCompile(`^## (.+?)\s*$`)

const fileHeader = "# Tasks\n\n<!-- ctxloom-tasks:v1 -->\n\n"

func parseFile(s string) []Task {
	var tasks []Task
	var currentStatus string
	for line := range strings.SplitSeq(s, "\n") {
		if m := sectionHeader.FindStringSubmatch(line); m != nil {
			currentStatus = strings.TrimSpace(m[1])
			continue
		}
		if currentStatus == "" {
			continue
		}
		m := taskLine.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		text := strings.TrimSpace(m[3])
		tasks = append(tasks, Task{
			HarpID:   m[2],
			Text:     text,
			Status:   currentStatus,
			Checked:  m[1] == "x",
			TextHash: hashText(text),
		})
	}
	return tasks
}

func renderFile(tasks []Task) string {
	// Group by status, preserving relative order within each section.
	byStatus := make(map[string][]Task, len(DefaultStatusOrder))
	statusSeen := make(map[string]bool, len(DefaultStatusOrder))
	statusOrder := make([]string, 0, len(DefaultStatusOrder)+2)
	for _, s := range DefaultStatusOrder {
		statusSeen[s] = true
		statusOrder = append(statusOrder, s)
	}
	for _, t := range tasks {
		byStatus[t.Status] = append(byStatus[t.Status], t)
		if !statusSeen[t.Status] {
			statusSeen[t.Status] = true
			statusOrder = append(statusOrder, t.Status)
		}
	}

	var b strings.Builder
	b.WriteString(fileHeader)
	for _, status := range statusOrder {
		bucket := byStatus[status]
		if len(bucket) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n", status)
		for _, t := range bucket {
			check := " "
			if t.Checked {
				check = "x"
			}
			fmt.Fprintf(&b, "- [%s] `%s` %s\n", check, t.HarpID, t.Text)
		}
		b.WriteString("\n")
	}
	return b.String()
}
