// Package tasks provides a flesler-style file-backed task store keyed by
// harp IDs (see internal/harp). The file format is human-editable
// markdown sectioned by status, e.g.:
//
//	# Tasks
//
//	<!-- ctxloom-tasks:v1 -->
//
//	## In Progress
//	- [ ] `swift-amber-falcon` implement TodoWrite hook
//
//	## To Do
//	- [ ] `quiet-silver-meadow` write storage layer
//
//	## Done
//	- [x] `misty-golden-river` spike session naming
//
// v1 caveat: non-task lines between tasks (free-form notes, blockquotes,
// etc.) are NOT preserved across mutations. The file is rewritten in a
// canonical shape on every Store.Add / SetStatus / Reconcile. If you want
// to keep notes alongside tasks, put them elsewhere for now. This will be
// addressed in a v2 if needed.
package tasks

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/ctxloom/ctxloom/internal/harp"
)

// Default status names. flesler is configurable via env vars; we hardcode
// in v1 and revisit if user-defined statuses become a real need.
const (
	StatusInProgress = "In Progress"
	StatusToDo       = "To Do"
	StatusDone       = "Done"
	StatusArchived   = "Archived"
)

// DefaultStatusOrder is the canonical section order in tasks.md.
var DefaultStatusOrder = []string{StatusInProgress, StatusToDo, StatusDone, StatusArchived}

// Task is one row in tasks.md.
type Task struct {
	HarpID   string // "swift-amber-falcon" — generated by internal/harp
	Text     string // trimmed, no harp ID inside
	Status   string // section name; one of DefaultStatusOrder or user-supplied
	Checked  bool   // true when status is Done/Archived; tracks the `[x]` bit on disk
	TextHash string // sha256(trimmed text), hex-encoded, first 12 chars
}

// Store is a file-backed task store. tasks.md is the source of truth;
// every mutation reads, modifies, and atomically rewrites the file.
type Store struct {
	path string
}

// Open returns a Store rooted at <projectDir>/.ctxloom/tasks.md. The file
// is created lazily on first Add; reads of a missing file return an empty
// task list with no error.
func Open(projectDir string) (*Store, error) {
	if projectDir == "" {
		return nil, fmt.Errorf("projectDir required")
	}
	return &Store{path: filepath.Join(projectDir, ".ctxloom", "tasks.md")}, nil
}

// Path returns the absolute path of the tasks file.
func (s *Store) Path() string { return s.path }

// List returns tasks filtered by status (empty = all statuses) and term
// (empty = no filter). Term is matched case-insensitively as a substring
// of the trimmed task text.
func (s *Store) List(statuses []string, term string) ([]Task, error) {
	all, err := s.snapshot()
	if err != nil {
		return nil, err
	}
	return filterTasks(all, statuses, term), nil
}

// Add appends a new task with an auto-generated unique harp ID. Empty
// status defaults to StatusToDo. Returns the persisted task.
func (s *Store) Add(text, status string) (Task, error) {
	text = strings.TrimSpace(text)
	if text == "" {
		return Task{}, fmt.Errorf("text required")
	}
	if status == "" {
		status = StatusToDo
	}
	all, err := s.snapshot()
	if err != nil {
		return Task{}, err
	}
	task := Task{
		HarpID:   uniqueHarpID(all),
		Text:     text,
		Status:   status,
		Checked:  statusIsDone(status),
		TextHash: hashText(text),
	}
	all = append(all, task)
	if err := s.write(all); err != nil {
		return Task{}, err
	}
	return task, nil
}

// SetStatus moves a task to a different section. Errors if the harp ID
// isn't present.
func (s *Store) SetStatus(harpID, status string) (Task, error) {
	if status == "" {
		return Task{}, fmt.Errorf("status required")
	}
	all, err := s.snapshot()
	if err != nil {
		return Task{}, err
	}
	for i := range all {
		if all[i].HarpID != harpID {
			continue
		}
		all[i].Status = status
		all[i].Checked = statusIsDone(status)
		if err := s.write(all); err != nil {
			return Task{}, err
		}
		return all[i], nil
	}
	return Task{}, fmt.Errorf("task not found: %s", harpID)
}

// Snapshot returns every task in the store, in file order.
func (s *Store) Snapshot() ([]Task, error) { return s.snapshot() }

// Summary holds counts per status and the harp IDs currently in-progress.
type Summary struct {
	Counts     map[string]int
	InProgress []string
}

// Summarize counts tasks per status. Deterministic; no LLM call. Used by
// the task_summary MCP surface and as the source for the one-line summary
// written to ~/.ctxloom/sessions/<harp>/tasks.md on compaction.
func (s *Store) Summarize() (Summary, error) {
	all, err := s.snapshot()
	if err != nil {
		return Summary{}, err
	}
	out := Summary{Counts: map[string]int{}}
	for _, t := range all {
		out.Counts[t.Status]++
		if t.Status == StatusInProgress {
			out.InProgress = append(out.InProgress, t.HarpID)
		}
	}
	return out, nil
}

// --- internals ---

func (s *Store) snapshot() ([]Task, error) {
	data, err := os.ReadFile(s.path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return parseFile(string(data)), nil
}

func (s *Store) write(tasks []Task) error {
	if err := os.MkdirAll(filepath.Dir(s.path), 0o755); err != nil {
		return err
	}
	body := renderFile(tasks)
	tmp := s.path + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, s.path)
}

func statusIsDone(status string) bool {
	return status == StatusDone || status == StatusArchived
}

func hashText(s string) string {
	h := sha256.Sum256([]byte(strings.TrimSpace(s)))
	return hex.EncodeToString(h[:])[:12]
}

func uniqueHarpID(existing []Task) string {
	seen := make(map[string]struct{}, len(existing))
	for _, t := range existing {
		seen[t.HarpID] = struct{}{}
	}
	// 100 attempts is overkill: with 5.6M name combinations and a small
	// existing set, collision probability is vanishingly low.
	for range 100 {
		id := harp.GenerateName()
		if _, dup := seen[id]; !dup {
			return id
		}
	}
	return harp.GenerateName()
}

func filterTasks(all []Task, statuses []string, term string) []Task {
	var statusSet map[string]bool
	if len(statuses) > 0 {
		statusSet = make(map[string]bool, len(statuses))
		for _, s := range statuses {
			statusSet[s] = true
		}
	}
	termLower := strings.ToLower(strings.TrimSpace(term))
	out := make([]Task, 0, len(all))
	for _, t := range all {
		if statusSet != nil && !statusSet[t.Status] {
			continue
		}
		if termLower != "" && !strings.Contains(strings.ToLower(t.Text), termLower) {
			continue
		}
		out = append(out, t)
	}
	return out
}

// --- parsing / rendering ---

// taskLine matches `- [ ] \`harp-id\` text` or `- [x] \`harp-id\` text`.
// The harp-id is restricted to [a-z][a-z0-9-]* to match the harp generator.
var taskLine = regexp.MustCompile("^- \\[([ x])\\] `([a-z][a-z0-9-]*)` (.+)$")

// sectionHeader matches `## Status Name`.
var sectionHeader = regexp.MustCompile(`^## (.+?)\s*$`)

const fileHeader = "# Tasks\n\n<!-- ctxloom-tasks:v1 -->\n\n"

func parseFile(s string) []Task {
	var tasks []Task
	var currentStatus string
	for line := range strings.SplitSeq(s, "\n") {
		if m := sectionHeader.FindStringSubmatch(line); m != nil {
			currentStatus = strings.TrimSpace(m[1])
			continue
		}
		if currentStatus == "" {
			continue
		}
		m := taskLine.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		text := strings.TrimSpace(m[3])
		tasks = append(tasks, Task{
			HarpID:   m[2],
			Text:     text,
			Status:   currentStatus,
			Checked:  m[1] == "x",
			TextHash: hashText(text),
		})
	}
	return tasks
}

func renderFile(tasks []Task) string {
	// Group by status, preserving relative order within each section.
	byStatus := make(map[string][]Task, len(DefaultStatusOrder))
	statusSeen := make(map[string]bool, len(DefaultStatusOrder))
	statusOrder := make([]string, 0, len(DefaultStatusOrder)+2)
	for _, s := range DefaultStatusOrder {
		statusSeen[s] = true
		statusOrder = append(statusOrder, s)
	}
	for _, t := range tasks {
		byStatus[t.Status] = append(byStatus[t.Status], t)
		if !statusSeen[t.Status] {
			statusSeen[t.Status] = true
			statusOrder = append(statusOrder, t.Status)
		}
	}

	var b strings.Builder
	b.WriteString(fileHeader)
	for _, status := range statusOrder {
		bucket := byStatus[status]
		if len(bucket) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n", status)
		for _, t := range bucket {
			check := " "
			if t.Checked {
				check = "x"
			}
			fmt.Fprintf(&b, "- [%s] `%s` %s\n", check, t.HarpID, t.Text)
		}
		b.WriteString("\n")
	}
	return b.String()
}
