// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: internal/lm/grpc/generator.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratorInfo) Reset() {
	*x = GeneratorInfo{}
	mi := &file_internal_lm_grpc_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratorInfo) ProtoMessage() {}

func (x *GeneratorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lm_grpc_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratorInfo.ProtoReflect.Descriptor instead.
func (*GeneratorInfo) Descriptor() ([]byte, []int) {
	return file_internal_lm_grpc_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeneratorInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GeneratorInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`                                                                         // Arguments passed to the generator
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables
	WorkDir       string                 `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`                                                    // Working directory
	Verbosity     uint32                 `protobuf:"varint,4,opt,name=verbosity,proto3" json:"verbosity,omitempty"`                                                              // 0=silent, 10=commands, 20=args, 30+=debug
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_internal_lm_grpc_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lm_grpc_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_internal_lm_grpc_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *GenerateRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *GenerateRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *GenerateRequest) GetVerbosity() uint32 {
	if x != nil {
		return x.Verbosity
	}
	return 0
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                                                           // The fragment content (markdown)
	Exports       map[string]string      `protobuf:"bytes,2,rep,name=exports,proto3" json:"exports,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Variables to export to other fragments
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`                                                        // Exit code (0 = success)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                                                               // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_internal_lm_grpc_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lm_grpc_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_internal_lm_grpc_generator_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateResponse) GetExports() map[string]string {
	if x != nil {
		return x.Exports
	}
	return nil
}

func (x *GenerateResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *GenerateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_lm_grpc_generator_proto protoreflect.FileDescriptor

const file_internal_lm_grpc_generator_proto_rawDesc = "" +
	"\n" +
	" internal/lm/grpc/generator.proto\x12\x10scm.lm.generator\x1a\x1dinternal/lm/grpc/plugin.proto\"_\n" +
	"\rGeneratorInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xd4\x01\n" +
	"\x0fGenerateRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12<\n" +
	"\x03env\x18\x02 \x03(\v2*.scm.lm.generator.GenerateRequest.EnvEntryR\x03env\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12\x1c\n" +
	"\tverbosity\x18\x04 \x01(\rR\tverbosity\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x10GenerateResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12I\n" +
	"\aexports\x18\x02 \x03(\v2/.scm.lm.generator.GenerateResponse.ExportsEntryR\aexports\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1a:\n" +
	"\fExportsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x9d\x01\n" +
	"\tGenerator\x12=\n" +
	"\x04Info\x12\x14.scm.lm.plugin.Empty\x1a\x1f.scm.lm.generator.GeneratorInfo\x12Q\n" +
	"\bGenerate\x12!.scm.lm.generator.GenerateRequest\x1a\".scm.lm.generator.GenerateResponseB0Z.github.com/benjaminabbitt/scm/internal/lm/grpcb\x06proto3"

var (
	file_internal_lm_grpc_generator_proto_rawDescOnce sync.Once
	file_internal_lm_grpc_generator_proto_rawDescData []byte
)

func file_internal_lm_grpc_generator_proto_rawDescGZIP() []byte {
	file_internal_lm_grpc_generator_proto_rawDescOnce.Do(func() {
		file_internal_lm_grpc_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_lm_grpc_generator_proto_rawDesc), len(file_internal_lm_grpc_generator_proto_rawDesc)))
	})
	return file_internal_lm_grpc_generator_proto_rawDescData
}

var file_internal_lm_grpc_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_lm_grpc_generator_proto_goTypes = []any{
	(*GeneratorInfo)(nil),    // 0: scm.lm.generator.GeneratorInfo
	(*GenerateRequest)(nil),  // 1: scm.lm.generator.GenerateRequest
	(*GenerateResponse)(nil), // 2: scm.lm.generator.GenerateResponse
	nil,                      // 3: scm.lm.generator.GenerateRequest.EnvEntry
	nil,                      // 4: scm.lm.generator.GenerateResponse.ExportsEntry
	(*Empty)(nil),            // 5: scm.lm.plugin.Empty
}
var file_internal_lm_grpc_generator_proto_depIdxs = []int32{
	3, // 0: scm.lm.generator.GenerateRequest.env:type_name -> scm.lm.generator.GenerateRequest.EnvEntry
	4, // 1: scm.lm.generator.GenerateResponse.exports:type_name -> scm.lm.generator.GenerateResponse.ExportsEntry
	5, // 2: scm.lm.generator.Generator.Info:input_type -> scm.lm.plugin.Empty
	1, // 3: scm.lm.generator.Generator.Generate:input_type -> scm.lm.generator.GenerateRequest
	0, // 4: scm.lm.generator.Generator.Info:output_type -> scm.lm.generator.GeneratorInfo
	2, // 5: scm.lm.generator.Generator.Generate:output_type -> scm.lm.generator.GenerateResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_lm_grpc_generator_proto_init() }
func file_internal_lm_grpc_generator_proto_init() {
	if File_internal_lm_grpc_generator_proto != nil {
		return
	}
	file_internal_lm_grpc_plugin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_lm_grpc_generator_proto_rawDesc), len(file_internal_lm_grpc_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_lm_grpc_generator_proto_goTypes,
		DependencyIndexes: file_internal_lm_grpc_generator_proto_depIdxs,
		MessageInfos:      file_internal_lm_grpc_generator_proto_msgTypes,
	}.Build()
	File_internal_lm_grpc_generator_proto = out.File
	file_internal_lm_grpc_generator_proto_goTypes = nil
	file_internal_lm_grpc_generator_proto_depIdxs = nil
}
