// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: internal/lm/grpc/plugin.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIPlugin_Info_FullMethodName = "/scm.lm.plugin.AIPlugin/Info"
	AIPlugin_Run_FullMethodName  = "/scm.lm.plugin.AIPlugin/Run"
)

// AIPluginClient is the client API for AIPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AIPlugin is the gRPC service that all AI backend plugins must implement.
type AIPluginClient interface {
	// Info returns metadata about the plugin.
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	// Run executes the AI backend with the given prompt and context.
	// Streams output back to the caller for real-time display.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunResponse], error)
}

type aIPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAIPluginClient(cc grpc.ClientConnInterface) AIPluginClient {
	return &aIPluginClient{cc}
}

func (c *aIPluginClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, AIPlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIPluginClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIPlugin_ServiceDesc.Streams[0], AIPlugin_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIPlugin_RunClient = grpc.ServerStreamingClient[RunResponse]

// AIPluginServer is the server API for AIPlugin service.
// All implementations must embed UnimplementedAIPluginServer
// for forward compatibility.
//
// AIPlugin is the gRPC service that all AI backend plugins must implement.
type AIPluginServer interface {
	// Info returns metadata about the plugin.
	Info(context.Context, *Empty) (*PluginInfo, error)
	// Run executes the AI backend with the given prompt and context.
	// Streams output back to the caller for real-time display.
	Run(*RunRequest, grpc.ServerStreamingServer[RunResponse]) error
	mustEmbedUnimplementedAIPluginServer()
}

// UnimplementedAIPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIPluginServer struct{}

func (UnimplementedAIPluginServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedAIPluginServer) Run(*RunRequest, grpc.ServerStreamingServer[RunResponse]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedAIPluginServer) mustEmbedUnimplementedAIPluginServer() {}
func (UnimplementedAIPluginServer) testEmbeddedByValue()                  {}

// UnsafeAIPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIPluginServer will
// result in compilation errors.
type UnsafeAIPluginServer interface {
	mustEmbedUnimplementedAIPluginServer()
}

func RegisterAIPluginServer(s grpc.ServiceRegistrar, srv AIPluginServer) {
	// If the following call panics, it indicates UnimplementedAIPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIPlugin_ServiceDesc, srv)
}

func _AIPlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIPluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIPlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIPluginServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIPlugin_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIPluginServer).Run(m, &grpc.GenericServerStream[RunRequest, RunResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIPlugin_RunServer = grpc.ServerStreamingServer[RunResponse]

// AIPlugin_ServiceDesc is the grpc.ServiceDesc for AIPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scm.lm.plugin.AIPlugin",
	HandlerType: (*AIPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _AIPlugin_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _AIPlugin_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/lm/grpc/plugin.proto",
}
