package runner

import (
	"github.com/ctxloom/ctxloom/internal/shared/report"

	"io"
	"sync"
	"sync/atomic"
	"time"

	agentcoordpb "github.com/ctxloom/ctxloom/internal/adapters/coordgrpc/pb"
	"github.com/ctxloom/ctxloom/internal/core/agent"
)

// TERMINAL INJECTION — the delivery half of the session-owner's wake.
//
// A child's arrival wakes it structurally: SetTurnSink hands the pushed
// message straight to the engine as a new turn. A session-owner Home never
// gets a turn sink (no EngineHost is ever built for it — see
// llm_runner_common.go), so deliverNotice's third case buffers the message
// and calls terminalNudge instead. TerminalInjector is what that hook is set
// to: it turns "mail arrived, nobody had a route to give it" into a literal
// keystroke in the engine's own stdin, so the SAME mechanism that lets a
// human type into a running session (the interceptor/PTY seam) also carries
// the coordinator's own wake.
//
// The injected text is a generated ctxloom-reminder frame
// (MailPendingReminder.XmlLike, "call agent_recv") — the wire format this
// repo already defines for exactly this purpose (coordination.proto: "NEVER
// WIRE TRAFFIC; exist to be rendered into injected ... frames", generated by
// xmllike_gen.go) and had zero callers before this file. It reads to the
// engine as if the human had typed a direct instruction, which is what makes
// it something the model ACTS on rather than narrates.

const (
	// terminalInjectQuiet is how long the engine's own output must have been
	// silent before an injection is considered safe: long enough that a
	// normal inter-token gap during streaming doesn't look quiet, short
	// enough that a genuinely idle engine is nudged promptly.
	terminalInjectQuiet = 500 * time.Millisecond
	// terminalInjectTick is how often quiet is re-checked.
	terminalInjectTick = 25 * time.Millisecond
	// terminalInjectMaxWait bounds the total wait. Reaching it is not an
	// error — there is no turn-boundary signal available to a terminal-driven
	// engine to wait for instead, so past this bound the injector delivers
	// anyway rather than risk waiting forever on an engine that is idling
	// noisily (a spinner, a heartbeat) and never looks quiet by the strict
	// definition above.
	terminalInjectMaxWait = 4 * time.Second
	// terminalInjectSubmitGap separates the frame from the Enter that submits
	// it. What the split defeats is real: measured against claude 2.1.251, a
	// frame and CR arriving in ONE read submit 0/5, because a TUI guessing at
	// a paste boundary swallows the CR as literal text. Split across two
	// reads it submits at every gap tried.
	//
	// The operative variable is READ SEPARATION, not elapsed time. The
	// threshold lies between 0ms and 5ms: >=5ms submits 3/3 and 2000ms is no
	// better than 5ms, because any scheduling delay at all is enough to put
	// the CR in its own read. This value therefore carries ~30x margin over
	// its own requirement. RAISING IT BUYS NOTHING MEASURABLE — if a wake is
	// not landing, the cause is elsewhere; do not reach for this constant.
	//
	// The gap alone is not the mechanism; the READER owns the split (see
	// nudgeReader.Read), because two chunks spaced only in the producer still
	// land in a single Read.
	//
	// A strictly better mechanism exists and is NOT yet adopted: claude
	// advertises bracketed paste (ESC[?2004h) and never disables it, and an
	// explicitly delimited paste followed by CR submits 5/5 in a SINGLE write
	// with no gap and no reader-owned split at all. Told where the paste
	// ends, the TUI stops guessing and treats the CR as a keypress.
	// terminalInjectInputQuiet is how long after the HUMAN's last keystroke an
	// injection is withheld. Output-quiet is not enough on its own: a terminal
	// is also quiet while someone is composing a line, and a frame delivered
	// then lands INSIDE their half-typed input and splits it. That is strictly
	// worse than a late wake, because the mail is still buffered for the next
	// Recv while the typed line is simply gone.
	//
	// JUDGEMENT, NOT A MEASUREMENT: 20s is chosen to clear a THINKING pause,
	// not merely a mid-sentence one. A person composing an instruction stops
	// for far longer than a typing rhythm while deciding what to say, and the
	// cost of the two errors is wildly asymmetric: waiting too long delays a
	// wake whose mail stays buffered for the next Recv, while firing too early
	// destroys a line the human cannot get back. When in doubt this constant
	// should be too LARGE.
	// Refining it means measuring real inter-keystroke gaps during
	// composition, which nobody has done; do not treat this number as carrying
	// evidence the way terminalInjectSubmitGap does.
	terminalInjectInputQuiet = 20 * time.Second
	terminalInjectSubmitGap  = 150 * time.Millisecond
	// terminalInjectAckWait bounds how long an injection cycle watches for
	// proof that the wake LANDED: the engine taking a turn and calling
	// agent_recv is what drains the buffer, so a falling mail count is the
	// only observable the terminal path has. It is generous because it spans
	// a model's wake, read and tool call, not just I/O.
	terminalInjectAckWait = 45 * time.Second
	// terminalInjectAckTick is how often that proof is re-checked.
	terminalInjectAckTick = 250 * time.Millisecond
)

// TerminalInjector is a Home's registered terminalNudge target. Construct ONE
// per Home and call Wrap at the start of each interactive turn, as that turn's
// stdin/stdout become available, to obtain the seams Execute should hand the
// engine. Wrap re-points the injection target, so the latest turn owns it.
//
// Do NOT construct one per turn: SetTerminalNudge refuses a second
// registration, so a per-turn injector leaves the registered nudge bound to
// the first turn's reader — which nothing drains once that turn is over, and
// the mail is injected into a stream no one is listening to.
type TerminalInjector struct {
	quiet, tick, maxWait time.Duration
	inputQuiet           time.Duration
	ackWait, ackTick     time.Duration

	lastWrite atomic.Int64 // unix nanos of the last stdout passthrough write
	lastInput atomic.Int64 // unix nanos of the last REAL keystroke read from stdin

	// gate is the ENGINE's own reading of whether it is accepting free text
	// or a keypress. coord owns the plumbing and the engine owns the
	// knowledge: the escape sequences that answer this are engine- and
	// version-specific, and embedding them here would put one engine's
	// terminal behaviour in the engine-agnostic coordination core, where no
	// other engine could correct it.
	//
	// nil means the engine implements no gate, which is NOT the same as
	// "safe". See run: an engine that has given no signal is refused.
	gate agent.InputGate
	// rep is the Home's Reporter: the injector is built on one Home and
	// reports where it does.
	rep report.Reporter
	// gateWarn makes the refusal above loud exactly once per injector, rather
	// than on every nudge. Silence here would be the project's characteristic
	// failure — a wake that never fires and never says why.
	gateWarn sync.Once

	mu      sync.Mutex
	waiting bool // an injection cycle is already scheduled/running
	// inject takes the frame and its submit as ONE unit. Two separate calls
	// would be silent corruption, not a split: the reader's queue holds a
	// single pending item and EVICTS to make room, so a bare "\r" arriving
	// before the frame was consumed would REPLACE the notice and submit an
	// empty line instead.
	inject func(frame, submit string)
	// injectGen identifies WHICH turn owns inject. Wrap stamps a fresh value
	// and its release clears inject only if the stamp still matches, because
	// the injector outlives any one turn: turn N+1 can Wrap before turn N's
	// deferred release runs, and an unconditional nil there would disarm the
	// LIVE turn's wake — silently, since injection into a nil target is a
	// no-op that reports nothing. A generation counter and not the func value
	// itself: func values are not comparable in Go, so identity has to be
	// carried explicitly.
	injectGen uint64
	count     func() int
	// parked reports whether a receive is parked on the Home: the engine is
	// already collecting, so a reminder to do so is redundant.
	parked func() bool
}

// NewTerminalInjector builds an injector for home and registers it as home's
// terminal nudge immediately: a nudge that fires before Wrap is called finds
// inject nil and is a no-op (the message stays buffered for the next nudge,
// or a real Recv), rather than lost.
// gate is the engine's optional InputGate capability, discovered by the caller
// via a type assertion on the backend. Passing nil is meaningful and safe: the
// injector then REFUSES to inject rather than assuming the terminal is idle.
func NewTerminalInjector(home *Home, gate agent.InputGate) *TerminalInjector {
	ti := &TerminalInjector{
		rep:        home.rep,
		gate:       gate,
		quiet:      terminalInjectQuiet,
		inputQuiet: terminalInjectInputQuiet,
		tick:       terminalInjectTick,
		maxWait:    terminalInjectMaxWait,
		ackWait:    terminalInjectAckWait,
		ackTick:    terminalInjectAckTick,
		count:      home.BufferedMailCount,
		parked:     home.RecvParked,
	}
	home.SetTerminalNudge(ti.nudge)
	return ti
}

// Wrap returns the stdin/stdout an interactive Execute should use in place of
// the real terminal seams: stdout is tapped for the quiet signal (every
// passthrough write resets the idle clock), and stdin gains the injection
// channel a nudge cycle writes into. Calling it again retargets injection at
// the new turn's stdin; that is how successive turns take ownership of the one
// registered nudge.
//
// The third return is that turn's RELEASE, and the caller must defer it as
// soon as the wrap is applied. The injector has HOME lifetime; the stream it
// writes into has TURN lifetime, and without a release the two never
// reconcile: mail arriving after the turn ends is injected into a reader
// nobody will ever Read. Inject is deliberately non-blocking, so that
// succeeds, the buffered count never falls, and awaitAck 45s later reports a
// frame "staged in the input box unsubmitted" — naming the wrong cause, since
// there is no live turn at all. Releasing puts the injector back in its
// pre-Wrap state, where run() leaves the mail buffered for a real Recv.
func (ti *TerminalInjector) Wrap(stdin io.Reader, stdout io.Writer) (io.Reader, io.Writer, func()) {
	r := newNudgeReader(stdin, &ti.lastInput)
	ti.mu.Lock()
	ti.injectGen++
	gen := ti.injectGen
	ti.inject = r.Inject
	ti.mu.Unlock()
	release := func() {
		ti.mu.Lock()
		defer ti.mu.Unlock()
		if ti.injectGen != gen {
			return // a later turn already took the target; it is not ours to clear
		}
		ti.inject = nil
	}
	return r, &quietTap{dst: stdout, lastWrite: &ti.lastWrite, gate: ti.gate}, release
}

// nudge is home's terminalNudge callback: it must not block (deliverNotice
// calls it inline, on the goroutine that just received the coordinator's
// push), so it only arms a background wait-and-inject cycle, coalescing
// concurrent arrivals into the one cycle already running.
func (ti *TerminalInjector) nudge() {
	ti.mu.Lock()
	if ti.waiting {
		ti.mu.Unlock()
		return
	}
	ti.waiting = true
	ti.mu.Unlock()
	go ti.run()
}

// run waits for quiet (or the bound) and then injects, if there is still
// anything to report — a Recv the engine made on its own between the nudge
// and now may already have drained the buffer, in which case there is
// nothing to say and injecting would be a stale, content-free interruption.
func (ti *TerminalInjector) run() {
	defer func() {
		ti.mu.Lock()
		ti.waiting = false
		ti.mu.Unlock()
	}()
	// An engine that implements no InputGate has said NOTHING about whether a
	// write would land in a text field or be swallowed by a modal, and this
	// path writes a carriage return. Absent a signal, refuse: silence is not
	// consent, and the failure it prevents (a wake selecting an option in an
	// open prompt) is unrecoverable, while the cost of refusing is only a
	// delayed wake whose mail agent_recv still collects.
	if ti.gate == nil {
		ti.gateWarn.Do(func() {
			ti.rep.Warnf("coordinator: this engine publishes no input-state gate, so terminal wakes are withheld to avoid answering a prompt for you; " +
				"the mail stays buffered and agent_recv still collects it. Measure this engine's modal markers and implement agent.InputGate to turn wakes back on")
		})
		return
	}
	deadline := time.Now().Add(ti.maxWait)
	for {
		now := time.Now().UnixNano()
		outIdle := time.Duration(now - ti.lastWrite.Load())
		inIdle := time.Duration(now - ti.lastInput.Load())
		// Asked once per pass and reused below, so the decision to break and
		// the decision to give up cannot disagree about what the gate said.
		accepting := ti.gate.AcceptingText()
		if outIdle >= ti.quiet && inIdle >= ti.inputQuiet && accepting {
			break
		}
		if !time.Now().Before(deadline) {
			// THE DEADLINE WAIVES OUTPUT-QUIET, NEVER INPUT-QUIET AND NEVER
			// THE INPUT GATE. Waiving
			// output-quiet is what the maxWait comment describes: an engine
			// idling noisily must not block the wake forever. Waiving
			// input-quiet would deliver a frame into a half-typed line and
			// split it, and the two failures are not comparable — a withheld
			// wake leaves the mail buffered for the next Recv, while the
			// human's typed line is unrecoverable. So give up this cycle
			// instead; nudge re-arms when the next mail arrives, and Recv
			// collects it regardless.
			//
			// The gate belongs in that same class for a stronger reason. A
			// split line is destroyed input; a wake delivered into a modal
			// MANUFACTURES input, and the record then shows a ruling the
			// human never gave. If a deadline could waive it, the guard would
			// be exactly as good as no guard on any session busy enough to
			// reach the bound.
			if inIdle < ti.inputQuiet || !accepting {
				return
			}
			break
		}
		time.Sleep(ti.tick)
	}
	ti.mu.Lock()
	inject := ti.inject
	ti.mu.Unlock()
	if inject == nil {
		return // Wrap was never called: no interactive stdin exists to inject into
	}
	if ti.parked != nil && ti.parked() {
		// A receive is parked: the engine is already collecting, so a
		// reminder to call agent_recv would interrupt the very call it asks
		// for. The mail completes that receive; nothing is lost by standing
		// down, and the next arrival with no park re-arms.
		return
	}
	if n := ti.count(); n > 0 {
		// "\r", not "\n": an interactive engine holds the terminal in RAW
		// mode, so the kernel's ICRNL input translation is off and the Enter
		// KEY is carriage return (0x0D). A line feed lands in the engine's
		// input buffer as literal text that is never submitted — the frame is
		// visible, the model never acts on it, and the mail sits unread until
		// the session takes a turn for some unrelated reason.
		//
		// The CR is handed over as the frame's SUBMIT, not concatenated onto
		// it: the reader spaces the two so the TUI sees a keypress rather
		// than pasted text (see terminalInjectSubmitGap).
		inject((&agentcoordpb.MailPendingReminder{Count: uint32(n)}).XmlLike(), "\r")
		// Watch for the wake landing on its own goroutine, so the coalescing
		// latch (ti.waiting, cleared by the defer above) is not held for the
		// whole acknowledgement window — mail arriving meanwhile must still
		// be able to arm a fresh cycle.
		go ti.awaitAck(n)
	}
}

// awaitAck watches for evidence that the injected wake actually produced a
// turn: the engine acting on the frame calls agent_recv, which drains the
// buffer, so a mail count that falls below what was reported is the landing
// signal. If it never falls, the injection was typed and not submitted (or
// not read at all) and that is reported.
//
// This exists because the terminal path had NO feedback channel of any kind,
// which is precisely why a wake that staged the frame and never submitted it
// shipped green: every gate passed while the feature was dark. A warning here
// makes the next regression loud instead of silent.
func (ti *TerminalInjector) awaitAck(before int) {
	deadline := time.Now().Add(ti.ackWait)
	for {
		if ti.count() < before {
			return
		}
		if !time.Now().Before(deadline) {
			break
		}
		time.Sleep(ti.ackTick)
	}
	ti.rep.Warnf("coordinator: injected a mail-pending reminder into this session's terminal but %d message(s) are still unread %s later — "+
		"the frame may be staged in the input box unsubmitted; call agent_recv to collect it",
		before, ti.ackWait)
}

// quietTap wraps an engine's stdout, recording when the last byte actually
// reached it — TerminalInjector's quiet signal. It is a plain pass-through
// otherwise; unlike termui's outputGate (the HOST-side surround's own
// idle heuristic, unreachable from here — this runs in the runner process,
// the host in a separate one) it holds nothing back.
type quietTap struct {
	dst       io.Writer
	lastWrite *atomic.Int64
	// gate, when the engine supplies one, is fed the same bytes so it can
	// track whether a modal is on screen. This tap is the only place coord
	// already sees every byte the engine writes, which is why the capability
	// hangs off it rather than growing a second output seam.
	gate agent.InputGate
}

func (t *quietTap) Write(p []byte) (int, error) {
	n, err := t.dst.Write(p)
	// Observe BEFORE stamping quiet, and observe what was HANDED to us rather
	// than the n the writer reported: a short write still displayed those
	// bytes downstream, and the marker this is looking for may sit past n.
	if t.gate != nil {
		t.gate.Observe(p)
	}
	t.lastWrite.Store(time.Now().UnixNano())
	return n, err
}

// nudgeReader wraps the real interactive stdin so injected text can be
// delivered even while the human is typing nothing at all: a background pump
// is the only way to do that, since the real reader's Read blocks on a live
// terminal with no other way to interrupt it.
type nudgeReader struct {
	inject chan pendingInject
	real   chan []byte
	errCh  chan error

	submitGap time.Duration

	// All three are touched by Read's single caller only; no lock needed.
	// lastInput is stamped on every REAL read and never on an injected one:
	// the point is to know when the HUMAN last typed, and an injected frame is
	// not the human.
	lastInput *atomic.Int64

	leftover      []byte
	pendingSubmit []byte    // the submit owed to an already-delivered frame
	submitAt      time.Time // when that submit becomes deliverable
}

// pendingInject is a frame and its submit held as ONE queue item. They travel
// together because the queue evicts to stay at depth one: as two items, a
// submit could outlive the frame it belongs to and be delivered alone.
type pendingInject struct {
	frame  []byte
	submit []byte
}

func newNudgeReader(real io.Reader, lastInput *atomic.Int64) *nudgeReader {
	r := &nudgeReader{
		lastInput: lastInput,
		inject:    make(chan pendingInject, 1), // coalesced: one pending frame is all there ever is
		real:      make(chan []byte),
		errCh:     make(chan error, 1),
		submitGap: terminalInjectSubmitGap,
	}
	go r.pump(real)
	return r
}

func (r *nudgeReader) pump(real io.Reader) {
	buf := make([]byte, 4096)
	for {
		n, err := real.Read(buf)
		if n > 0 {
			chunk := make([]byte, n)
			copy(chunk, buf[:n])
			r.real <- chunk
		}
		if err != nil {
			r.errCh <- err
			return
		}
	}
}

// Read favors already-injected bytes over the real stream (an injected frame
// should not be stuck behind a keystroke that has not arrived yet), then
// blocks on whichever of the two produces first.
//
// A frame's submit is deliberately NOT returned with the frame. It is held
// back and returned by a LATER Read, once submitGap has elapsed, because a
// TUI treats everything it receives in one read as a paste and renders the
// carriage return as literal text instead of acting on it. Delivering the two
// as separate, time-separated Read returns is what makes the second one read
// as a keypress — spacing them in the producer cannot achieve this, since
// both would still be drained into a single Read.
func (r *nudgeReader) Read(p []byte) (int, error) {
	if len(r.leftover) > 0 {
		n := copy(p, r.leftover)
		r.leftover = r.leftover[n:]
		r.armSubmit()
		return n, nil
	}
	if r.pendingSubmit != nil {
		// Block out the remainder of the gap. Read blocks by nature, so
		// waiting here costs nothing the caller was not already prepared for.
		if d := time.Until(r.submitAt); d > 0 {
			time.Sleep(d)
		}
		chunk := r.pendingSubmit
		r.pendingSubmit, r.submitAt = nil, time.Time{}
		return r.deliver(p, chunk)
	}
	select {
	case item := <-r.inject:
		return r.deliverInject(p, item)
	default:
	}
	select {
	case item := <-r.inject:
		return r.deliverInject(p, item)
	case chunk := <-r.real:
		r.lastInput.Store(time.Now().UnixNano())
		return r.deliver(p, chunk)
	case err := <-r.errCh:
		return 0, err
	}
}

// deliverInject hands back the frame and takes custody of its submit.
func (r *nudgeReader) deliverInject(p []byte, item pendingInject) (int, error) {
	if len(item.submit) > 0 {
		r.pendingSubmit = item.submit
		r.submitAt = time.Time{}
	}
	n, err := r.deliver(p, item.frame)
	r.armSubmit()
	return n, err
}

// armSubmit starts the gap clock once the frame's LAST byte has been handed
// over. A frame too large for one buffer spans several Reads; timing the gap
// from the first would let the submit follow the frame's tail immediately and
// land in the same read, which is the coalescing this exists to defeat.
func (r *nudgeReader) armSubmit() {
	if r.pendingSubmit != nil && len(r.leftover) == 0 && r.submitAt.IsZero() {
		r.submitAt = time.Now().Add(r.submitGap)
	}
}

func (r *nudgeReader) deliver(p, chunk []byte) (int, error) {
	n := copy(p, chunk)
	if n < len(chunk) {
		r.leftover = chunk[n:]
	}
	return n, nil
}

// Inject queues a frame and the submit that actuates it for the next Reads,
// as if they had been typed. It never blocks: the channel holds exactly one
// pending item, which is the coalescing contract (TerminalInjector.run only
// ever has one cycle in flight) — a full channel means a frame is already
// queued and unread, so a second Inject before the first is consumed replaces
// it rather than piling up (the replacement's count is the more current one
// anyway).
//
// frame and submit arrive as one item precisely BECAUSE the queue evicts.
// Were the submit injected by a second call, an undrained frame would be
// evicted by its own carriage return: the notice would vanish and a blank
// line would be submitted in its place — silent corruption, and worse than
// the unsubmitted frame this split exists to fix. The pairing makes that
// unrepresentable rather than merely discouraged.
func (r *nudgeReader) Inject(frame, submit string) {
	item := pendingInject{frame: []byte(frame), submit: []byte(submit)}
	select {
	case r.inject <- item:
	default:
		select {
		case <-r.inject:
		default:
		}
		select {
		case r.inject <- item:
		default:
		}
	}
}
