// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';

export default defineConfig({
	site: 'https://ctxloom.dev',
	redirects: {
		'/concepts/prompts/': '/concepts/commands/',
		'/concepts/skills/': '/concepts/commands/',
		// ltk graduated from an Ecosystem footnote to a top-level section.
		'/ecosystem/llm-tool-killer/': '/ltk/',
	},
	integrations: [
		mermaid(), // Must come BEFORE starlight for diagram rendering
		starlight({
			title: 'ctxloom',
			description: 'Context Loom - Weave context for AI coding agents',
			favicon: '/favicon.ico',
			social: {
				github: 'https://github.com/ctxloom/ctxloom',
			},
			editLink: {
				baseUrl: 'https://github.com/ctxloom/ctxloom/edit/main/website/',
			},
			customCss: ['./src/styles/custom.css'],
			lastUpdated: true,
			sidebar: [
				{
					label: 'Introduction',
					link: '/',
				},
				{
					label: 'Getting Started',
					items: [
						{ label: 'Installation', link: '/getting-started/installation/' },
						{ label: 'Trusting the Binaries', link: '/getting-started/binary-trust/' },
						{ label: 'Quick Start', link: '/getting-started/quickstart/' },
						{ label: 'Authoring Bundles', link: '/getting-started/authoring/' },
						{ label: 'Session Memory', link: '/getting-started/memory/' },
					],
				},
				{
					// Generated by `just gen-living-docs` from @doc-tagged acceptance
					// features (see .github/workflows/docs.yml) — never checked in, so
					// this MUST autogenerate rather than enumerate pages, or a fresh
					// clone with no pages generated yet fails the build on a dead link.
					label: 'Journeys',
					autogenerate: { directory: 'journeys' },
				},
				{
					label: 'Concepts',
					items: [
						{ label: 'Bundles', link: '/concepts/bundles/' },
						{ label: 'Fragments', link: '/concepts/fragments/' },
						{ label: 'Commands', link: '/concepts/commands/' },
						{ label: 'Profiles', link: '/concepts/profiles/' },
						{ label: 'Agents & Isolation', link: '/concepts/agents/' },
						{ label: 'Weave (ensembles)', link: '/concepts/weave/' },
						{ label: 'Remotes', link: '/concepts/remotes/' },
						{ label: 'Review and Trust', link: '/concepts/review-and-trust/' },
						{ label: 'Sessions and Tasks', link: '/concepts/sessions-and-tasks/' },
						{ label: 'Architecture', link: '/concepts/architecture/' },
					],
				},
				{
					label: 'Trust & Security',
					items: [
						{ label: 'A prompt is executable code', link: '/security/prompts-are-code/' },
						{ label: 'Choosing an isolation boundary', link: '/security/environment-isolation/' },
						{ label: 'The engine you don\'t control', link: '/security/isolation/' },
						{ label: 'What a bundle can do to you', link: '/security/bundle-anatomy/' },
						{ label: 'Threat model', link: '/security/threat-model/' },
						{ label: 'Trust states and the gate', link: '/security/trust-states/' },
						{ label: 'Key management', link: '/security/key-management/' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'Configuration', link: '/guides/configuration/' },
						{ label: 'MCP Server', link: '/guides/mcp-server/' },
						{ label: 'Templating', link: '/guides/templating/' },
						{ label: 'Discovery', link: '/guides/discovery/' },
						{ label: 'Hooks', link: '/guides/hooks/' },
						{ label: 'Sharing', link: '/guides/sharing/' },
						{ label: 'Distillation', link: '/guides/distillation/' },
						{ label: 'Ad-hoc Context', link: '/guides/adhoc-context/' },
						{ label: 'Workflows', link: '/guides/workflows/' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'CLI', autogenerate: { directory: 'reference/cli' } },
						{ label: 'MCP Tools', link: '/reference/mcp-tools/' },
						{ label: 'Configuration', link: '/reference/config/' },
						{ label: 'Environment', link: '/reference/environment/' },
					],
				},
				{
					label: 'taskloom',
					items: [
						{ label: 'Overview', link: '/taskloom/' },
						{ label: 'Tags', link: '/taskloom/tags/' },
						{ label: 'CLI', autogenerate: { directory: 'taskloom/reference/cli' } },
						{ label: 'MCP Tools', link: '/taskloom/reference/mcp-tools/' },
					],
				},
				{
					label: 'ltk',
					items: [
						{ label: 'Overview', link: '/ltk/' },
						{ label: 'Writing Rules', link: '/ltk/rules/' },
						{ label: 'CLI', autogenerate: { directory: 'ltk/reference/cli' } },
					],
				},
				{ label: 'Troubleshooting', link: '/troubleshooting/' },
				{ label: 'Contributing', link: '/contributing/' },
			],
		}),
	],
});
